### ISSUE TITLE
Support presto TIMESTAMP

### ISSUE THREAD

**Issue by bkyryliuk** [airbnb/superset#1207]
Support the presto timestamps and the date fields.
Slicing the table that has date column of the time Timestamp generates the query:

```
SELECT COUNT(*) AS "count" 
FROM $TABLE_NAME
WHERE
  call_date >= '2016-09-20 13:57:53.000000' 
     AND 
  call_date <= '2016-09-27 13:57:53.000000'
LIMIT 50000
```

and gives an error:

```
u'java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)', u'java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)', u'java.lang.Thread.run(Thread.java:745)']}, u'errorType': u'USER_ERROR', u'errorName': u'SYNTAX_ERROR', u'errorCode': 1, u'message': u'line 3:19: Operator GREATER_THAN_OR_EQUAL(timestamp, varchar) not registered'}
```

**Comment by mistercrunch** [comment]
https://github.com/airbnb/caravel/issues/1098

**Comment by bkyryliuk** [comment]
workaround:
<img width="910" alt="screen shot 2016-09-27 at 3 47 50 pm" src="https://cloud.githubusercontent.com/assets/5727938/18894778/caffd0c4-84c9-11e6-8086-4aede518d275.png">

**Comment by bkyryliuk** [comment]
Workaround is not good enough - `CAST(to_iso8601(call_date) AS TIMESTAMP)`  fails on the presto side with an error:
`Invalid format: \"2016-09-26T21:39:00.000Z\" is malformed at \"T21:39:00.000Z\"', `

**Comment by bkyryliuk** [comment]
Workaround #2: 
<img width="1280" alt="screen shot 2016-09-28 at 1 44 48 pm" src="https://cloud.githubusercontent.com/assets/5727938/18931623/cc29b722-8581-11e6-889a-1e6497a4375f.png">

**Comment by bkyryliuk** [comment]
Max solved it

**Comment by csevier** [comment]
@bkyryliuk  what was the solution? Im experiencing this now, and asking users to use date.format expression on any timestamp column isnt really that viable. Perhaps ive misunderstood?

**Comment by mistercrunch** [comment]
This was tackled fairly recently. May not be in the latest version.

**Comment by csevier** [comment]
@mistercrunch gotcha, looking forward to solution. Let me know if I can help.

**Comment by dennari** [comment]
What is the solution to this? I'm running against the same problem decribed in the first post in this thread.

**Comment by villebro** [comment]
@dennari Would you be able to open a new ticket so we can investigate further? If you are on a recent version this should already work, as we're no longer comparing to strings but native `TIMESTAMP`s: 

https://github.com/apache/incubator-superset/blob/0.35/superset/db_engine_specs/presto.py#L527-L528
