### ISSUE TITLE
Time Granularity formatting bug in Time Series chart

### ISSUE THREAD

**Issue by auroralinan** [airbnb/superset#1299]
Hi there, when I use 'Time Series - Line Chart' or any type of Time Series chart, I find that 'Time Granularity' doesn't work well. Here is the SQL generated by caravel.

```
> SELECT `mobileNumberIsActive` AS `mobileNumberIsActive`,
>        DATE("inputDate") AS timestamp,
>        COUNT(*) AS count
> FROM `Party`
> INNER JOIN
>   (SELECT `mobileNumberIsActive` AS `mobileNumberIsActive__`,
>           COUNT(*) AS count
>    FROM `Party`
>    WHERE `inputDate` >= DATE_FORMAT(`InputDate`,'%%Y-%%m-%%d')
>      AND `inputDate` <= DATE_FORMAT(`InputDate`,'%%Y-%%m-%%d')
>    GROUP BY `mobileNumberIsActive`
>    ORDER BY count DESC LIMIT 50) AS anon_1 ON `mobileNumberIsActive` = `mobileNumberIsActive__`
> WHERE `inputDate` >= DATE_FORMAT(`InputDate`,'%%Y-%%m-%%d')
>   AND `inputDate` <= DATE_FORMAT(`InputDate`,'%%Y-%%m-%%d')
> GROUP BY `mobileNumberIsActive`,
>          DATE("inputDate")
> ORDER BY count DESC LIMIT 1000000
```

When I select 'day' or 'week', caravel will add a datetime format function.
Note that inputDate is quoted by "", which means it put a string into DATE function.

> DATE("inputDate") AS timestamp,

So there will be no date column in return data.
How can I fix this? Now I can just add a new column like year, day or something. And select this as time column. 

In addition, when I select Group By column, if this column contains Chinese character, it returns this error.

> {"error": "'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)"}

I guess this is a python encode problem, should I use Python3?

**Comment by xrmx** [comment]
Python3 is recommended, could you please post the stacktrace?

**Comment by auroralinan** [comment]
2016-10-08 17:22:50,814:ERROR:root:'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/httx/run/anaconda2/lib/python2.7/site-packages/caravel-0.11.0-py2.7.egg/caravel/views.py", line 1185, in explore
    viz_obj.get_json(),
  File "/httx/run/anaconda2/lib/python2.7/site-packages/caravel-0.11.0-py2.7.egg/caravel/viz.py", line 320, in get_json
    'data': self.get_data(),
  File "/httx/run/anaconda2/lib/python2.7/site-packages/caravel-0.11.0-py2.7.egg/caravel/viz.py", line 1129, in get_data
    chart_data = self.to_series(df)
  File "/httx/run/anaconda2/lib/python2.7/site-packages/caravel-0.11.0-py2.7.egg/caravel/viz.py", line 1108, in to_series
    name = ["{}".format(s) for s in name]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)

**Comment by xrmx** [comment]
The unicode issue should be fixed by https://github.com/airbnb/caravel/pull/1301

**Comment by auroralinan** [comment]
Seems still not fixed

> 2016-10-10 09:28:06,498:ERROR:root:'ascii' codec can't decode byte 0xe4 in position 1: ordinal not in range(128)
> Traceback (most recent call last):
>   File "/httx/run/anaconda2/lib/python2.7/site-packages/caravel-0.11.0-py2.7.egg/caravel/views.py", line 1183, in explore
>     viz_obj.get_json(),
>   File "/httx/run/anaconda2/lib/python2.7/site-packages/caravel-0.11.0-py2.7.egg/caravel/viz.py", line 318, in get_json
>     'data': self.get_data(),
>   File "/httx/run/anaconda2/lib/python2.7/site-packages/caravel-0.11.0-py2.7.egg/caravel/viz.py", line 1127, in get_data
>     chart_data = self.to_series(df)
>   File "/httx/run/anaconda2/lib/python2.7/site-packages/caravel-0.11.0-py2.7.egg/caravel/viz.py", line 1106, in to_series
>     name = [text_type(s) for s in name]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 1

: ordinal not in range(128)

**Comment by xrmx** [comment]
@auroralinan what does it happen if you comment the line  `name = [text_type(s) for s in name]` ?

**Comment by auroralinan** [comment]
@xrmx Same error at next if condition

```
if len(self.form_data.get('metrics')) > 1:
                    series_title = ", ".join(name)
                else:
                    series_title = ", ".join(name[1:])  #this line cause error
```

Now I can fix it by force set default encoding by 
```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

But I don't think it's a good solution.
Hope for your opinion.

**Comment by auroralinan** [comment]
@xrmx  FYI
`
[<type 'unicode'>, <type 'str'>]`

**Comment by mistercrunch** [comment]
What's the database backend here? Looks to me like `DATE("inputDate")` should be using backticks, not quotes.

**Comment by auroralinan** [comment]
Yes, It supposed to be DATE(`inputDate`) not "inputDate", I'm using MySQL.
When I use TIME SERIES chart and use Time Granularity to format my date, like use week, then the query of timestamp part will be 

> DATE(DATE_SUB("inputDate", INTERVAL DAYOFWEEK("inputDate") - 1 DAY)) AS timestamp,

It will use "" but not `` and thus return nothing.

sorry for not looking at this question.

@mistercrunch

**Comment by hongqp** [comment]
@auroralinan , @mistercrunch 
I have the same problem(msyql 5.5) and find a way to solve it，maybe you can try this:
udf.function.format(col=dttm_expr), type_=DateTime).label('timestamp')  ==>
udf.function.format(col=dttm_col), type_=DateTime).label('timestamp'):


models.py
`

            # Transforming time grain into an expression based on configuration
            time_grain_sqla = extras.get('time_grain_sqla')
            if time_grain_sqla:
                db_engine_spec = self.database.db_engine_spec
                if dttm_col.python_date_format == 'epoch_s':
                    dttm_expr = \
                        db_engine_spec.epoch_to_dttm().format(col=dttm_expr)
                elif dttm_col.python_date_format == 'epoch_ms':
                    dttm_expr = \
                        db_engine_spec.epoch_ms_to_dttm().format(col=dttm_expr)
                udf = self.database.grains_dict().get(time_grain_sqla, '{col}')
                timestamp_grain = literal_column(
                    # here
                    udf.function.format(col=dttm_col), type_=DateTime).label('timestamp')
            else:
                timestamp_grain = timestamp`

**Comment by auroralinan** [comment]
@hongqp  It works, thanks~

**Comment by mistercrunch** [comment]
The piece of code you referenced above is pretty dense. I should refactor it a bit as I fix this.
@xrmx as a sidenote we fully support python 2.7 and run our production on it.
