### ISSUE TITLE
Table viz, sorting by column "version" is broken in Chrome

### ISSUE THREAD

**Issue by 0x0ece** [airbnb/superset#1307]
I'm reporting a bug which is really about DataTables more than Caravel, but it may affect Caravel users.

We have table visualizations with a version field (e.g. our app version), and sorting by that column breaks in Chrome.

The issue is that DataTables attempts to auto detect dates, which is not working properly on Chrome. Here's the issue:
https://github.com/DataTables/DataTables/issues/874

Let's monitor for a new version of DataTables that hopefully will fix this. I'll keep an eye on it.

**Comment by ecesena** [comment]
Temporary fix is to edit `caravel/assets/node_modules/datatables.net/js/jquery.dataTables.js` and comment out lines 14769-14771:
```
		//"date-pre": function ( d ) {
		//	return Date.parse( d ) || 0;
		//},
```
Then re-run `npm run prod` (or `npm run dev`).

**Comment by mistercrunch** [comment]
Oh interesting. Thanks for documenting / sharing. You can keep track of our npm dependencies and wether they are updated here:
https://david-dm.org/airbnb/caravel?path=caravel/assets

**Comment by 0x0ece** [comment]
It's been fixed, closing.
