### ISSUE TITLE
Use database_name in share query link

### ISSUE THREAD

**Issue by vera-liu** [airbnb/superset#1328]

**Comment by mistercrunch** [comment]
Careful here, there's no guarantee that a database name is unique. It'd be great to have a meaningful/readable yet unique ID for databases.

**Comment by bkyryliuk** [comment]
@mistercrunch - can't we just enforce the DB name to be unique?
Do you have any user flow where it would make sense to have multiple DBs with the same name ?

**Comment by xrmx** [comment]
@bkyryliuk multiple database with the same name on different datasources does not look that unusual

**Comment by mistercrunch** [comment]
I vote for adding a new field `database_id` that would be unique, non-null and based off of the database_name. No spaces or special character.

That would require a migration script that kickstarts the field and suffix number are added where there is uniqueness conflict on the "slugified" database name.

A `utils.slugify(name, model_column)` method could be generalized and reused wherever we need this.

**Comment by bkyryliuk** [comment]
@vera-liu  - could u tackle it this week ?

**Comment by vera-liu** [comment]
Since we use shortened link now, this issue is out of scope, closing for now.
