### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by gschrader** [airbnb/superset#1339]
The urls that are created to fetch the json data seem to be formed wrong for IE in both the Dashboard and Slice views.

For example:
![image](https://cloud.githubusercontent.com/assets/868298/19318076/6bd6980c-9064-11e6-8113-30aa7cfe80cc.png)

The [IE url](http://qhefriooer.localtunnel.me/caravel/explore_json/table/3/?viz_type=big_number_total&granularity_sqla=ds&time_grain_sqla=Time+Column&since=100+years+ago&until=now&metric=sum__num&subheader=total+female+participants&y_axis_format=.3s&where=&having=&flt_col_0=&flt_op_0=in&flt_eq_0=&flt_col_1=gender&flt_op_1=in&flt_eq_1=girl&slice_id=24&slice_name=Number+of+Girls&collapsed_fieldsets=&action=&userid=1&goto_dash=false&datasource_name=birth_names&datasource_id=3&datasource_type=table&previous_viz_type=big_number_total&rdo_save=overwrite&new_slice_name=&add_to_dash=false&save_to_dashboard_id=&new_dashboard_name=&json=true&force=false) vs [Chrome url](http://qhefriooer.localtunnel.me/caravel/explore/table/3/caravel/explore_json/table/3/?viz_type=big_number_total&granularity_sqla=ds&time_grain_sqla=Time+Column&since=100+years+ago&until=now&metric=sum__num&subheader=total+female+participants&y_axis_format=.3s&where=&having=&flt_col_0=&flt_op_0=in&flt_eq_0=&flt_col_1=gender&flt_op_1=in&flt_eq_1=girl&slice_id=24&slice_name=Number+of+Girls&collapsed_fieldsets=&action=&userid=1&goto_dash=false&datasource_name=birth_names&datasource_id=3&datasource_type=table&previous_viz_type=big_number_total&rdo_save=overwrite&new_slice_name=&add_to_dash=false&save_to_dashboard_id=&new_dashboard_name=&json=true&force=false) . Looks like it's missing `caravel/explore/table/3` as a prefix.

This was discussed in #1323.

**Comment by gschrader** [comment]
I haven't tried earlier versions of IE, I shudder to think anyone still needing to support them. The new Edge browser in Windows 10 works great already.

**Comment by mistercrunch** [comment]
Does IE have weird issues with common URLs?

**Comment by gschrader** [comment]
@mistercrunch what do you mean by common URLs? I can navigate through all the pages within caravel just fine, it's just the visualizations that aren't fetching correctly.

**Comment by woel0007** [comment]
Did anyone else make any progress with this issue?  From what I can tell, it's still happening...

Steps to re-create:
1) I pulled the latest version of Superset from GH this AM.  Commit: 2133056c04d20807ea0c503d0fed235ee20e94bb
2) Install/build node dependencies.
3) Started superset.  

When tested via Chrome, everything seems to work just fine.  However, when tested from IE11 (from the same machine used to test via Chrome) I see the same error from the screenshot above.  

Note: Superset itself is not installed on Windows - I use my Windows machine only to test with different browsers.  Superset is installed/running from OSX.  

I did a little bit of troubleshooting - there's definitely a difference in the URLs being requested between Chrome and IE.  

IE:
```
/superset/explore/druid/86/superset/explore_json/druid/86/?viz_type=table&granularity=one+day&druid_time_origin=&since=7+days+ago&until=now&table_timestamp_format=smart_date&row_limit=50000&include_search=false&flt_col_0=&flt_op_0=in&flt_eq_0=&having_col_0=&having_op_0=%3D%3D&having_eq_0=&slice_id=&slice_name=&collapsed_fieldsets=&action=&userid=2&goto_dash=false&datasource_name=Test.DBQL_Analysis_V3&datasource_id=86&datasource_type=druid&previous_viz_type=table&rdo_save=saveas&new_slice_name=&add_to_dash=false&save_to_dashboard_id=&new_dashboard_name=&json=true&force=false
```
Chrome:
```
/superset/explore_json/druid/86/?viz_type=table&granularity=one+day&druid_time_origin=&since=7+days+ago&until=now&table_timestamp_format=smart_date&row_limit=50000&include_search=false&flt_col_0=&flt_op_0=in&flt_eq_0=&having_col_0=&having_op_0=%3D%3D&having_eq_0=&slice_id=&slice_name=&collapsed_fieldsets=&action=&userid=2&goto_dash=false&datasource_name=Test.DBQL_Analysis_V3&datasource_id=86&datasource_type=druid&previous_viz_type=table&rdo_save=saveas&new_slice_name=&add_to_dash=false&save_to_dashboard_id=&new_dashboard_name=&json=true&force=false```

If it isn't obvious from the above extremely-long URL, the only difference in the above URLs is that, in IE, the URL begins with ```/superset/explore/druid/86/```; otherwise the 2 URLs are identical.  

Any idea what could be causing this issue?  Is there any other logs I can provide that might help to reproduce and/or diagnose?

**Comment by woel0007** [comment]
Does anyone have any thoughts on this one?  Why would IE write a different URL than Chrome/Safari?

**Comment by gschrader** [comment]
@woel0007 it doesn't make much sense to me why IE would behave differently, I haven't had a chance to look closer at the code yet though.

I do find it odd that @mistercrunch added the can't reproduce label, I think it is easily reproducible

**Comment by mistercrunch** [comment]
It's only easy to reproduce if you have access to a windows computer

**Comment by gschrader** [comment]
Yes true, having windows would be necessary. I've used https://github.com/xdissent/ievms in the past with success.

**Comment by niconoe** [comment]
Yep, I also have the issue with v0.14.0

**Comment by francisliyy** [comment]
is there any breakthrogh for this issue?

**Comment by wbsljh** [comment]
superset.js

jsonEndpoint() {
        const parser = document.createElement('a');
        parser.href = data.json_endpoint;
        let endpoint = parser.pathname + this.querystring();
        endpoint += '&json=true';
        endpoint += '&force=' + this.force;
        //for ie11
        if (endpoint.substring(0, 1) != '/') {
          endpoint = '/' + endpoint;
        }
        return endpoint;
      },

**Comment by xrmx** [comment]
@wbsljh care to open a pull request please?

**Comment by rlei** [comment]
@xrmx we recently met the same issue and had fixed it in our local repo. I've created PR #1821 for it. Please have a review at it, thanks.

**Comment by xrmx** [comment]
@rlei thanks!

**Comment by xrmx** [comment]
PR is merged, closing.
