### ISSUE TITLE
Cannot resolve module 'react-map-gl'

### ISSUE THREAD

**Issue by kusumakarb** [airbnb/superset#1358]
I'm trying to build from the sources and when I do `npm run dev` I get the following error:

`ERROR in ./visualizations/mapbox.jsx
Module not found: Error: Cannot resolve module 'react-map-gl' in ~/caravel/caravel-airbnb_prod.0.11.0.1/caravel/assets/visualizations
 @ ./visualizations/mapbox.jsx 19:18-41`

I'm using Ubuntu 14.04.Here is the entire output:

`> caravel@0.11.0 dev ~/caravel/caravel-airbnb_prod.0.11.0.1/caravel/assets

> NODE_ENV=dev webpack -d --watch --colors --progress

Hash: 23c3b38433d5a55bb1a3  
Version: webpack 1.13.2
Time: 45523ms
                                 Asset     Size  Chunks             Chunk Names
             explorev2.0.11.0.entry.js  4.33 MB       4  [emitted]  explorev2
  f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]  
 fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]  
  e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]  
  89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]  
  7b9776076d5fceef4993b55c9383dedd.gif  1.85 kB          [emitted]  
  2b912f7c0653008ca28ebacda49025e7.gif  1.74 kB          [emitted]  
                common.0.11.0.entry.js   622 kB       0  [emitted]  common
             css-theme.0.11.0.entry.js   185 kB       1  [emitted]  css-theme
             dashboard.0.11.0.entry.js  6.72 MB       2  [emitted]  dashboard
               explore.0.11.0.entry.js  5.85 MB       3  [emitted]  explore
448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]  
                sqllab.0.11.0.entry.js  5.16 MB       5  [emitted]  sqllab
            standalone.0.11.0.entry.js  4.45 MB       6  [emitted]  standalone
               welcome.0.11.0.entry.js  1.51 MB       7  [emitted]  welcome
            common.0.11.0.entry.js.map   749 kB       0  [emitted]  common
         css-theme.0.11.0.entry.js.map   237 kB       1  [emitted]  css-theme
         dashboard.0.11.0.entry.js.map     8 MB       2  [emitted]  dashboard
           explore.0.11.0.entry.js.map  6.95 MB       3  [emitted]  explore
         explorev2.0.11.0.entry.js.map  4.87 MB       4  [emitted]  explorev2
            sqllab.0.11.0.entry.js.map  5.86 MB       5  [emitted]  sqllab
        standalone.0.11.0.entry.js.map  5.33 MB       6  [emitted]  standalone
           welcome.0.11.0.entry.js.map  1.79 MB       7  [emitted]  welcome
   [0] multi explorev2 40 bytes {4} [built]
   [0] multi sqllab 40 bytes {5} [built]
   [0] multi standalone 40 bytes {6} [built]
   [0] multi welcome 40 bytes {7} [built]
   [0] multi explore 40 bytes {3} [built]
   [0] multi dashboard 40 bytes {2} [built]
    + 2173 hidden modules

ERROR in ./visualizations/mapbox.jsx
Module not found: Error: Cannot resolve module 'react-map-gl' in ~/caravel/caravel-airbnb_prod.0.11.0.1/caravel/assets/visualizations
 @ ./visualizations/mapbox.jsx 19:18-41`

I tried using `'react-map-gl': path.resolve('../node_modules/react-map-gl/')` in the webpack config file but no luck.

**Comment by kusumakarb** [comment]
Changing `import MapGL from 'react-map-gl` to `import MapGL from 'react-map-gl/dist/map-gl.js` in caravel/assets/visualizations/mapbox.jsx worked for me.

**Comment by mistercrunch** [comment]
What are your npm and node versions?

**Comment by kusumakarb** [comment]
```
npm -v: 3.10.8
node -v: v6.8.1
```

**Comment by s3ni0r** [comment]
same here.
npm -v: 1.3.24
node -v: 0.10.25
uname -a : Linux gear 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xrmx** [comment]
@s3ni0r you have to update your node and npm version https://github.com/airbnb/caravel/commit/9db4cc8c6d0422f28357dc4283089ee3dde9a08e

**Comment by x4base** [comment]
npm -v: 3.10.9
node -v: v6.9.2

**Comment by x4base** [comment]
I switched to node 6.2.2 and npm 3.9.5 using nvm, deleted node_modules, then `npm install`, `npm run dev`, but still doesn't work. Only after I did `npm cache clean` then repeated the steps above, it's finally working.

**Comment by xrmx** [comment]
Thanks @x4base for reporting. Closing as it looks like the usual js tooling hiccup.
