### ISSUE TITLE
VizType filter_box does not show the "verbose name" of a column but rather the column name.

### ISSUE THREAD

**Issue by cons0l3** [airbnb/superset#1363]
When setting up a new slice of visualisation type "filter_box" on a table T1 with a column name "dim_A" and a verbose name "Dimension A", the filter box is shown with the column name "dim_A" on the dashboard.

I would rather want the "verbose name" to show on the dashboard and only show the column name if there is no versbose name.

My understanding is to use the verbose name for non technical users and column name for technical users (in queries, ...)

**Comment by raelmiu** [comment]
+1
I understood from this https://github.com/airbnb/superset/issues/520 that the verbose name should be used. But I can't figure out how to show it.
