### ISSUE TITLE
count_distinct function doesn't exist in mysql

### ISSUE THREAD

**Issue by maver1ck** [airbnb/superset#1373]
Hi,
I have following problem. When I'm using SQL Lab and COUNT(DISTINCT) metric Caravel is trying to calculate this metric using `count_distinct` function.
Unfortunately there is no such a function in MySQL. and I'm getting exception.

```
"error": "(_mysql_exceptions.OperationalError) (1305, 'FUNCTION test.count_distinct does not exist')
```

**Comment by xrmx** [comment]
Any chance this has been fixed in newer releases?

**Comment by carlessebastian** [comment]
Same problem here. Not working with postgres.

**Comment by xrmx** [comment]
@carlessebastian i don't think there are many chances that you are getting a mysql operational error on postgres.

**Comment by xrmx** [comment]
While at it closing since it has been ~a month without feedback from original poster.
