### ISSUE TITLE
[sql lab] use a lighter table component in ResultSet

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/superset#1378]
The current table component seem to be really heavy on the browser. If you bring in a few 1000 rows result set, the application starts to struggle quite a bit.

The perfect table component would have:
- shouldn't have issue rendering tens of thousands of rows
- a client side search capability
- auto-width of column, plus the ability to resize
- we need to be able to put JSX in cells
- stylable, we need to be able to make it look bootstrapy
- (optional) pagination
- (optional) per-column search/filter?
- (optional) its own export to CSV
- ...?

**Comment by nickbarnwell** [comment]
I can take a stab at benchmarking a couple of different options if you don't already have a library in mind

**Comment by mistercrunch** [comment]
Awesome! One elusive feature is for the column width to be set automagically based on the data. Basic html table to this, and it may be part of the reason why they are slow.

I guess we could try to estimate the needed width based on a sample of the data, but it seems like the component should just do this.
