### ISSUE TITLE
build Caravel from sources

### ISSUE THREAD

**Issue by ujhujuh** [airbnb/superset#1534]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the caravel logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of caravel
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Caravel version
0.12.0

### Expected results
want to show the dashboards or slices, but nothing

### Actual results
nothing

### Steps to reproduce
cd $CARAVEL_HOME/caravel/assets
npm install
npm run prod
cd $CARAVEL_HOME
python setup.py install

**Comment by hustxiaofeng** [comment]
the same problem as yours

**Comment by xrmx** [comment]
I'm sorry but i don't see any issue here, read the tutorial if your problem is how to load demo data http://airbnb.io/caravel/installation.html#caravel-installation-and-initialization

**Comment by ujhujuh** [comment]
@xrmx 
       when i install the caravel, everything is ok. but now i want to  build it by source code, i follow those steps:
- npm install
- npm run prod
- python setup.py install

     no errors has been found in those steps, then i run it, but the dashboards and slices has nothing to show. there was a problem in chrome's console: 

**web_worker.js?e7d2:5Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.(…)**

**Comment by xrmx** [comment]
@ujhujuh  And how i was supposed to know that if you don't mention the actual error in your bug report?

**Comment by hustxiaofeng** [comment]
@ujhujuh , i encounter the same problem as you

**Comment by hustxiaofeng** [comment]
@ujhujuh , i encounter the same problem as you, after install and run server, the page is blank, and the chrome console throws a error:
![image](https://cloud.githubusercontent.com/assets/7539662/19961482/d991e078-a1ed-11e6-87cb-85edaf491998.png)

**Comment by toabey** [comment]
alias: { webworkify: 'webworkify-webpack',
  'mapbox-gl/js/geo/transform':APP_DIR + '/node_modules/mapbox-gl/js/geo/transform',
  'mapbox-gl':'mapbox-gl/dist/mapbox-gl.js')

edit inside webpack may solve the problem
https://github.com/uber/react-map-gl/issues/112

**Comment by ujhujuh** [comment]
@toabey ,slice worked well, but dashboard like this:
![a](https://cloud.githubusercontent.com/assets/19641641/19992838/14a40ebe-a27c-11e6-9210-c1f004cbf991.png)

and now the sqllab doesn't work:
![b](https://cloud.githubusercontent.com/assets/19641641/19992892/8d908712-a27c-11e6-9e51-be71f5fd553b.png)

**Comment by hustxiaofeng** [comment]
@toabey ,the dashboard is still blank ,and browser console show the error:
===========================================================
dataTables.bootstrap.js?fffa:47Uncaught TypeError: Cannot read property 'defaults' of undefined(anonymous function) @ dataTables.bootstrap.js?fffa:47(anonymous function) @ dataTables.bootstrap.js?fffa:17DataTable @ dataTables.bootstrap.js?fffa:18(anonymous function) @ dataTables.bootstrap.js?fffa:41(anonymous function) @ dashboard.0.12.0.entry.js:7648__webpack_require__ @ dashboard.0.12.0.entry.js:20(anonymous function) @ pivot_table.js?7ad3:7(anonymous function) @ dashboard.0.12.0.entry.js:7639__webpack_require__ @ dashboard.0.12.0.entry.js:20(anonymous function) @ main.js?a62f:28(anonymous function) @ dashboard.0.12.0.entry.js:5023__webpack_require__ @ dashboard.0.12.0.entry.js:20(anonymous function) @ caravel.js?9e8e:7(anonymous function) @ dashboard.0.12.0.entry.js:5014__webpack_require__ @ dashboard.0.12.0.entry.js:20(anonymous function) @ Dashboard.jsx?c99a:21(anonymous function) @ dashboard.0.12.0.entry.js:2881__webpack_require__ @ dashboard.0.12.0.entry.js:20(anonymous function) @ dashboard.0.12.0.entry.js:51__webpack_require__ @ dashboard.0.12.0.entry.js:20(anonymous function) @ dashboard.0.12.0.entry.js:40(anonymous function) @ dashboard.0.12.0.entry.js:43

**Comment by hustxiaofeng** [comment]
@toabey ,thanks to your tips, solved my problem, but the dashboard is still blank ,and browser console show the error, all related about dataTable, i find that in the dist js files, for example, in dist/dashboard.xx.js, the datatable.net.bs is loaded as AMD:
![image](https://cloud.githubusercontent.com/assets/7539662/20044200/b5d1996c-a4d1-11e6-9d79-7ae57fb571a2.png)

the if statement get a true const, but in datatable.net.bs's node modules, the if statement is a express as "typeof define === 'function' && define.amd", the npm run dev replace the express as 'true' in output dist js, i attemp to modify it as false in dist js file, and then it works well, but i don't know what cause the issue. i find other js error almost the same related to datatable in webpack:
![image](https://cloud.githubusercontent.com/assets/7539662/20044263/5e64bdca-a4d2-11e6-8c84-961e3fcfd968.png)

**Comment by tryer3000** [comment]
got the same error after login.
webpack fail to load datatable
here's some clues to this problem

https://gist.github.com/swemaniac/2fbe5d6d5e425b7c046168b6d6e74e95
https://www.datatables.net/blog/2015-11-09#AMD

**Comment by mistercrunch** [comment]
@ascott fixed both issues here:
https://github.com/mistercrunch/caravel/commit/902f9544d2fbf03c69537df67cb3f7bf2aa9ab65
and 
https://github.com/mistercrunch/caravel/commit/e64e1b2e73597d940179297b60bc6a0f8a6a2bef#diff-89f4a08914347e2e8a144079a0bb2642R54

**Comment by github35** [comment]
I encountered the same error when I install Superset....

**Comment by mistercrunch** [comment]
@github35 can you try off of the current master or `pip install superset==0.13.0`?

**Comment by github35** [comment]
@mistercrunch I installed 0.13.0 and encountered another problem -- I only have css-theme.0.12.0.entry and other 0.12.0 files in dist folder. So it's not working from my side.

**Comment by github35** [comment]
0.13.1 works. Thank you!!

**Comment by hustxiaofeng** [comment]
@mistercrunch ,0.13.1 just fix the problem, it is great!

**Comment by mistercrunch** [comment]
Nice!
