### ISSUE TITLE
Ability to see results from all SQL queries from user, not just latest SQL query

### ISSUE THREAD

**Issue by jefffeng** [airbnb/superset#1548]
Ability to see results from all SQL queries from user, not just latest SQL query

**Comment by mistercrunch** [comment]
We can't keep all queries result in the application's state on the client side as it would blow up. When using the results backend (async mode) it's possible to re-fetch the results easily. When not using the results backend, users have to re-run the query.

**Comment by jefffeng** [comment]
Would it be possible to set a limit (either time-based or # of queries based) to save the results?  Say for 1 hour or for the last 5 queries?

**Comment by jefffeng** [comment]
Closing this issue in favor of https://github.com/airbnb/superset/issues/1797
