### ISSUE TITLE
can not execute fabmanager create-admin –app caravel

### ISSUE THREAD

**Issue by fangyeqing** [airbnb/superset#1557]
```
/xxx/python-3.5.2/lib/python3.5/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
Username [admin]: test
User first name [admin]: test
User last name [user]: test
Email [admin@fab.org]: test@test.org
Password: 
Repeat for confirmation: 
/xxx/python-3.5.2/lib/python3.5/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  .format(x=modname), ExtDeprecationWarning
/global/exec/fangyeqing/python-3.5.2/lib/python3.5/site-packages/flask_cache/__init__.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
/xxx/python-3.5.2/lib/python3.5/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  .format(x=modname), ExtDeprecationWarning
```

**Comment by xrmx** [comment]
These are warnings not errors. Which version of caravel is this? Doesn't look a recent version of caravel.

**Comment by fangyeqing** [comment]
the latest version 0.12.0.
It will stop after the warning log, why?

**Comment by xrmx** [comment]
It's waiting for you to retype the password, have you done that? But the flask-app-builder we are depending one should have already fixed the flask ext warning. So again, are you really sure this is 0.12?

**Comment by fangyeqing** [comment]
I have retype the password, and the version is 0.12.0.

**Comment by xrmx** [comment]
could you please paste the output of pip freeze?

**Comment by fangyeqing** [comment]
```
alembic==0.8.8
amqp==1.4.9
anyjson==0.3.3
Babel==2.3.4
billiard==3.3.0.23
caravel==0.12.0
celery==3.1.23
cffi==1.8.3
click==6.6
colorama==0.3.7
cryptography==1.4
enum34==1.1.6
Flask==0.11.1
Flask-AppBuilder==1.8.1
Flask-Babel==0.11.1
Flask-Cache==0.13.1
Flask-Login==0.2.11
Flask-Migrate==1.5.1
Flask-OpenID==1.2.5
Flask-Script==2.0.5
Flask-SQLAlchemy==2.0
Flask-Testing==0.5.0
Flask-WTF==0.13.1
future==0.16.0
gunicorn==19.6.0
humanize==0.5.1
idna==2.1
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.8
kombu==3.0.37
Mako==1.0.5
Markdown==2.6.6
MarkupSafe==0.23
numpy==1.11.2
pandas==0.18.1
parsedatetime==2.0
pyasn1==0.1.9
pycparser==2.17
pydruid==0.3.0
PyHive==0.2.1
python-dateutil==2.5.3
python-editor==1.0.1
python-openid==2.2.5
pytz==2016.7
requests==2.10.0
sasl==0.2.1
simplejson==3.8.2
six==1.10.0
SQLAlchemy==1.0.13
SQLAlchemy-Utils==0.32.7
sqlparse==0.1.19
thrift==0.9.3
thrift-sasl==0.2.1
Werkzeug==0.11.10
WTForms==2.1
```

**Comment by dodysw** [comment]
I have this issue as well. Python 3.5.2 from "conda update --all", followed by pip install superset. Got bunch of warnings, then nothing happen. Any suggestion which file/lines to look so I can put some debugging lines?

**Comment by dodysw** [comment]
Found out the issue. The application stores an sqlite db by default at ~/.superset/superset.db. My home directory is an NFS partition which sqlite doesn't play nice due to some locking mechanism. My fix is to create superset_config.py in current directory, and definte this variable to tell it to place the database in an non-NFS partition:
SQLALCHEMY_DATABASE_URI = 'sqlite:////opt/logs/sandbox/airbnb/superset.db'

Another option is possibly to create a symlink in ~/.superset to a different directory on non-NFS partition.

**Comment by fangyeqing** [comment]
@dodysw , I create a symlink in ~/.superset, and it worked, thanks!

**Comment by xrmx** [comment]
Would be nice to have an entry in the faq for this issue. @dodysw care to do a pull request?

**Comment by dodysw** [comment]
#1637 created

**Comment by xrmx** [comment]
@dodysw thanks! closing this one then
