### ISSUE TITLE
no module named superset when upgrade db

### ISSUE THREAD

**Issue by github35** [airbnb/superset#1577]
I installed superset and got this error message when I tried to run superset db upgrade. BTW, is Caravel changing name again?

**Comment by github35** [comment]
something wrong with system paths

**Comment by pranita-s** [comment]
I am facing exactly the same problem. After >pip install superset command, it throws following error- 

(venv) > superset db upgrade
'superset' is not recognized as an internal or external command,operable program or batch file.

OS: Windows
Python version: 3.5
How to resolve it ?

**Comment by github35** [comment]
@pranita-s cd bin and use python superset db upgrade

**Comment by guduxingzou** [comment]
@github35  I used that  then    
ImportError: No module named 'grp'?
how to handle this problem? ths!

**Comment by mistercrunch** [comment]
If someone is serious about a windows release, they should add windows to the travis-ci build matrix. The core developers don't have access to Windows machines.

**Comment by Josemboa** [comment]
cd C:\venv\Scripts\ && python superset db upgrade worked for me. Thank you @github35!

**Comment by DanGolding** [comment]
I used a conda virtual env so I had to go to `C:\ProgramData\Anaconda3\envs\my-env-name\Scripts\` and then `python superset db upgrade` worked for me

**Comment by sedhha** [comment]
> @pranita-s cd bin and use python superset db upgrade

where is bin folder located?
