### ISSUE TITLE
[sql-lab] make error messages look more like console log messages.

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#1580]

**Comment by mistercrunch** [comment]
About this, note that the format of the Exception returned by the database API is heterogenous. It should be handled in `db_engine_spec.py`

**Comment by ascott** [comment]
@mistercrunch i was meaning the ui rather than the actual content of the exception.

**Comment by mistercrunch** [comment]
oh yeah that'd be nice, I was thinking you were referring to the large Presto error blobs
