### ISSUE TITLE
Filtering on integer values is broken.

### ISSUE THREAD

**Issue by bkyryliuk** [airbnb/superset#1640]
Error message:
`argument of type 'int' is not iterable`

<img width="389" alt="screen shot 2016-11-22 at 3 05 59 pm" src="https://cloud.githubusercontent.com/assets/5727938/20545660/374854dc-b0c5-11e6-9633-76861c8364f0.png">

Leads to the query generated:
```
FROM "blabla"."blabla" 
WHERE "ds" >= '2016-11-15 15:02:52' AND "ds" <= '2016-11-22 15:02:52' AND "dim_bla" IN ('33')
```
Where 33 is a string but should be int

**Comment by prashantGit** [comment]
when is this getting fixed?

**Comment by zallek** [comment]
same problem if you click on filterable table grouped on integers.
![image](https://cloud.githubusercontent.com/assets/1886834/22116486/ea9b85bc-de70-11e6-9c4e-7fe4ac10de2b.png)

problem at https://github.com/airbnb/superset/blob/master/superset/viz.py#L264
