### ISSUE TITLE
Redirect Caravel URLs to Superset

### ISSUE THREAD

**Issue by kingo55** [airbnb/superset#1650]
Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if any
- [*] I have reproduced the issue with at least the latest released version of superset
- [*] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.13.2

### Expected results
When visiting an old URL like https://{{domain}}/caravel/sqllab - you would expect to be redirected to: https://{{domain}}/superset/sqllab

This means people need to update their bookmarks or popular links.

### Actual results
Land on a 404 page

### Steps to reproduce
Visit a standard view, replacing "superset" with "caravel".

**Comment by xrmx** [comment]
Next time you don't need to open a bug if you are going to open a PR right after :)

**Comment by kingo55** [comment]
Gotcha! Thanks for merging.
