### ISSUE TITLE
Import CSV easily

### ISSUE THREAD

**Issue by WGierke** [airbnb/superset#1652]
### Expected results
Import CSV via file selection

### Actual results
Convert CSV manually to e.g. Postgres database and provide it's path

Aren't there any easy ways to import CSV files so far?

**Comment by mistercrunch** [comment]
duplicate with https://github.com/airbnb/superset/issues/381

**Comment by hillaryhitch** [comment]
use this:
import pandas as pd
pdsites = pd.read_csv("site_data.csv")
pdsites.columns


def df2sqlite(dataframe, db_name = "import.sqlite", tbl_name = "import"):

    import sqlite3
    conn=sqlite3.connect(db_name)
    cur = conn.cursor()

    wildcards = ','.join(['?'] * len(dataframe.columns))
    data = [tuple(x) for x in dataframe.values]

    cur.execute("drop table if exists %s" % tbl_name)

    col_str = '"' + '","'.join(dataframe.columns) + '"'
    cur.execute("create table %s (%s)" % (tbl_name, col_str))

    cur.executemany("insert into %s values(%s)" % (tbl_name, wildcards), data)

    conn.commit()
    conn.close()

df2sqlite(pdsites, db_name="sites_4g.db", tbl_name = "sites_data_4g")


import sqlite3
import pandas as pd
# Create your connection.
cnx = sqlite3.connect('sites_4g.db')

df = pd.read_sql_query("SELECT * FROM sites_data_4g", cnx)
df.head(5)

####Then go to superset data sources-databases and input 'sqlite///sites_4g.db'
