### ISSUE TITLE
[SQL Lab] Run sql in the SQL Lab with Jinja

### ISSUE THREAD

**Issue by ganshanshan** [airbnb/superset#1674]
Make sure these boxes are checked before submitting your issue - thank you!

- [Yes ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Yes] I have reproduced the issue with at least the latest released version of superset
- [ Yes] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.12.0

### Expected results
I want to run the SQL in the SQL lab with **Jinja**:

```
SELECT *
FROM some_table
WHERE partition_key = '{{ presto.latest_partition('some_table') }}'
```

### Actual results
It has been failed.
`Template rendering failed: 'presto' is undefined`

**Comment by mistercrunch** [comment]
`presto` is only in the context if you are using a Presto database engine, does the connection string for the active db start with `presto://` ?
