### ISSUE TITLE
How do I configure superset to use Redis as caches backend?

### ISSUE THREAD

**Issue by girish1605** [airbnb/superset#1682]
I installed [superset](http://airbnb.io/superset/installation.html) & [redis](http://redis.io/topics/quickstart) as per standard documentation. But not able to configure superset to redis (i.e., Every time I run query it coming from database, it don't take result from cache)

**What are the exact steps to configure superset to redis ?**

**Comment by xrmx** [comment]
Cache is handled by flask cache, its documentation is here https://pythonhosted.org/Flask-Cache/#configuring-flask-cache . Superset documentation on caching with hints on dependencies is here http://airbnb.io/superset/installation.html#caching

**Comment by ioshger0125** [comment]
1.install redis
2.install redis-py which connect python to redis
3.change the cache-config in config.py
eg: Cache_Configure=｛'Cache_Type'= 'redis',
                                           'Cach.....host'= '127.0.0.1',
                                            ..............port'
｝
