### ISSUE TITLE
python 2 support

### ISSUE THREAD

**Issue by xrmx** [airbnb/superset#1686]
I'm wondering if it's time to stop supporting superset on python 2. I created by mistake a virtualenv with python2 instead of python3 and sqllab does not work at all when non ascii encodable data is used. It breaks in the loggers, it breaks when poking with dataframes. 
So given that airbnb is on python3 and tests does not catch any encoding issue is it time to stop supporting it?

**Comment by mistercrunch** [comment]
Python 2.7 is there to stay. In many environments people might now have the luxury to choose. 

We use it in production at Airbnb. We  could run 3.4 or 3.5 if we wanted but we'll probably make the switch when our standard images use distros that ship py3 by default.

So even though it reduce the surface for bugs, we're not dropping py2.7 support, I don't think there's a lot of projects that are doing that at the moment.

I'm not sure what your exact issues were, but most likely something that's easy to fix across the board with some environment (or perhaps database connection) setting.

**Comment by xrmx** [comment]
An easy reproducer for sqllab breaking with python2.7 is something like over a table from the examples:
```
select 'ኴ' from anexampletable;
```

Closing then.

**Comment by rumbin** [comment]
Another fact that should be kept in mind:

python-ldap is not available for python3.
LDAP-auth is the sole reason why we run superset in a python2.7 venv.

**Comment by xrmx** [comment]
@rumbin except you can upgrade :) https://github.com/pyldap/pyldap.

**Comment by rumbin** [comment]
@xrmx thanks for pointing me to pyldap, it seems to work well!
