### ISSUE TITLE
Unable to add Postgres table

### ISSUE THREAD

**Issue by niconoe** [airbnb/superset#1691]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

master

### Expected results

Database added successfully

### Actual results

The addition fails with "module has no attribute merge_perm"

### Steps to reproduce

getting to Sources -> Databases -> Add and filling the parameters (sqlalchemy/postgres)

The issue has been tracked down to bce02e3 and I'll submit a PM immediately.

**Comment by xrmx** [comment]
If you submit a PR shortly no need to open an issue too, thanks.

**Comment by niconoe** [comment]
Okay, thanks for the info. I won't next time :)

**Comment by mistercrunch** [comment]
https://github.com/airbnb/superset/pull/1692
