### ISSUE TITLE
Update documentation on http://airbnb.io/projects/superset/

### ISSUE THREAD

**Issue by jefffeng** [airbnb/superset#1695]
We should include a bullet on SQL Lab on the main page of Superset.  Suggested edit below:

https://docs.google.com/a/airbedandbreakfast.com/document/d/13w0eh3x1oPagJzsl33Je0FSB6H2ck8TmlS8n2v9Z9bs/edit?usp=sharing

**Comment by ascott** [comment]
https://github.com/airbnb/airbnb.github.io/pull/97
