### ISSUE TITLE
Access denied for the new users logging in

### ISSUE THREAD

**Issue by bkyryliuk** [airbnb/superset#1700]
New users when they log in they see `Access Denied` instead of the dashboard
<img width="1426" alt="screen shot 2016-11-28 at 2 17 34 pm" src="https://cloud.githubusercontent.com/assets/5727938/20688405/7e750e7c-b575-11e6-9d58-ea1c219ce030.png">

**Comment by timfeirg** [comment]
dup https://github.com/airbnb/superset/issues/1807

**Comment by xrmx** [comment]
@timfeirg thanks! closing
