### ISSUE TITLE
prompt user to login if not logged in on `/superset/welcome`

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#1703]
currently `/dashboardmodelviewasync/api/read` throws a 401 access denied and doesn't update the ui, spinner keeps spinning.

<img width="1280" alt="screenshot 2016-11-28 22 49 50" src="https://cloud.githubusercontent.com/assets/130878/20699606/065c0ccc-b5bd-11e6-8e82-0f7bbe7b12a0.png">

**Comment by francisliyy** [comment]
yes, i've got the same problem, when visit the site "http://IP:PORT", it redirect me to the "http://IP:PORT/superset/welcome",then the same picture as the above.

**Comment by vera-liu** [comment]
https://github.com/airbnb/superset/pull/1723
