### ISSUE TITLE
Cache with redis cluster

### ISSUE THREAD

**Issue by ioshger0125** [airbnb/superset#1717]
Make sure these boxes are checked before submitting your issue - thank you!

- [ Y] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y] I have reproduced the issue with at least the latest released version of superset
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset(caravel) 0.12

### Expected results
Did you considered the case when we use the redis-cluster from caching strategy?
Please tell us  how we can cached with redis cluster if possible.

### Actual results
I have tried several times from caching with redis-cluster.
When I use a node of redis-cluter to cache, I can get the data writed in the assigned host, I cannot get the data which moved to the other nodes
### Steps to reproduce
1、I configued the config.py of Caravel cached uses flask_cache 
2、I installed redis-py-cluster
3、Cache_Config = {'Cache_Type': 'redis',
                                 Cache_redis_host: '127.0.0.1',
                                 Cache_redis_port: '6379'
}
4、Data was dumped on the random hashsolts
5、I can only get data from the assigned host

**Comment by xrmx** [comment]
Caching is handled by flask-cache, not by superset.

**Comment by xrmx** [comment]
Also dup if #1716
