### ISSUE TITLE
Runserver hardcoded to use 2 Gunicorn workers instead of default 4

### ISSUE THREAD

**Issue by kingo55** [airbnb/superset#1758]
Make sure these boxes are checked before submitting your issue - thank you!

- [ * ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ * ] I have reproduced the issue with at least the latest released version of superset
- [ * ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.14.1

### Expected results

At least 4 workers should start as per the defaults in config.py and the Superset CLI python:

```python
def run_server():
    parser = argparse.ArgumentParser(description='Run gunicorn for superset')
    subparsers = parser.add_subparsers()
    gunicorn_parser = subparsers.add_parser('runserver')

    gunicorn_parser.add_argument(
        '-d', '--debug', action='store_true',
        help='Start the web server in debug mode')
    gunicorn_parser.add_argument(
        '-a', '--address', type=str, default='127.0.0.1',
        help='Specify the address to which to bind the web server')
    gunicorn_parser.add_argument(
        '-p', '--port', type=int, default=8088,
        help='Specify the port on which to run the web server')
    gunicorn_parser.add_argument(
        '-w', '--workers', type=int, default=4,
        help='Number of gunicorn web server workers to fire up')
    gunicorn_parser.add_argument(
        '-t', '--timeout', type=int, default=30,
        help='Specify the timeout (seconds) for the gunicorn web server')
```

### Actual results

After running "runserver", the Unix 'ps' command indicates we're passing '2' to the workers parameter on Gunicorn rather than 4.

This results in slower load times for large dashboards.

```bash
 4351 ttys001    0:03.04 /Users/robertkingston/superset/venv/bin/python3 /Users/robertkingston/superset/venv/bin/superset runserver -p 8088
 4364 ttys001    0:00.29 /Users/robertkingston/superset/venv/bin/python3 /Users/robertkingston/superset/venv/bin/gunicorn -w 2 --timeout 60 -b 0.0.0.0:8088 
 4367 ttys001    0:02.92 /Users/robertkingston/superset/venv/bin/python3 /Users/robertkingston/superset/venv/bin/gunicorn -w 2 --timeout 60 -b 0.0.0.0:8088 
 4368 ttys001    0:02.89 /Users/robertkingston/superset/venv/bin/python3 /Users/robertkingston/superset/venv/bin/gunicorn -w 2 --timeout 60 -b 0.0.0.0:8088
```

### Steps to reproduce

Run the latest version of Caravel out of the box.

**Comment by xrmx** [comment]
Yeah, regressions from 50da4f8c0708f91ff24c0abd7189a137a1415bf6 as it stopped reading default from the config

**Comment by kingo55** [comment]
@xrmx - Yep - definitely on 0.14.1 installed it via pip to my local machine.

Will try installing via master a bit later to see if I can confirm for you. Note - I'm also seeing it on an older docker image by @amancevice which I'm running on a VPS.

**Comment by kingo55** [comment]
@xrmx - sorry my mistake... I had master installed via pip and 0.14.1 installed via docker. I'm living in the future.

Regardless, we'll need to update the documentation / docker image to add the config path to the environment.
