### ISSUE TITLE
SQL Lab: Oracle Error (cx_Oracle.DatabaseError) ORA-12505: TNS:listener does not currently know of SID given in connect descriptor

### ISSUE THREAD

**Issue by qiulin** [airbnb/superset#1761]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.14.1

### Actual results

Oracle data source does not work.

### Steps to reproduce

Add oracle db as data source, then query a table.

**Comment by xrmx** [comment]
Looks like your connection string is wrong and we cannot help with that, please double check oracle and sqlalchemy oracle driver documentation.

**Comment by hehetown** [comment]
I am sure the connection Settings are correct. I need to connect to Oracle Service instead of SID. How should I configure it
