### ISSUE TITLE
[vis] big number w/trendline doesn't show last date on axis

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#1766]
- show last date on axis
- show date in tooltip when hovering over trend line

<img width="958" alt="screenshot 2016-12-05 13 41 48" src="https://cloud.githubusercontent.com/assets/130878/20903591/c0f69560-baf0-11e6-8490-1db64c33acf3.png">

**Comment by jefffeng** [comment]
Could we also show the y-axis value for a particular date in the tool tip as well?

**Comment by ascott** [comment]
added the tooltips, but still need to fix the axis.
