### ISSUE TITLE
[vis] add `Big String` vis type (similar to `Big Number`)

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#1784]

**Comment by mistercrunch** [comment]
Can this be accomplished with the `Markup` viz?

**Comment by ascott** [comment]
i'm imaging the use case for this would be to show a string based on the data, so it wouldn't be a static string. could we use jinja templating in the code block for the markup viz?

**Comment by punitusingh** [comment]
What is the requirement here? What kind of value we will represent in Big String? How will we plot Big String on the graph or chart?

Please provide more information.

**Comment by vickeynvickey** [comment]
What will be the value of x-axis & y-axis here for Big String? How & where will you plot a Big String?

**Comment by ascott** [comment]
closing this in favor of https://github.com/airbnb/superset/issues/2919
