### ISSUE TITLE
Rendering and Crashing the browser

### ISSUE THREAD

**Issue by rkkarthikeyan** [airbnb/superset#1787]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest one

### Expected results
We try to build as a Normal data report. it is crashed the chrome browser

### Steps to reproduce
if data size is more than 3 mb it is crashing. ( But response shows 20 mb on firefox but chrome getting out of memory)

**Comment by xrmx** [comment]
Am sorry but I don't see anything actionable here unless you are going to find out what consumes that memory. Also latest one is not a version number.
