### ISSUE TITLE
Unnecessary SQL joins

### ISSUE THREAD

**Issue by tylerFowler** [airbnb/superset#1804]
I've noticed that when hooked up to a PostgreSQL database, Superset will often generate queries with unnecessary joins. For example on generating a simple line chart that finds event type counts grouped by a 'process' field rolled up by week Superset is generating this query:

```sql
SELECT process AS process, DATE_TRUNC('week', event_date) AS __timestamp, COUNT(*) AS count 
FROM events JOIN (
	SELECT process AS process__, COUNT(*) AS count 
	FROM events 
	WHERE event_date >= '2016-09-09 20:40:16' AND event_date <= '2016-12-08 20:40:16' GROUP BY process ORDER BY count DESC 
	LIMIT 50
) AS anon_1 ON process = process__ 
WHERE event_date >= '2016-09-09 20:40:16' AND event_date <= '2016-12-08 20:40:16' GROUP BY process, DATE_TRUNC('week', event_date) ORDER BY count DESC 
LIMIT 5000;
```

Whereas I would normally write this query as:
```sql
select
	process as process,
	date_trunc('week', event_date) as __timestamp,
	count(*) as count
from events
where
	event_date >= '2016-09-09 20:40:16'
	and event_date <= '2016-12-08 20:40:16'
group by process, __timestamp
order by count desc
limit 5000;
```

Without the join, which causes the query plan to be significantly more efficient. The first query with the join takes over an hour to run on a current database, whereas the second handwritten one runs in 80 seconds. Perhaps there's a reason for this, and I'm no data specialist, but it would seem that the join serves no purpose whatsoever. Thoughts?

This is a big problem for us as the first query will actually just time out in Superset after 400 seconds or so, making it unusable for our current setup.

### Superset Version
v0.13.2

**Comment by xrmx** [comment]
@tylerFowler have you analized where the query come from? Is it something that can be optimized in pandas, sqlalchemy or superset?

**Comment by tylerFowler** [comment]
Frankly, I wouldn't even know where to look as I'm not familiar with pandas or sqlalchemy. I would imagine it's Superset that's generating the query based off of the graph options, but if I'm mistaken feel free to redirect me to appropriate repo.

**Comment by bkyryliuk** [comment]
@tylerFowler  - query is generated here:
https://github.com/airbnb/superset/blob/master/superset/models.py#L992
improvements and suggestions are greatly appreciated.

**Comment by mistercrunch** [comment]
This subquery is a feature. It's a byproduct of using the `Series Limit` parameter. Set that parameter to `0` to not generate that subquery.

<img width="291" alt="screen shot 2016-12-09 at 11 20 24 am" src="https://cloud.githubusercontent.com/assets/487433/21061520/90f750b6-be01-11e6-8a7b-942ced794597.png">

**Comment by tylerFowler** [comment]
@mistercrunch Ahh, I see, I didn't quite put that together. Thanks! That fixed the issue.
