### ISSUE TITLE
Connect Superset to ClickHouse DBMS

### ISSUE THREAD

**Issue by sichkarev** [airbnb/superset#1808]
Hello. 
Superset is a very good dashboard. I liked him at first sight.
In my projects are increasingly used [ClickHouse](https://clickhouse.yandex/), because it is very fast DBMS for OLAP. See performance comparison at https://clickhouse.yandex/benchmark.html#[100000000,["ClickHouse","Hive"],["0","1"]]

May be possible create connector to ClickHouse, e.g. through [JDBC] (https://github.com/yandex/clickhouse-jdbc) (do similarly to Hive)?
All the best, thank you!

**Comment by tomsej** [comment]
I think ClickHouse is great alternative for Druid. According to documentation there are 2 ways how to make Superset work with ClickHouse:
1) Native support (similar to Druid)
2) Using SQLAlchemy
Unfortunately there is no external SQLAlchemy dialect for ClickHouse (https://github.com/Infinidat/infi.clickhouse_orm/issues/8). And I think native support would be better. Unfortunately there documentation lack description how to do that.

**Comment by xrmx** [comment]
@sichkarev Of course it is possible if someone do the work :)
@tomsej If you want to tackle it feel free to ask any question you have, i don't think much code is needed to add a new data sources backend.

**Comment by tomsej** [comment]
@xrmx Thank you so much! Where should I start - Models.py?

**Comment by xrmx** [comment]
@tomsej Well it depends. If it exposes a sql interface i'd give a try with the sqlalchemy dialect. If it's not try to come up with something like DruidDatasource. I don't know if it has the same metric, cluster and column entities as Druid though.

**Comment by bkyryliuk** [comment]
It would be quite exciting to have the `clickhouse` onboard !
From my very little knowledge about `clickhouse`, I've heard it somewhat is similar to `presto`. 
In that case: https://github.com/dropbox/PyHive could be helphul as an example of the sqlalchemy integration.

**Comment by vavrusa** [comment]
We've (Cloudflare) open-sourced a basic sqlalchemy dialect for ClickHouse https://github.com/cloudflare/sqlalchemy-clickhouse

I'll start a PR for ClickHouse backend integration for Superset, it works but it's still a little bit buggy.

**Comment by RichRadics** [comment]
PR #1844 was merged, so this issue can probably be closed...

**Comment by xrmx** [comment]
Indeed, closing then.
