### ISSUE TITLE
Making my own build: npm ERR! tar.unpack for st*.tgz gl*.tgz

### ISSUE THREAD

**Issue by zhangjiajie023** [airbnb/superset#1813]
when i making my own build, and at the step `npm install` always `npm ERR! tar.unpack unzip error ...` 
`npm -v` 3.10.9
`node -v` 6.9.2
and also try `npm cache clean`, but error remain
has someone meet this before?
has it matter with superset, or just my npm?

**Comment by xrmx** [comment]
I think it's just something silly with npm, try to remove node_modules. Or give a try to yarn.
