### ISSUE TITLE
Consolidate "Run Query" and "Run Async" in SQL Lab to "Run Query"

### ISSUE THREAD

**Issue by jefffeng** [airbnb/superset#1819]
This is a feature to help simplify the UX for users.  Users should not have to choose whether to run a query in the standard mode or run a query asynchronously. 

Could we run the query in both modes and automatically fail over to running the query running asynchronously if the standard query fails?  Open to other ideas as well...

**Comment by ascott** [comment]
i was thinking that if running async is an available option, just run async, if not, run sync. we should just show 1 button that reads `run query`

**Comment by jefffeng** [comment]
Makes sense @ascott.  I spoke to @mistercrunch and I am onboard with your suggested approach

**Comment by ascott** [comment]
going to tackle this today.

**Comment by ascott** [comment]
https://github.com/airbnb/superset/pull/1858

**Comment by santhavathi** [comment]
@ascott, the one button that is showed does not run the query asynchronously though the tooltip shows "Run Query Asynchronously". I am using superset 0.17, since there are issues with 0.17.5 mentioned in https://github.com/airbnb/superset/issues/2643
