### ISSUE TITLE
Empty response from 0.15.0 server

### ISSUE THREAD

**Issue by amancevice** [airbnb/superset#1833]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
`0.15.0`

### Expected results
http://localhost:8088 loads in browser

### Actual results
Empty response

### Steps to reproduce
I am using a Docker image I maintain. When I upgraded the image to use Superset `0.15.0` the app no longer loads in a browser. Something seems strange about the processes that the runserver command is spawning.

Here is the output from `0.14.1`:
```bash
$ docker run -d --name superset-0-14-1 -p 8088:8088 amancevice/superset:0.14.1
$ docker exec superset-0-14-1 ps ax
  PID   USER     TIME   COMMAND
    1 superset   0:06 {superset} /usr/bin/python3.5 /usr/bin/superset runserver
   21 superset   0:00 ps ax
```
Navigating to [localhost:8088](http://localhost:8088) resolves to the main Superset page.

And from `0.15.0`:
```
$ docker run -d --name superset-0-15-0 -p 8089:8088 amancevice/superset:0.15.0
$ docker exec superset-0-15-0 ps ax
  PID   USER     TIME   COMMAND
    1 superset   0:00 {superset} /usr/bin/python3.5 /usr/bin/superset runserver
   13 superset   0:00 {superset} /usr/bin/python3.5 /usr/bin/superset runserver
   14 superset   0:00 {superset} /usr/bin/python3.5 /usr/bin/superset runserver
   15 superset   0:00 {superset} /usr/bin/python3.5 /usr/bin/superset runserver
   16 superset   0:00 {superset} /usr/bin/python3.5 /usr/bin/superset runserver
   17 superset   0:00 ps ax
```
Navigating to [localhost:8089](http://localhost:8089) is an empty response

In `curl` form:
```bash
$ curl http://localhost:8089/superset/welcome
curl: (52) Empty reply from server
```

**Comment by amancevice** [comment]
Note that *from within the container* it looks like the server is reachable:

```bash
$ curl http://localhost:8089/health
curl: (52) Empty reply from server

$ docker exec superset-0-15-0 curl http://localhost:8088/health
OK
```

**Comment by xrmx** [comment]
Do you see the request in superset logs?

**Comment by amancevice** [comment]
Not when the request is coming from the host machine

**Comment by xrmx** [comment]
so docker issue? :)

**Comment by amancevice** [comment]
I'm prepared to believe that, but it's just strange that it's happening now and never before. I changed nothing about the image except the caravel version:

https://github.com/amancevice/superset/compare/0.14.1...master

**Comment by xrmx** [comment]
does mapping the ports to 8088:8088 in the superset 0.15.0 container change anything?

**Comment by amancevice** [comment]
No, no change in behavior:

```bash
$ docker run -d --name superset-0-15-0 -p 8088:8088 amancevice/superset:0.15.0
$ curl http://localhost:8088/health
curl: (52) Empty reply from server
$ docker exec superset-0-15-0 curl http://localhost:8088/health
OK
```

**Comment by amancevice** [comment]
I also tried building a new image from scratch using the debian distribution (current is alpine), but same behavior there, too.

**Comment by amancevice** [comment]
Running in debug mode seems to fix it:

```bash
$ docker run -d --name superset-0-15-0 -p 8088:8088 amancevice/superset:0.15.0 runserver -d
$ curl localhost:8088/health
OK
```

I suspect this commit to be the culprit: https://github.com/airbnb/superset/commit/50da4f8c0708f91ff24c0abd7189a137a1415bf6

**Comment by amancevice** [comment]
Ah, I think this is it: https://github.com/airbnb/superset/blob/master/superset/bin/superset#L46

The default address is `0.0.0.0` for debug mode, but `127.0.0.1` for normal.

Confirmed that this works:

```bash
$ docker run -d --name superset-0-15-0 -p 8088:8088 amancevice/superset:0.15.0 runserver -a 0.0.0.0
$ curl localhost:8088/health
OK
```

I'll open a PR
