### ISSUE TITLE
[sql lab] show run button even when no database is selected

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#1849]
- if no database is selected, show run button as disabled
- maybe choose a database by default on page load

![no-run-btns](https://cloud.githubusercontent.com/assets/130878/21239547/2ba6797a-c2bc-11e6-87a3-6872b8955bee.gif)

**Comment by jefffeng** [comment]
Rather than show the run button as disabled when no database is selected, could we show the run button as disabled only when no database is selected AND no text has been altered in the query window.  I want to ensure we support the use case where a user copies and pastes a query into a new tab.

**Comment by ascott** [comment]
i believe it is a requirement to choose a database before running your query even if you have just pasted a query into the sql editor pane. the sql query should determine the schema and table but does not specify the database afaik, which is why it needs to be choosen from the dropdown.

another option here is to always choose a default db so if the user pastes a query into the editor they will be able to run the query right away. if it's against the wrong db, they should get a useful error message.

**Comment by ascott** [comment]
looks like this was fixed already. 

<img width="646" alt="screenshot 2017-02-02 18 27 43" src="https://cloud.githubusercontent.com/assets/130878/22577319/af46e5d2-e975-11e6-9432-d4a216a5f677.png">
