### ISSUE TITLE
Unable to construct SQLAlchemy URI for Teradata which can read and load Cover views 

### ISSUE THREAD

**Issue by JagadishBobade** [airbnb/superset#1870]
Make sure these boxes are checked before submitting your issue - thank you!

- [yes ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ yes] I have reproduced the issue with at least the latest released version of superset
- [yes ] I have checked the issue tracker for the same issue and I haven't found one similar

Hello All, 

I was trying to connect to Teradata database via Superset using SQLAlchemy URI. I was successful in connecting and reading the tables. but i am facing issue in loading views. Please can one help with the valid Parameters to pass so i can add view as table in Superset

Here is my SQLAlchemy URI for connecting and pulling table data: Its successful 

    SQLAlchemy URI >teradata://UID:PWD@Servername:22/Table_Schema_name?authentication=LDAP

Here is my SQLAlchemy URI for connecting and pulling view data: It fails with below error, 
    
     SQLAlchemy URI >teradata://UID:PWD@Servername:22/View_Schema_name?authentication=LDAP
Extra: 
{
    "metadata_params": {"reflect":{"bind":"teradata://UID:PWD@Servername:22/View_Schema_name?authentication=LDAP","views":"True","extend_existing":"False","autoload_replace":"True"}},
    "engine_params": {}
}

Error :  ERROR:root:A bind must be supplied in conjunction with reflect=True

**Comment by JagadishBobade** [comment]
Anyone here who can help with this request ?

**Comment by mistercrunch** [comment]
https://github.com/Teradata/sqlalchemy-teradata is probably a better resource for help,  though I notice that your JSON doesn't seem proper, you should use `true` and not `"True"` as in:
```
{
    "metadata_params": {
        "reflect": {
            "bind": "teradata://UID:PWD@Servername:22/View_Schema_name?authentication=LDAP",
             "views": true, 
             "extend_existing": false, "autoload_replace": true
         }
     },
    "engine_params": {}
}
```

**Comment by xrmx** [comment]
Looks like a configuration issue, closing.

**Comment by SanjayJosh** [comment]
I did do pip install sqlalchemy-teradata , and then restart superset.
However, on giving this URI: `teradata://UID:PWD@Servername:22/View_Schema_name?authentication=LDAP` in superset , I get 
`ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:teradata"}`
