### ISSUE TITLE
in config.py SUPERSET_WEBSERVER_TIMEOUT, SQLLAB_TIMEOUT seems doesn't work

### ISSUE THREAD

**Issue by zhangjiajie023** [airbnb/superset#1872]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.0

### Expected results
timeout error should occur after the given time

### Actual results
timeout error occurs in less than 30s

### Steps to reproduce
in config.py set:
SUPERSET_WEBSERVER_TIMEOUT = 600
SQLLAB_TIMEOUT = 600

and then debug superset

**Comment by xrmx** [comment]
Are you using 0.15.0 or master?

**Comment by mistercrunch** [comment]
Timeouts don't work with the debug/dev webserver for some reason and probably is a "wont fix", can you confirm that this is what you are reporting?

**Comment by zhangjiajie023** [comment]
@xrmx not master, release version

**Comment by zhangjiajie023** [comment]
@mistercrunch ye, i found it. SQLLAB_TIMEOUT is used for the query in sql_lab, and  SUPERSET_WEBSERVER_TIMEOUT is for something other

**Comment by xrmx** [comment]
So can we close this?
