### ISSUE TITLE
npm install stuck at 78% additional chunk assets

### ISSUE THREAD

**Issue by yhc1990518** [airbnb/superset#1877]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

npm version:3.10.9
python version:2.7.5
nodejs version:6.9.2
centOS version:7.2

When I executed 'npm run prod' it will be stuck at **78% additional chunk assets**, and sometimes it also will be stuck at **80% optimize chunk assets**

Is there anyone know how to solve about this?

thanks

**Comment by xrmx** [comment]
You just have to wait, it'll finish eventually.

**Comment by yhc1990518** [comment]
Is there anyway to speed it up?

**Comment by xrmx** [comment]
@yhc1990518 if you find a way you are very welcome to contribute it

**Comment by thmspl** [comment]
How can I solve this problem? I have the same problem at the moment. It's stuck and doesn't continue. Please don't say "just waiting" this doesn't solve the problem!
