### ISSUE TITLE
Error while processing cluster HTTP Error 405: HTTP method POST is not supported by this URL Druid Error:None

### ISSUE THREAD

**Issue by singhania** [airbnb/superset#1880]
Hi,
I am trying to setup druid cluster with Superset as my UI.
One Issue that I am facing is that I kept my broker nodes behind a load balancer and providing that IP as a broker host and port on which the druid services running but when I execute refresh druid metadata the its giving me the below error  

Error while processing cluster HTTP Error 405: HTTP method POST is not supported by this URL Druid Error:None

I understand that it is because its not able to connect to the broker node.

So how to fix this ?

**Comment by xrmx** [comment]
Does it work if you connect superset to one of your druid instance? if so there's something wrong in your load balancer config.

**Comment by singhania** [comment]
Yea the problem was with load balancer config.
Thanks for the pointer.
