### ISSUE TITLE
argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by RajkumarKadari** [airbnb/superset#1904]
I am very new to Caravel. I would like to explore the Caravel and its features for enterprise use.
Can any one gives info/article links to get clarity on the below.

**currently am facing issue : argument of type 'NoneType' is not iterable**

It would be great if you can share any link where I can explore more.

**Comment by xrmx** [comment]
This is called superset so i assume you are using a very old version of this. Please add all the needed information per template issue.

**Comment by RajkumarKadari** [comment]
Thnx i have updated.

**Comment by xrmx** [comment]
@RajkumarKadari so we can close this?

**Comment by RajkumarKadari** [comment]
Yes thanks for the support...

And one more :  its support Hive Views?

(Hive----> presto------> superset)

**Comment by ebuildy** [comment]
Got the same issue with superset 0.17.4 (via Docker):

Running a query via "SQL Labs", on Presto:

```
superset_1  | 2017-04-10 10:28:20,583:ERROR:root:argument of type 'NoneType' is not iterable
superset_1  | Traceback (most recent call last):
superset_1  |   File "/usr/lib/python3.5/site-packages/superset/views/core.py", line 1994, in sql_json
superset_1  |     query_id=query_id, return_results=True)
superset_1  |   File "/usr/lib/python3.5/site-packages/celery/local.py", line 188, in __call__
superset_1  |     return self._get_current_object()(*a, **kw)
superset_1  |   File "/usr/lib/python3.5/site-packages/celery/app/task.py", line 420, in __call__
superset_1  |     return self.run(*args, **kwargs)
superset_1  |   File "/usr/lib/python3.5/site-packages/superset/sql_lab.py", line 123, in get_sql_results
superset_1  |     engine = database.get_sqla_engine(schema=query.schema)
superset_1  |   File "/usr/lib/python3.5/site-packages/superset/models/core.py", line 565, in get_sqla_engine
superset_1  |     url.database = self.get_database_for_various_backend(url, schema)
superset_1  |   File "/usr/lib/python3.5/site-packages/superset/models/core.py", line 571, in get_database_for_various_backend
superset_1  |     if '/' in database:
```

but I can use this data-source on dashboard without any problem.

**Comment by desavera** [comment]
+1 !!! Thanks ebuildy ... not using the menu on the left solves it in deed !

**Comment by desavera** [comment]
Could someone confirm this was fixed on new releases ???
