### ISSUE TITLE
[sql lab] Columns not matching data

### ISSUE THREAD

**Issue by cgivre** [airbnb/superset#1911]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Actual results
![screen shot 2017-01-06 at 09 56 55](https://cloud.githubusercontent.com/assets/5513150/21721722/8981d110-d3f7-11e6-9c34-65a2e3234942.png)

### Steps to reproduce
I'm working on getting Apache Drill to work with SuperSet and I've written a Python DBAPI driver for Drill as well as a Sqlalchemy dialect.   (BTW, I am very impressed with SuperSet and think it is really awesome!)  Anyway, I've gotten Drill to connect to Superset, and gotten it to query schemata and even view files in SQL Lab.  

Here is the query that I'm executing:
Here is the query being executed:
```
SELECT `ipVersion`, 
 `Frame_Number`,      
 `Protocol`,       
`MACAddressSource`,     
 `MACAddressDestination`,      
 `PacketLength`,       
`Timestamp`,      
 `Source_IP`,      
`Destination_IP`,       
`IP_Protocol`,      
`IP_Protocol_Name`,       
`IP_Protocol_Desc`,       
`sourcePort`,      
`destinationPort` 
FROM dfs.test.`tcp-1.pcap` LIMIT 100
```
(Yes.. I'm querying a pcap file...)

However, I've reached a point where I'm a little stuck and wanted to ask for some assistance.  The basic problem I'm running into is that Superset doesn't seem to be mapping the data to the correct columns.    The dialect seems to be returning the data with the appropriate field names in a python dictionary (see below) but SQL Lab doesn't seem to be putting the data in the correct column.  

Here is the query being executed:
```
SELECT `ipVersion`, 
 `Frame_Number`,      
 `Protocol`,       
`MACAddressSource`,     
 `MACAddressDestination`,      
 `PacketLength`,       
`Timestamp`,      
 `Source_IP`,      
`Destination_IP`,       
`IP_Protocol`,      
`IP_Protocol_Name`,       
`IP_Protocol_Desc`,       
`sourcePort`,      
`destinationPort` 
FROM dfs.test.`tcp-1.pcap` LIMIT 100
```

and here is the debug info: 

```
2017-01-06 09:36:21,436:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
2017-01-06 09:36:21,483:DEBUG:requests.packages.urllib3.connectionpool:"POST /query.json HTTP/1.1" 200 None
2017-01-06 09:36:21,484:INFO:pydrill:POST http://localhost:8047/query.json [status:200 request:0.050s]
2017-01-06 09:36:21,484:DEBUG:pydrill:> {"query": "SELECT `ipVersion`,       `Frame_Number`,       `Protocol`,       `MACAddressSource`,       `MACAddressDestination`,       `PacketLength`,       `Timestamp`,       `Source_IP`,       `Destination_IP`,       `IP_Protocol`,       `IP_Protocol_Name`,       `IP_Protocol_Desc`,       `sourcePort`,       `destinationPort` FROM dfs.test.`tcp-1.pcap` LIMIT 100", "queryType": "SQL"}
2017-01-06 09:36:21,484:DEBUG:pydrill:< {
  "columns" : [ "ipVersion", "Frame_Number", "Protocol", "MACAddressSource", "MACAddressDestination", "PacketLength", "Timestamp", "Source_IP", "Destination_IP", "IP_Protocol", "IP_Protocol_Name", "IP_Protocol_Desc", "sourcePort", "destinationPort" ],
  "rows" : [ {
    "destinationPort" : "0",
    "sourcePort" : "161",
    "IP_Protocol" : "6",
    "PacketLength" : "98",
    "Destination_IP" : "192.168.0.2",
    "Timestamp" : "1970-01-01T00:00:00.000-05:00",
    "IP_Protocol_Name" : "TCP",
    "IP_Protocol_Desc" : "Transmission Control Protocol",
    "ipVersion" : "4",
    "MACAddressDestination" : "FE:00:00:00:00:01",
    "Protocol" : "TCP",
    "Frame_Number" : "1",
    "MACAddressSource" : "FE:00:00:00:00:02",
    "Source_IP" : "192.168.0.1"
  }, {
    "destinationPort" : "0",
    "sourcePort" : "161",
    "IP_Protocol" : "6",
    "PacketLength" : "98",
    "Destination_IP" : "192.168.0.2",
    "Timestamp" : "1970-01-01T00:00:00.000-05:00",
    "IP_Protocol_Name" : "TCP",
    "IP_Protocol_Desc" : "Transmission Control Protocol",
    "ipVersion" : "4",
    "MACAddressDestination" : "FE:00:00:00:00:01",
    "Protocol" : "TCP",
    "Frame_Number" : "2",
    "MACAddressSource" : "FE:00:00:00:00:02",
    "Source_IP" : "192.168.0.1"
  },```

You can see that the fields contain the correct data but SQL Lab doesn't seem to display them in the correct column.  This problem seems to only happen when I query Drill, and is the same even if I use a very simple query.  

I suspect that the issue is something that the sqlalchemy dialect is returning, but I'm not really sure what to do next and I wanted to reach out to the Superset community to see if anyone has any suggestions as to what to do next. 

Thanks!

**Comment by xrmx** [comment]
Have you tried a query against a table in the database you installed superset? We can then confirm or (moslty) exclude something broken in the sql lab ui,

**Comment by cgivre** [comment]
HI Riccardo, 
I have tried other datasets and they are working, which leads me to believe that the problem is with my drill dialect but I’m at a loss as to why.  It appears as if the dialect is working.  I’m not familiar enough with Superset to even know where to look.
Thanks,
—C

**Comment by mistercrunch** [comment]
Nice! a dbapi and sqlalchemy support are great assets for the Apache Drill community. Make sure to share that if you haven't already!

You may want to debug around here, see if columns are lined up when calling:
`pd.DataFrame(data, columns=column_names)`
https://github.com/airbnb/superset/blob/master/superset/sql_lab.py#L126

**Comment by cgivre** [comment]
Salut Maxime, 
I definitely intend to share it once it is in a presentable and more stable state. John Omernik started working on this, but his dialect used Drill’s ODBC interface.  I’ve had a lot of issues getting Drill to work with ODBC so I decided to use pydrill which uses the RESTful interface and hence no additional drivers to configure.  However, PyDrill isn’t DBAPI compliant, so I first had to build that… This was way more complicated than I first imagined, but I’m learning a lot so it’s fun. 
Thanks for the tip and I’ll probably have other questions as I go forward.  
Best,
— C

**Comment by mistercrunch** [comment]
I'm very familiar with the pyhive package which does the same thing (dbapi + sqlalchemy) for both Hive and Presto. It can be a good resource as you are building something very similar, especially Presto since it has its own REST api as well (Hive is thrift).

https://github.com/dropbox/PyHive

**Comment by cgivre** [comment]
I thought I would post the conclusion.  After digging into this a lot more, I found that the PyDrill driver was returning a dictionary of results.  Making that an `OrderedDict` corrected that problem. 
Thank you @mistercrunch for the assistance as that was really helpful in tracking the dataflow through Superset.
