### ISSUE TITLE
Pretty print json in the results in SQL Lab

### ISSUE THREAD

**Issue by bkyryliuk** [airbnb/superset#1915]
Right now query:
```
SELECT event_data
from some_schema.event_data
where date='2017-01-03' 
and event_name = 'event_name'
and event_data['a'] = 'a'
and event_data['b'] = '16501'
and event_data['description'] != ''
limit 1000
```
Results in:
<img width="320" alt="screen shot 2017-01-06 at 11 25 05 am" src="https://cloud.githubusercontent.com/assets/5727938/21730120/1a78d65e-d403-11e6-8d40-bcfa540c9ee6.png">

**Comment by mistercrunch** [comment]
It's interesting that the Presto driver (pyhive) returns probably python objects directly and that somehow it makes it to javascripts objects, these must be array or map type in Hive/Presto. It should be as easy as modifying the table react component with a code highlighter
