### ISSUE TITLE
[Explore V2] Date select options are not editable

### ISSUE THREAD

**Issue by bkyryliuk** [airbnb/superset#1916]
<img width="432" alt="screen shot 2017-01-06 at 11 59 39 am" src="https://cloud.githubusercontent.com/assets/5727938/21731116/adfa4210-d407-11e6-998c-953d9941e7ae.png">

I cannot modify the date I've entered.

**Comment by ascott** [comment]
this is a bug and/or a ux decision made by the folks who made [React Select](http://jedwatson.github.io/react-select/). It looks like it's not editable, but it actually is:
![explore-edit-dates](https://cloud.githubusercontent.com/assets/130878/22457854/ae9b38d2-e74e-11e6-9068-4572fda682d7.gif)
