### ISSUE TITLE
Field "Created by" is html and it's improperly rendered

### ISSUE THREAD

**Issue by 0x0ece** [airbnb/superset#1918]
### Superset version
0.15.1 and master

### Expected results
values in "Changed by" should be links

### Actual results
values in "Changed by" are texts e.g. '<a href="/superset/profile/emanuele/">Emanuele Cesena</a>'

### Steps to reproduce
Got to the url /druiddatasourcemodelview/list/
(note: this works fine with the Creator, e.g. in the list of dashboards)

**Comment by xrmx** [comment]
This looks like an easy patch, care to open a pull request?

**Comment by 0x0ece** [comment]
I'd love to, but I spent quite some time and didn't really figured out the whole path from the header definition to the react rendering.
 
Maybe @ascott can chime in and give me a hint?

**Comment by ascott** [comment]
looks like a Flask App Builder template issue. i think the fix may be to add the `safe` filter here where the column value is rendered: 
https://github.com/ascott/superset/blob/master/superset/templates/superset/fab_overrides/list_with_checkboxes.html#L69

http://stackoverflow.com/questions/12672469/how-to-render-html-content-with-jinja-using-flask#12673984
