### ISSUE TITLE
timestamp in TableView is returned in number

### ISSUE THREAD

**Issue by flametest** [airbnb/superset#1934]
in commit c14c7ed, the json_dumps function of class TableViz was deleted, but this default parameter of this function has different value -- utils.json_**iso**_dttm_ser:

    def json_dumps(self, obj):
        return json.dumps(obj, default=utils.json_iso_dttm_ser)

compared to json_**int**_dttm_ser in:

    def json_dumps(self, obj):
        """Used by get_json, can be overridden to use specific switches"""
        return json.dumps(obj, default=utils.json_int_dttm_ser, ignore_nan=True)

so when the granularity in not all in table view, the timestamp will be like this:

![1](https://cloud.githubusercontent.com/assets/2179241/21803724/5531b5b6-d766-11e6-8ea6-3c7dfdd2c6dd.png)

**Comment by xrmx** [comment]
Uhm so https://github.com/airbnb/superset/commit/a2c41bbace99eb3e749c59a3b2805c6e8e2b7130 is broken too as it'll always use *int* serializer
