### ISSUE TITLE
It take count variable every where, There is nothing to visualize output of sql query..

### ISSUE THREAD

**Issue by dineshrajput007** [airbnb/superset#1936]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by dineshrajput007** [comment]
It take count variable every where, There is nothing to visualize output of sql query..

**Comment by xrmx** [comment]
Superset is a tool, it won't create visualization on its own. You have to fiddle with the visualization type and its options to make something more appealing than the default count. If you follow the documentation and load the examples you'll see more examples.
