### ISSUE TITLE
Can we have a access Hive Views

### ISSUE THREAD

**Issue by RajkumarKadari** [airbnb/superset#1938]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
If pyhive support it probably yes. On the mailing list or gitter you may find more people using pyhive than here.
