### ISSUE TITLE
[sql lab] show better messaging when query that returns no results is run async

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#1966]
steps to repro:
1. write query that returns no results
2. run asynchronously
3. click fetch results
4. ui just keeps showing fetch results btn

solution: if query returns no results, we should not show fetch results button, and instead show no results messaging.

<img width="1077" alt="screenshot 2017-01-12 14 22 45" src="https://cloud.githubusercontent.com/assets/130878/21910911/006048c2-d8d3-11e6-9c1c-e0bfe4776f3c.png">

**Comment by vera-liu** [comment]
https://github.com/airbnb/superset/pull/2055
