### ISSUE TITLE
Purposing analysisTypes for Druid refresh metadata

### ISSUE THREAD

**Issue by noppanit** [airbnb/superset#1979]
If you have a very large dataset in Druid, refresh metadata can take a very long time and results in timeout. 

Not sure if we can pass `analysisTypes` just only `cardinality` or something that's configurable which results in a much faster query.

https://github.com/airbnb/superset/blob/2d866e3ffa9bfedd3b3dad0d3463767aae879a14/superset/models.py#L2018

http://druid.io/docs/latest/querying/segmentmetadataquery.html#analysistypes

Because by default it will look for all the types and it seems like we only care about the columns. 
 
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest

### Expected results
faster refresh druid metadata

### Actual results
faster refresh druid metadata

### Steps to reproduce
`superset refresh_druid -m true`

**Comment by noppanit** [comment]
`analysisTypes` is supported by pydruid.

**Comment by xrmx** [comment]
Has this been fixed in #1983?

**Comment by noppanit** [comment]
Yes it's fixed in #1983. I'm closing the issue.
