### ISSUE TITLE
SQL Labs query returning UTF8 decode error

### ISSUE THREAD

**Issue by mearroyo** [airbnb/superset#1999]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
      --Don't have access to the backend superset is installed in.
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.15.1

### Expected results

Columns matching those returned when the same query is ran in MySQL Workbench

### Actual results

'utf8' codec can't decode byte 0xe3 in position 1: invalid continuation byte

### Steps to reproduce

Run query:

SELECT
CONCAT('#RES', item.reservation_id) 'Res ID #',
IF (ISNULL(lead.id),
(SELECT CONCAT('#LEAD', MIN(lead.id))
    FROM reservation_item_stays ris
    LEFT JOIN reservation_items ri ON ri.id = ris.id
    LEFT JOIN leads lead ON lead.id = ri.lead_id
    WHERE ri.reservation_id = item.reservation_id),
CONCAT('#LEAD', lead.id)) 'Lead ID #',
CONCAT('#STAY', stay.id) 'Stay ID #',
stay.status 'Stay Status',
destination.name 'Destination'

  
FROM reservation_item_stays stay
LEFT JOIN reservation_item_modified_stays mo ON mo.stay_id = stay.id AND mo.id = (SELECT MAX(mo.id) FROM reservation_item_modified_stays mo WHERE mo.stay_id = mo.stay_id)
LEFT JOIN reservation_items item ON stay.id = item.id
LEFT JOIN leads lead ON lead.id = item.lead_id
LEFT JOIN rental_informations rental ON rental.id = IFNULL(mo.rental_information_id, stay.rental_information_id)
LEFT JOIN properties property ON property.id = rental.property_id
LEFT JOIN destination_neighborhoods neighborhood ON neighborhood.id = property.destination_neighborhood_id
LEFT JOIN destinations destination ON destination.id = neighborhood.destination_id

This error occurs consistently, but only on certain queries. In this case, the query performs as expected if I remove "destination.name 'Destination'"

**Comment by xrmx** [comment]
That's python2 right?

**Comment by mearroyo** [comment]
I put in an internal request for both the stacktrace and the python version yesterday (had the same thought). I'll come back with more info when I receive it. Thanks!

**Comment by mearroyo** [comment]
Still no traceback but confirmed to be running on Python 2.x. Upgraded to 3.x and the issue is resolved. Thank you.

**Comment by xrmx** [comment]
Closing then, thanks for the heads up!
