### ISSUE TITLE
JS Translation Problem

### ISSUE THREAD

**Issue by YinghaoPu** [airbnb/superset#2002]
Hi Superset Team,

As I know, superset can translate the words in .html and .py file easily, but the words in .js or .jsx can't be translated. I found a solution in  http://www.obviel.org/en/1.0b/i18n.html, and I try it locally, it works. but everytime I merge the newest code from your repository, it takes lots of time. Could you please add this found to your code?

Thanks

**Comment by xrmx** [comment]
@YinghaoPu thanks for the hint, looks promising. Could you please move the discussion to #1926 though?
