### ISSUE TITLE
Cannot use metric of type REAL

### ISSUE THREAD

**Issue by petroswork** [airbnb/superset#2010]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
14.1

### Expected results
Metric of type REAL should be available for selection.

### Actual results
No metric of type REAL is available to select for a slice.

### Steps to reproduce
1. Use a table with columns of type REAL or DATE.
2. Attempt to create a slice with metric of type REAL.

**Comment by xrmx** [comment]
Is this druid or sql alchemy?

**Comment by petroswork** [comment]
SQLAlchemy using PostgreSQL.

**Comment by xrmx** [comment]
What do you have in the "list table columns" tab of your table for your column? What metric do you want to use on your column?

**Comment by petroswork** [comment]
Well, the metric was missing. I assumed that the metrics would appear automatically, as in the case of columns of type INTEGER. Now that I created the metric, it works. Should I change the title?

**Comment by xrmx** [comment]
What metric do you expect to be created automatically for a REAL field?

**Comment by petroswork** [comment]
I used SUM(column), as the metric is a ratio of COUNTs aggregated in a day. Perhaps a way to display time series without any form of aggregation is required in this case?

**Comment by xrmx** [comment]
But is the sum checkbox checked? in the "list table columns"? I am pretty sure we are enabling some attributes on the columns depending on the type of fields, e.g. is_temporal.

**Comment by petroswork** [comment]
"Sum", "Min" and "Max" are enabled, yet the only Sql Metric appearing by default is "count".

**Comment by madmanbeck** [comment]
I'm also seeing the same behavior when using Redshift. 

However, if I update the table in Redshift changing the columns from REAL to FLOAT then Superset will automatically check off the **Sum**, **Min**, and **Max** options as well as create the **avg__** and **sum__** metrics.

**Comment by xrmx** [comment]
@petroswork @madmanbeck the PR above should do the trick
