### ISSUE TITLE
missing files while build superset 0.15.2

### ISSUE THREAD

**Issue by JessicaDuan** [airbnb/superset#2013]
After "python setup.py install", I found that something is missing in the directory "build".
Here is the SOURCE.txt in the superset.egg-info
```
setup.cfg
setup.py
superset/__init__.py
superset/cli.py
superset/config.py
superset/dataframe.py
superset/db_engine_specs.py
superset/extract_table_names.py
superset/forms.py
superset/import_util.py
superset/jinja_context.py
superset/models.py
superset/results_backends.py
superset/security.py
superset/source_registry.py
superset/sql_lab.py
superset/sql_parse.py
superset/utils.py
superset/views.py
superset/viz.py
superset.egg-info/PKG-INFO
superset.egg-info/SOURCES.txt
superset.egg-info/dependency_links.txt
superset.egg-info/not-zip-safe
superset.egg-info/requires.txt
superset.egg-info/top_level.txt
superset/bin/__init__.py
superset/bin/superset
superset/data/__init__.py
superset/data/countries.py
superset/migrations/__init__.py
superset/migrations/env.py
tests/__init__.py
tests/access_tests.py
tests/base_tests.py
tests/celery_tests.py
tests/core_tests.py
tests/druid_tests.py
tests/email_tests.py
tests/import_export_tests.py
tests/security_tests.py
tests/sql_parse_tests.py
tests/sqllab_tests.py
tests/superset_test_config.py
tests/utils_tests.py
```

And I only have these files in the directory "build", the most important thing like the "assets" is missing. Does anyone know why?

**Comment by xrmx** [comment]
They are missing because you have to build them as documented http://airbnb.io/superset/installation.html#making-your-own-build

**Comment by JessicaDuan** [comment]
@xrmx But I did follow the directions in the document...The only problem is that I remove the MANIFEST.in because "python setup.py install" always stuck at this sentence(However it's ok when building caravel). Is that the point?

**Comment by xrmx** [comment]
@JessicaDuan if you look at the content of the file you'll see exactly that :)
