### ISSUE TITLE
build superset from source  stuck

### ISSUE THREAD

**Issue by uptonking** [airbnb/superset#2015]
- [ok] I have checked the superset logs for python stacktraces and included it here as text if any
- [ok] I have reproduced the issue with at least the latest released version of superset
- [ok] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version  superset-airbnb_prod.0.15.0.1 downloaded from release
 "on Dec 16, 2016	airbnb_prod.0.15.0.1 "
"10 days ago	0.15.2" 
both  tried

### Expected results
build superset from source code with success

### Actual results
no success, stuck at  exec "python setup.py install/develop"  

![stuck at setup.py](https://github.com/uptonking/assets/blob/master/issues/superset/setup_install.png)

### Steps to reproduce
build as the [Make your own build](http://airbnb.io/superset/installation.html#making-your-own-build) .
cd  ./superset-airbnb_prod.0.15.0.1/superset/assets
npm install
npm run prod
cd ./superset-airbnb_prod.0.15.0.1
python setup.py install

GET STUCK every time when exec "python setup.py install/develop" ,I hava tried 
- centos 7.2+ python2.7 + node7.0+ npm3.10
- centos 7.2+ python3.5 + node7.0+ npm3.10
- ubuntu 14.04 + python2.7 + node7.3+ npm3.10

exec "npm run " & "python setup.py install" is really slow, I have spent 30+ hours on this, driving me crazy.
Help please.
Thanks

**Comment by uptonking** [comment]
the pic doesn't show.   The terminal message hangs at
"writing manifest file 'superset.egg-info/SOURCES.txt'
reading manifest file 'superset.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in"
the memory is incredibly high, up to 15GB.

**Comment by JessicaDuan** [comment]
+1
caravel 0.11.0
superset 0.15.1 & 0.15.2

**Comment by xrmx** [comment]
master builds fine here

**Comment by uptonking** [comment]
@xrmx thanks, i will try ```python setup.py sdist``` instead of  ```python setup.py  install```.

**Comment by uptonking** [comment]
@xrmx please.
Just tried ```python setup.py sdist``` and ```python setup.by install``` both on superset-master,  failed again. Error is the same as before.  
From the network monitor, ***both*** cases have ***NO*** network IO. the memory is up to 15G, then itself killed itself.  

Could i t be the problem of the setup.by.  It always hangs at ```reading manifest template 'MANIFEST.in```

My PC is CentOS 7.2. Python 2.7.5, Node 7.0.0, NPM 3.10.8.

**Comment by uptonking** [comment]
@xrmx I solve this problem finally, please close the issue.
The problem lies in myself. because I use cnpm instead of npm, making my node_modules folder containing soft links which caused `python setup.py install` dist assets folder in loop.

**Comment by xrmx** [comment]
@uptonking yeah checked for links creating infinite loops but there weren't :) btw why you haven't said that on your issue instead of writing npm?

**Comment by RichardKyire** [comment]
@uptonking i have the save problem with yours ,how do you solve your problem,do you change the MANIFEST.in file?

**Comment by uptonking** [comment]
@RichardKyire  
my solution is described above. 
I didn't change the MANIFEST.in.
please make sure there is no soft links or folder shortcuts in your ./superset/assets/node_modules folder

**Comment by RichardKyire** [comment]
@uptonking 
thanks your solution.i have a little question , does  cnpm command will create a soft links or folder shortcuts in node_modules folder? i try to use npm command  ,but  it get some wrong .

**Comment by uptonking** [comment]
@RichardKyire 
cnpm will do. so you should use `npm install`.
if you failed for the sake of poor network, u better use a proxy, especially in China.

**Comment by RichardKyire** [comment]
@uptonking 
I follow your suggection , use a proxy and use ' npm install ' ,bug it still get a error . The error message is 'no matching version found for gulp-sourcemaps@1.7.0 ' , i try use 'npm install gulp-sourcemaps' to install gulp-sourcemaps  module ,it can intall a higher version than 1.7.0 successfully .  i get very confused ,how can i set the gulp-sourcemaps version in the superset or how can i sovle this question?

**Comment by uptonking** [comment]
@RichardKyire 
the dependencies can be set  in  ` ./superset/assets/package.json`.
better not change the default dependency version.
just try `npm install`  again and again, u will make it sometime :flushed:

**Comment by zhizunbao514** [comment]
这个该怎么解决呢？  我也遇到同样的问题

**Comment by tingxin** [comment]
Hi Guys,
i also met this issue, when install it, it took so long time block at reading manifest template 'MANIFEST.in'? anyone idea?

sudo python3 setup.py install 
-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
VERSION: 0.999.0dev
GIT SHA: 9423e9a8be1c0fc0bad8fbd2f04fe298d08469bf
-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
/usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/local/lib/python3.6/site-packages/setuptools/dist.py:397: UserWarning: Normalizing '0.999.0dev' to '0.999.0.dev0'
  normalized_version,
running install
running bdist_egg
running egg_info
creating apache_superset.egg-info
writing apache_superset.egg-info/PKG-INFO
writing dependency_links to apache_superset.egg-info/dependency_links.txt
writing requirements to apache_superset.egg-info/requires.txt
writing top-level names to apache_superset.egg-info/top_level.txt
writing manifest file 'apache_superset.egg-info/SOURCES.txt'
reading manifest file 'apache_superset.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'

**Comment by GautamProtegrity** [comment]
"I don't understand despite all my efforts for last 2 weeks why i keep getting this issue and not being able to make it up and running on server. This is crazy. from logs also its not clear what exactly is the issue as it is also a git repository."
Installing collected packages: superset-hand-china                                                                                                                                                                                                                                Running setup.py install for superset-hand-china: started                                                                                                                                                                                                                         Running setup.py install for superset-hand-china: finished with status 'error'                                                                                                                                                                                                  ERROR: Complete output from command 'd:\python\python35\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\271293\\AppData\\Local\\Temp\\pip-install-jv0b4_8_\\superset-hand-china\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__); code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\271293\AppData\Local\Temp\pip-record-4pz6i6pt\install-record.txt' --single-version-externally-managed --compile:                            ERROR: fatal: not a git repository (or any of the parent directories): .git                                                                                                                                                                                                     -==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-                                                                                                                                                                                                                    VERSION: 1.3.8                                                                                                                                                                                                                                                                  GIT SHA:                                                                                                                                                                                                                                                                        -==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-                                                                                                                                                                                                                    running install                                                                                                                                                                                                                                                                 running build                                                                                                                                                                                                                                                                   running build_py                                                                                                                                                                                                                                                                creating build                                                                                                                                                                                                                                                                  creating build\lib                                                                                                                                                                                                                                                              creating build\lib\superset                                                                                                                                                                                                                                                     copying superset\cache_util.py -> build\lib\superset                                                                                                                                                                                                                            copying superset\cli.py -> build\lib\superset                                                                                                                                                                                                                                   copying superset\config.py -> build\lib\superset                                                                                                                                                                                                                                copying superset\dataframe.py -> build\lib\superset                                                                                                                                                                                                                             copying superset\db_engine_specs.py -> build\lib\superset                                                                                                                                                                                                                       copying superset\extract_table_names.py -> build\lib\superset                                                                                                                                                                                                                   copying superset\import_util.py -> build\lib\superset                                                                                                                                                                                                                           copying superset\jinja_context.py -> build\lib\superset                                                                                                                                                                                                                         copying superset\legacy.py -> build\lib\superset                                                                                                                                                                                                                                copying superset\security.py -> build\lib\superset                                                                                                                                                                                                                              copying superset\sql_lab.py -> build\lib\superset                                                                                                                                                                                                                               copying superset\sql_parse.py -> build\lib\superset                                                                                                                                                                                                                             copying superset\stats_logger.py -> build\lib\superset                                                                                                                                                                                                                          copying superset\utils.py -> build\lib\superset                                                                                                                                                                                                                                 copying superset\viz.py -> build\lib\superset                                                                                                                                                                                                                                   copying superset\__init__.py -> build\lib\superset                                                                                                                                                                                                                              creating build\lib\superset\bin                                                                                                                                                                                                                                                 copying superset\bin\__init__.py -> build\lib\superset\bin                                                                                                                                                                                                                      creating build\lib\superset\connectors                                                                                                                                                                                                                                          copying superset\connectors\connector_registry.py -> build\lib\superset\connectors                                                                                                                                                                                              copying superset\connectors\__init__.py -> build\lib\superset\connectors                                                                                                                                                                                                        creating build\lib\superset\data                                                                                                                                                                                                                                                copying superset\data\countries.py -> build\lib\superset\data                                                                                                                                                                                                                   copying superset\data\__init__.py -> build\lib\superset\data                                                                                                                                                                                                                    creating build\lib\superset\db_engines                                                                                                                                                                                                                                          copying superset\db_engines\hive.py -> build\lib\superset\db_engines                                                                                                                                                                                                            copying superset\db_engines\presto.py -> build\lib\superset\db_engines                                                                                                                                                                                                          copying superset\db_engines\__init__.py -> build\lib\superset\db_engines                                                                                                                                                                                                        creating build\lib\superset\hand                                                                                                                                                                                                                                                copying superset\hand\interceptor.py -> build\lib\superset\hand                                                                                                                                                                                                                 copying superset\hand\mail.py -> build\lib\superset\hand                                                                                                                                                                                                                        copying superset\hand\models.py -> build\lib\superset\hand                                                                                                                                                                                                                      copying superset\hand\role_manager.py -> build\lib\superset\hand                                                                                                                                                                                                                copying superset\hand\role_views.py -> build\lib\superset\hand                                                                                                                                                                                                                  copying superset\hand\scheduler.py -> build\lib\superset\hand                                                                                                                                                                                                                   copying superset\hand\start.py -> build\lib\superset\hand                                                                                                                                                                                                                       copying superset\hand\views.py -> build\lib\superset\hand                                                                                                                                                                                                                       copying superset\hand\viz.py -> build\lib\superset\hand                                                                                                                                                                                                                         copying superset\hand\__init__.py -> build\lib\superset\hand                                                                                                                                                                                                                    creating build\lib\superset\migrations                                                                                                                                                                                                                                          copying superset\migrations\env.py -> build\lib\superset\migrations                                                                                                                                                                                                             copying superset\migrations\__init__.py -> build\lib\superset\migrations                                                                                                                                                                                                        creating build\lib\superset\models                                                                                                                                                                                                                                              copying superset\models\annotations.py -> build\lib\superset\models                                                                                                                                                                                                             copying superset\models\core.py -> build\lib\superset\models                                                                                                                                                                                                                    copying superset\models\helpers.py -> build\lib\superset\models                                                                                                                                                                                                                 copying superset\models\sql_lab.py -> build\lib\superset\models                                                                                                                                                                                                                 copying superset\models\__init__.py -> build\lib\superset\models                                                                                                                                                                                                                creating build\lib\superset\translations                                                                                                                                                                                                                                        copying superset\translations\utils.py -> build\lib\superset\translations                                                                                                                                                                                                       copying superset\translations\__init__.py -> build\lib\superset\translations                                                                                                                                                                                                    creating build\lib\superset\views                                                                                                                                                                                                                                               copying superset\views\annotations.py -> build\lib\superset\views                                                                                                                                                                                                               copying superset\views\base.py -> build\lib\superset\views                                                                                                                                                                                                                      copying superset\views\core.py -> build\lib\superset\views                                                                                                                                                                                                                      copying superset\views\sql_lab.py -> build\lib\superset\views                                                                                                                                                                                                                   copying superset\views\__init__.py -> build\lib\superset\views                                                                                                                                                                                                                  creating build\lib\superset\connectors\base                                                                                                                                                                                                                                     copying superset\connectors\base\models.py -> build\lib\superset\connectors\base                                                                                                                                                                                                copying superset\connectors\base\views.py -> build\lib\superset\connectors\base                                                                                                                                                                                                 copying superset\connectors\base\__init__.py -> build\lib\superset\connectors\base                                                                                                                                                                                              creating build\lib\superset\connectors\druid                                                                                                                                                                                                                                    copying superset\connectors\druid\models.py -> build\lib\superset\connectors\druid                                                                                                                                                                                              copying superset\connectors\druid\views.py -> build\lib\superset\connectors\druid                                                                                                                                                                                               copying superset\connectors\druid\__init__.py -> build\lib\superset\connectors\druid                                                                                                                                                                                            creating build\lib\superset\connectors\sqla                                                                                                                                                                                                                                     copying superset\connectors\sqla\models.py -> build\lib\superset\connectors\sqla                                                                                                                                                                                                copying superset\connectors\sqla\views.py -> build\lib\superset\connectors\sqla                                                                                                                                                                                                 copying superset\connectors\sqla\__init__.py -> build\lib\superset\connectors\sqla                                                                                                                                                                                              running egg_info                                                                                                                                                                                                                                                                writing requirements to superset_hand_china.egg-info\requires.txt                                                                                                                                                                                                               writing superset_hand_china.egg-info\PKG-INFO                                                                                                                                                                                                                                   writing dependency_links to superset_hand_china.egg-info\dependency_links.txt                                                                                                                                                                                                   writing top-level names to superset_hand_china.egg-info\top_level.txt                                                                                                                                                                                                           warning: manifest_maker: standard file '-c' not found                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           reading manifest file 'superset_hand_china.egg-info\SOURCES.txt'                                                                                                                                                                                                                reading manifest template 'MANIFEST.in'                                                                                                                                                                                                                                         warning: no previously-included files matching '*' found under directory 'superset\static\docs'                                                                                                                                                                                 warning: no previously-included files matching '*' found under directory 'superset\static\spec'                                                                                                                                                                                 warning: no previously-included files matching '*' found under directory 'superset\static\assets\node_modules'                                                                                                                                                                  warning: no previously-included files matching '*' found under directory 'tests'                                                                                                                                                                                                writing manifest file 'superset_hand_china.egg-info\SOURCES.txt'                                                                                                                                                                                                                copying superset\bin\superset -> build\lib\superset\bin                                                                                                                                                                                                                         creating build\lib\superset\static                                                                                                                                                                                                                                              creating build\lib\superset\static\assets                                                                                                                                                                                                                                       copying superset\static\assets\.babelrc -> build\lib\superset\static\assets                                                                                                                                                                                                     copying superset\static\assets\.babelrc.bac -> build\lib\superset\static\assets                                                                                                                                                                                                 copying superset\static\assets\.eslintignore -> build\lib\superset\static\assets                                                                                                                                                                                                copying superset\static\assets\.eslintrc -> build\lib\superset\static\assets                                                                                                                                                                                                    copying superset\static\assets\.istanbul.yml -> build\lib\superset\static\assets                                                                                                                                                                                                copying superset\static\assets\backendSync.json -> build\lib\superset\static\assets                                                                                                                                                                                             copying superset\static\assets\js_build.sh -> build\lib\superset\static\assets                                                                                                                                                                                                  copying superset\static\assets\npm-debug.log.1666687767 -> build\lib\superset\static\assets                                                                                                                                                                                     copying superset\static\assets\package-lock.json -> build\lib\superset\static\assets                                                                                                                                                                                            copying superset\static\assets\package.json -> build\lib\superset\static\assets                                                                                                                                                                                                 copying superset\static\assets\version_info.json -> build\lib\superset\static\assets                                                                                                                                                                                            copying superset\static\assets\webpack.config.js -> build\lib\superset\static\assets                                                                                                                                                                                            copying superset\static\assets\webpack.config_bak.js -> build\lib\superset\static\assets                                                                                                                                                                                        creating build\lib\superset\static\assets\branding                                                                                                                                                                                                                              copying superset\static\assets\branding\Full Lockup With Text.svg -> build\lib\superset\static\assets\branding                                                                                                                                                                  copying superset\static\assets\branding\Full Lockup With Text@2x.png -> build\lib\superset\static\assets\branding                                                                                                                                                               copying superset\static\assets\branding\Full Lockup Without Text@1x.svg -> build\lib\superset\static\assets\branding                                                                                                                                                            copying superset\static\assets\branding\Full Lockup Without Text@2x.png -> build\lib\superset\static\assets\branding                                                                                                                                                            copying superset\static\assets\branding\Horizontal.svg -> build\lib\superset\static\assets\branding                                                                                                                                                                             copying superset\static\assets\branding\Horizontal@2x.png -> build\lib\superset\static\assets\branding                                                                                                                                                                          copying superset\static\assets\branding\Solo Mark.png -> build\lib\superset\static\assets\branding                                                                                                                                                                              copying superset\static\assets\branding\Solo Mark@1x.svg -> build\lib\superset\static\assets\branding                                                                                                                                                                           creating build\lib\superset\static\assets\dist                                                                                                                                                                                                                                  copying superset\static\assets\dist\448c34a56d699c29117adc64c43affeb.woff2 -> build\lib\superset\static\assets\dist                                                                                                                                                             copying superset\static\assets\dist\45c73723862c6fc5eb3d6961db2d71fb.eot -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\4b5a84aaf1c9485e060c503a0ff8cadb.woff2 -> build\lib\superset\static\assets\dist                                                                                                                                                             copying superset\static\assets\dist\596814caa4fbaecbf5014bcfe8e363fb.ttf -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\5db2ea1bcb7a6cc078755c90458c3b65.svg -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\76a4f23c6be74fd309e0d0fd2c27a5de.svg -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\7c87870ab40d63cfb8870c1f183f9939.ttf -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\89889688147bd7575d6327160d64e760.svg -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\addSlice.5d83e1775d528827e8af.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                             copying superset\static\assets\dist\ag-grid.99ac761271f480148430.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                              copying superset\static\assets\dist\bootstrap.ed208d2afca2619a9fde.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                            copying superset\static\assets\dist\common.82f50deb1fb25ce18bfe.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\d3-tip.68c7016f09febed8cf13.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\d3.6166821421cb1c23017f.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                                   copying superset\static\assets\dist\dashboard.3d424b9b77374fae69a5.css -> build\lib\superset\static\assets\dist                                                                                                                                                                 copying superset\static\assets\dist\dashboard.3d424b9b77374fae69a5.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                            copying superset\static\assets\dist\dashboard_download.c0709b8c5a6bc59fbc1d.css -> build\lib\superset\static\assets\dist                                                                                                                                                        copying superset\static\assets\dist\dashboard_download.c0709b8c5a6bc59fbc1d.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                   copying superset\static\assets\dist\datatables.net-bs.a4caf5ff7ea2c124b285.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                    copying superset\static\assets\dist\dfb02f8f6d0cedc009ee5887cc68f1f3.woff -> build\lib\superset\static\assets\dist                                                                                                                                                              copying superset\static\assets\dist\e18bbf611f2a2e43afc071aa2f4e1512.ttf -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\echarts.fb71fe7b402a3c296e55.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                              copying superset\static\assets\dist\explore.50cb3617cd883609d5b1.css -> build\lib\superset\static\assets\dist                                                                                                                                                                   copying superset\static\assets\dist\explore.50cb3617cd883609d5b1.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                              copying superset\static\assets\dist\f19a7f6c7a0b54b748277c40d7cf8882.eot -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\f4769f9bdb7466be65088239c12046d1.eot -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\fa2772327f55d8198301fdb8bcfc8158.woff -> build\lib\superset\static\assets\dist                                                                                                                                                              copying superset\static\assets\dist\ff94ad94c3a9d04bd2f80cb3c87dcccb.woff -> build\lib\superset\static\assets\dist                                                                                                                                                              copying superset\static\assets\dist\jquery.8fd8af7744be46549fae.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\manifest.json -> build\lib\superset\static\assets\dist                                                                                                                                                                                      copying superset\static\assets\dist\models.4535b3567145ab31d60b.css -> build\lib\superset\static\assets\dist                                                                                                                                                                    copying superset\static\assets\dist\models.4535b3567145ab31d60b.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\nvd3.f535c7e848ebb9c3429c.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                                 copying superset\static\assets\dist\profile.9fc504da59221e602580.css -> build\lib\superset\static\assets\dist                                                                                                                                                                   copying superset\static\assets\dist\profile.9fc504da59221e602580.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                              copying superset\static\assets\dist\react-ace.ebe55012a5215012b56f.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                            copying superset\static\assets\dist\react-bootstrap-table.775909efa2a72802397a.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                copying superset\static\assets\dist\react-bootstrap.55612c0ee758c3a27f2f.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                      copying superset\static\assets\dist\react-dom.dabc146e8210214fb693.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                            copying superset\static\assets\dist\react-gravatar.32bd240cdfb8aaca63e0.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                       copying superset\static\assets\dist\react-grid-layout.94c9fa29fa7f7a0b1330.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                    copying superset\static\assets\dist\react-map-gl.1844d2ef406bd87689d1.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                         copying superset\static\assets\dist\react-redux.4ae98851c417d9d4d4e2.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                          copying superset\static\assets\dist\react-resizable.7aab5a97ea33870647c1.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                      copying superset\static\assets\dist\react-select.0997ce81853b0a39cca7.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                         copying superset\static\assets\dist\react-syntax-highlighter.a99774a0c4640a4f64ba.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                             copying superset\static\assets\dist\react.4ea8e8f5cf8b14fa01ea.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                                copying superset\static\assets\dist\redux.4ed52cd669eda5cf9958.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                                copying superset\static\assets\dist\scheduler.7c20c67402adbc8fcaf6.css -> build\lib\superset\static\assets\dist                                                                                                                                                                 copying superset\static\assets\dist\scheduler.7c20c67402adbc8fcaf6.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                            copying superset\static\assets\dist\sqllab.7382fb858218949570f9.css -> build\lib\superset\static\assets\dist                                                                                                                                                                    copying superset\static\assets\dist\sqllab.7382fb858218949570f9.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                               copying superset\static\assets\dist\theme.ee7009f9471d05f201c4.css -> build\lib\superset\static\assets\dist                                                                                                                                                                     copying superset\static\assets\dist\theme.ee7009f9471d05f201c4.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                                copying superset\static\assets\dist\welcome.a644b2df482c55035665.css -> build\lib\superset\static\assets\dist                                                                                                                                                                   copying superset\static\assets\dist\welcome.a644b2df482c55035665.entry.js -> build\lib\superset\static\assets\dist                                                                                                                                                              creating build\lib\superset\static\assets\images                                                                                                                                                                                                                                copying superset\static\assets\images\babytux.jpg -> build\lib\superset\static\assets\images                                                                                                                                                                                    copying superset\static\assets\images\bubble.png -> build\lib\superset\static\assets\images                                                                                                                                                                                     copying superset\static\assets\images\caret-down.png -> build\lib\superset\static\assets\images                                                                                                                                                                                 copying superset\static\assets\images\caret-right.png -> build\lib\superset\static\assets\images                                                                                                                                                                                copying superset\static\assets\images\cloud.png -> build\lib\superset\static\assets\images                                                                                                                                                                                      copying superset\static\assets\images\create_role.png -> build\lib\superset\static\assets\images                                                                                                                                                                                copying superset\static\assets\images\dash.png -> build\lib\superset\static\assets\images                                                                                                                                                                                       copying superset\static\assets\images\druid_agg.png -> build\lib\superset\static\assets\images                                                                                                                                                                                  copying superset\static\assets\images\favicon.png -> build\lib\superset\static\assets\images                                                                                                                                                                                    copying superset\static\assets\images\loading.gif -> build\lib\superset\static\assets\images                                                                                                                                                                                    copying superset\static\assets\images\log3.png -> build\lib\superset\static\assets\images                                                                                                                                                                                       copying superset\static\assets\images\noimg.png -> build\lib\superset\static\assets\images                                                                                                                                                                                      copying superset\static\assets\images\s.png -> build\lib\superset\static\assets\images                                                                                                                                                                                          copying superset\static\assets\images\superset-logo@2x.png -> build\lib\superset\static\assets\images                                                                                                                                                                           copying superset\static\assets\images\superset.png -> build\lib\superset\static\assets\images                                                                                                                                                                                   copying superset\static\assets\images\superset_screenshot.png -> build\lib\superset\static\assets\images                                                                                                                                                                        creating build\lib\superset\static\assets\images\pictorial_bar                                                                                                                                                                                                                  Traceback (most recent call last):                                                                                                                                                                                                                                                File "", line 1, in                                                                                                                                                                                                                                             File "C:\Users\271293\AppData\Local\Temp\pip-install-jv0b4_8_\superset-hand-china\setup.py", line 101, in                                                                                                                                                                 'Programming Language :: Python :: 3.5',                                                                                                                                                                                                                                      File "d:\python\python35\lib\distutils\core.py", line 148, in setup                                                                                                                                                                                                               dist.run_commands()                                                                                                                                                                                                                                                           File "d:\python\python35\lib\distutils\dist.py", line 955, in run_commands                                                                                                                                                                                                        self.run_command(cmd)                                                                                                                                                                                                                                                         File "d:\python\python35\lib\distutils\dist.py", line 974, in run_command                                                                                                                                                                                                         cmd_obj.run()                                                                                                                                                                                                                                                                 File "d:\python\python35\lib\site-packages\setuptools\command\install.py", line 61, in run                                                                                                                                                                                        return orig.install.run(self)                                                                                                                                                                                                                                                 File "d:\python\python35\lib\distutils\command\install.py", line 539, in run                                                                                                                                                                                                      self.run_command('build')                                                                                                                                                                                                                                                     File "d:\python\python35\lib\distutils\cmd.py", line 313, in run_command                                                                                                                                                                                                          self.distribution.run_command(command)                                                                                                                                                                                                                                        File "d:\python\python35\lib\distutils\dist.py", line 974, in run_command                                                                                                                                                                                                         cmd_obj.run()                                                                                                                                                                                                                                                                 File "d:\python\python35\lib\distutils\command\build.py", line 135, in run                                                                                                                                                                                                        self.run_command(cmd_name)                                                                                                                                                                                                                                                    File "d:\python\python35\lib\distutils\cmd.py", line 313, in run_command                                                                                                                                                                                                          self.distribution.run_command(command)                                                                                                                                                                                                                                        File "d:\python\python35\lib\distutils\dist.py", line 974, in run_command                                                                                                                                                                                                         cmd_obj.run()                                                                                                                                                                                                                                                                 File "d:\python\python35\lib\site-packages\setuptools\command\build_py.py", line 47, in run                                                                                                                                                                                       self.build_package_data()                                                                                                                                                                                                                                                     File "d:\python\python35\lib\site-packages\setuptools\command\build_py.py", line 108, in build_package_data                                                                                                                                                                       outf, copied = self.copy_file(srcfile, target)                                                                                                                                                                                                                                File "d:\python\python35\lib\distutils\cmd.py", line 348, in copy_file                                                                                                                                                                                                            dry_run=self.dry_run)                                                                                                                                                                                                                                                         File "d:\python\python35\lib\distutils\file_util.py", line 125, in copy_file                                                                                                                                                                                                      log.info("%s %s -> %s", action, src, dir)                                                                                                                                                                                                                                     File "d:\python\python35\lib\distutils\log.py", line 44, in info                                                                                                                                                                                                                  self._log(INFO, msg, args)                                                                                                                                                                                                                                                    File "d:\python\python35\lib\distutils\log.py", line 34, in _log                                                                                                                                                                                                                  stream.write('%s\n' % msg)                                                                                                                                                                                                                                                    File "d:\python\python35\lib\encodings\cp1252.py", line 19, in encode                                                                                                                                                                                                             return codecs.charmap_encode(input,self.errors,encoding_table)[0]                                                                                                                                                                                                           UnicodeEncodeError: 'charmap' codec can't encode characters in position 52-53: character maps to                                                                                                                                                                     ----------------------------------------                                                                                                                                                                                                                                    ERROR: Command "'d:\python\python35\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\271293\\AppData\\Local\\Temp\\pip-install-jv0b4_8_\\superset-hand-china\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('" '"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\271293\AppData\Local\Temp\pip-record-4pz6i6pt\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\271293\Ap pData\Local\Temp\pip-install-jv0b4_8_\superset-hand-china\
--
