### ISSUE TITLE
[explore-v2] filter bug

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#2021]
When I click into a slice to explore further and add something, like perhaps change weekly aggregation to daily, and press 'Query' there is always an error (screenshot below) that's associated with automatic filter fields that pop up but contain no values (screenshot below). Once I remove the filters option by pressing on the - and then rerun everything runs.  

![image 2](https://cloud.githubusercontent.com/assets/130878/22229911/70f3a06a-e18f-11e6-96af-a30b9e7d8a77.png)

**Comment by vera-liu** [comment]
It might be that the url string contains flt_eq and flt_op. Is there a url to the slice for this bug?

**Comment by ascott** [comment]
i sent you an email with more details on this.

**Comment by vera-liu** [comment]
resolved within deprecate_v1
