### ISSUE TITLE
Can anybody explain how requests are getting formed in Superset app??

### ISSUE THREAD

**Issue by drahul12** [airbnb/superset#2025]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
Could you please be more specific?

**Comment by drahul12** [comment]
I am trying to learn superset app. I want to add extra parameter to the request when we click one of the dashboard from dashboards. and later to use it at backend. but I am not getting idea that from where the request goes to backend when we click dashboard link(eg. Births or World's Bank Data) or slice link(eg. Calendar Heatmap multiformat4)

**Comment by drahul12** [comment]
for adding extra parameter to dashboard request or slice request where to make the change? or where to add it so it will go as an request.args parameter at backend.

**Comment by drahul12** [comment]
Yup...got the answer.
