### ISSUE TITLE
[sql-labs] 414 Request-URI Too Large

### ISSUE THREAD

**Issue by mearroyo** [airbnb/superset#2026]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.1

I am trying to use the visualize feature on a fairly large SQL query in the SQL Labs and I am receiving the following error:  414 Request-URI Too Large

The URL is ~9.9k characters. Is this a hard limit or can I change the max length accepted?

Thank you.

**Comment by bkyryliuk** [comment]
@mearroyo - it should not be the case on master, we will have a release some time soon.

**Comment by mearroyo** [comment]
Great, thanks!

**Comment by xrmx** [comment]
Closing then.

**Comment by mearroyo** [comment]
Hello, 

I updated to 0.17.0

I'm getting the following error when using the visualize feature on large queries:

Bad Request
Request Line is too large (5491 > 4094)

I believe that this is related?
