### ISSUE TITLE
not getting a json of udated object in slices export to .json

### ISSUE THREAD

**Issue by drahul12** [airbnb/superset#2042]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by drahul12** [comment]
after slice refresh, I get the json correctly. but when I make changes and run query I get the json of that object which is there at refresh time.

**Comment by drahul12** [comment]
I found out the problem but didnt understand why its happening.So in my function, everytime I get only that request which is of refresh time object. SO for json do not get new request with updated parameters.

**Comment by xrmx** [comment]
I think asking on the mailing list would be better instead of opening an issue every time you don't find out how to do a thing, no? Also it's quite difficult to fix issues on your custom code if you don't post the code.

**Comment by drahul12** [comment]
ok..Is this a superset community?? then sorry. Ok no problem.

**Comment by xrmx** [comment]
Mailing list is there https://groups.google.com/forum/#!forum/airbnb_superset
