### ISSUE TITLE
Linechart tooltip legend stucks in HTML DOM

### ISSUE THREAD

**Issue by szmate1618** [airbnb/superset#2043]
Hi Superset people! I need your wisdom once again. Is it even a Superset issue? Or an nvd3 one?
Is there any chance for a fix or a workaround? Thanks in advance!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
Legend not burning into the video memory.

### Actual results
![tooltip_dont_disappear](https://cloud.githubusercontent.com/assets/20772880/22291556/4b4689da-e307-11e6-8365-9a956a3f3b43.png)

### Steps to reproduce
It happens almost every time if I have the mouse cursor over the chart while the chart is (re)loading.

**Comment by szmate1618** [comment]
Possible work-around:
```
.nvtooltip:not(:last-of-type) {
 display: none;
}
```

**Comment by xrmx** [comment]
Same as #2053?

**Comment by szmate1618** [comment]
Ah, I didn't know scrolling has the same effect. But yes, these 2 issues seem to be the same, basically.

**Comment by ascott** [comment]
closing in favor of https://github.com/airbnb/superset/issues/2053

**Comment by ascott** [comment]
this one is actually a little different. if you are hovering over a tooltip and then refresh a slice, or the window gets resized, the tooltip gets stuck in the dom. it's an edge case, but will push a fix for this as well.

**Comment by ascott** [comment]
fixed with https://github.com/airbnb/superset/pull/2096
