### ISSUE TITLE
[explore v2] saving a slice from /explore/table/ throws 500

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#2056]
<img width="1153" alt="screenshot 2017-01-26 13 33 41" src="https://cloud.githubusercontent.com/assets/130878/22351361/5cc1f90e-e3cc-11e6-8772-d1c79c01087d.png">

**Comment by silashundt** [comment]
Is this the same bug as the one addressed in https://github.com/airbnb/superset/pull/2065?

**Comment by xrmx** [comment]
Indeed, thanks @silashundt
