### ISSUE TITLE
Pivot table format

### ISSUE THREAD

**Issue by yileic** [airbnb/superset#2058]
Hi,

If I want to customize the pivot table's number format, what's the best way to do it? 
Because currently the table html is generated in "viz.py", instead of in a js file. Thus, if I want to customize the look of pivot table, I need to modify the "viz.py" file. This may introduce future merge conflict with latest Superset. 
Would it be possible to generate the table html of pivot table in the js file? Then it would be super helpful and convenient for other people to customize it.
Thank you so much for your attention!

**Comment by yileic** [comment]
be able to independently customize pivot table **number** format would be enough

**Comment by RajkumarKadari** [comment]
is there any way to set it up for the comma in the Pivot table
