### ISSUE TITLE
[vis] dual axis Y axis 2 formatting isn't applied to tooltips

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#2060]
- axis shows $, but tooltip shows %. both should show $ format.

<img width="445" alt="screenshot 2017-01-26 17 47 52" src="https://cloud.githubusercontent.com/assets/130878/22357863/df2ca894-e3ef-11e6-9e94-1694e51b4d46.png">

**Comment by vera-liu** [comment]
https://github.com/airbnb/superset/pull/2068
