### ISSUE TITLE
[explore] [v1/v2] exploring a datasource throws error

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#2062]
- i can repro this on master, on staging, but not on the latest release.

<img width="1439" alt="screenshot 2017-01-26 23 01 50" src="https://cloud.githubusercontent.com/assets/130878/22363039/392d7c2a-e41c-11e6-96a9-7af4b42b4894.png">

<img width="1437" alt="screenshot 2017-01-26 23 21 40" src="https://cloud.githubusercontent.com/assets/130878/22363296/40948ff6-e41e-11e6-9ed9-770cfe85ca43.png">

<img width="1436" alt="screenshot 2017-01-26 23 08 55" src="https://cloud.githubusercontent.com/assets/130878/22363069/734a0914-e41c-11e6-98ee-f8ff37137111.png">

**Comment by bkyryliuk** [comment]
@ascott - it is a release blocker?

**Comment by ascott** [comment]
@bkyryliuk yes, we shouldn't push this bug to a release.

**Comment by ascott** [comment]
@mistercrunch do you think this could be related to your changes ?https://github.com/airbnb/superset/commit/e46ba2b4a4f5ccc9f584db0a3c7c1fbaf2b7fdf0#diff-3b162e04e00bcf00c104545b856a4105

**Comment by ascott** [comment]
this is happening on /expore/table/{id} as well as on Table View slices where there are no group by clauses. 

https://github.com/ascott/superset/blob/master/superset/viz.py#L202
`self.datasource.query(**query_obj)` is returning a failed query with this error.

```
'(sqlite3.OperationalError) near "FROM": syntax error [SQL: u"SELECT\\nFROM birth_names\\nWHERE ds >= \'2017-01-23 21:45:44.000000\'\\n  AND ds <= \'2017-01-30 21:45:44.000000\' LIMIT 50000\\nOFFSET 0"]'
```

the query it's trying to run is 
```
SELECT\nFROM birth_names\nWHERE ds >= '2017-01-23 21:45:44.000000'\n  AND ds <= '2017-01-30 21:45:44.000000' LIMIT 50000\nOFFSET 0
```

when it should be 
```
SELECT *\nFROM birth_names\nWHERE ds >= '2017-01-23 21:45:44.000000'\n  AND ds <= '2017-01-30 21:45:44.000000' LIMIT 50000\nOFFSET 0
```

this is as far as I've gotten with this one. @bkyryliuk @mistercrunch @vera-liu anyone have any ideas how to fix this? the backend is not my strong point.
