### ISSUE TITLE
[explorev2] mixed content Favstar request is sent over http

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/superset#2082]

**Comment by ascott** [comment]
i was able to repro this yesterday, and looked into the code, but everything looks like it should be working properly. i just tried to reproduce again on it's working as expected.

<img width="780" alt="screenshot 2017-02-02 15 45 41" src="https://cloud.githubusercontent.com/assets/130878/22573621/ae173c1e-e95e-11e6-9919-eb69deaec4a5.png">
