### ISSUE TITLE
npm install   err - git clone mapbox-gl-test-suite  failed

### ISSUE THREAD

**Issue by uptonking** [airbnb/superset#2087]
Make sure these boxes are checked before submitting your issue - thank you!

- [√] I have checked the superset logs for python stacktraces and included it here as text if any
- [√] I have reproduced the issue with at least the latest released version of superset
- [√] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4  master

### Expected results
`npm install` download required dependencies

### Actual results
failed to download mapbox-gl-test-suite, cause` mapbox-gl-test-suite` renamed to `mapbox-gl-js`
![npm_install_err](https://uptonking.github.io/assets/issues/superset/npm_install.png)
```  
npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/mapbox/mapbox-gl-test-suite.git /root/.npm/_git-remotes/git-github-com-mapbox-mapbox-gl-test-suite-git-ceba0a2e2e8e5860aa2550c53bb6083387d053d3-9786376a
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR! fatal: early EOF
npm ERR! fatal: index-pack failed

```   
### Steps to reproduce
cd $SUPERSET_HOME/superset/assets
npm install

node -v 6.9.1
npm -v 3.10.8

**Comment by xrmx** [comment]
What version of mapbox-gl-js is trying to install? please try to empty your npm cache. Maybe you have an older mapbox-gl-js version that still depends on mapbox-gl-test-suite.

**Comment by uptonking** [comment]
@xrmx after `npm cache clean`, I tried `npm install`, still the err.
```   
[root@*** assets]# npm install
npm ERR! tar.unpack unzip error /tmp/npm-9561-bd59ff0f/registry.npmjs.org/gl/-/gl-4.0.2.tgz
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates  
                             --mirror git://github.com/mapbox/mapbox-gl-test-suite.git   
                              /root/.npm/_git-remotes/git-github-com-mapbox-mapbox-gl-test-suite-git-ceba0a2e2e8e5860aa2550c53bb6083387d053d3-9786376a: 
                          Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-mapbox-mapbox-gl-test-suite-git-ceba0a2e2e8e5860aa2550c53bb6083387d053d3-9786376a'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/mapbox/mapbox-gl-test-suite.git /root/.npm/_git-remotes/git-github-com-mapbox-mapbox-gl-test-suite-git-ceba0a2e2e8e5860aa2550c53bb6083387d053d3-9786376a: 
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/mapbox/mapbox-gl-test-suite.git /root/.npm/_git-remotes/git-github-com-mapbox-mapbox-gl-test-suite-git-ceba0a2e2e8e5860aa2550c53bb6083387d053d3-9786376a: fatal: The remote end hung up unexpectedly
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/mapbox/mapbox-gl-test-suite.git /root/.npm/_git-remotes/git-github-com-mapbox-mapbox-gl-test-suite-git-ceba0a2e2e8e5860aa2550c53bb6083387d053d3-9786376a: fatal: early EOF
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/mapbox/mapbox-gl-test-suite.git /root/.npm/_git-remotes/git-github-com-mapbox-mapbox-gl-test-suite-git-ceba0a2e2e8e5860aa2550c53bb6083387d053d3-9786376a: fatal: index-pack failed
npm ERR! Linux 3.10.0-514.2.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/di/superset/superset/assets/npm-debug.log
```
------
in `package.json`. I can't find the dependency `mapbox-gl-test-suite`, I only find the ` "mapbox-gl": "^0.26.0"`

**Comment by xrmx** [comment]
@uptonking Have you also removed the local node_models? then could you please try to bump the release number to latest mapbox-gl and see if that works fine?

**Comment by uptonking** [comment]
@xrmx  `npm install` failed with the above message, so there is NO local `node_modules` folder.    
  
I changed the `"mapbox-gl": "^0.26.0"` to `"mapbox-gl": "^0.32.0"`, exec `npm cache clean` + `npm install` again, still the same err.  


[mapbox-gl-test-suite](https://github.com/mapbox/mapbox-gl-test-suite) was merged to `mapbox-gl-js` 23 days ago, maybe you didn't update your dependency.    

could you please check whether `/root/.npm/_git-remotes/git-github-com-mapbox-mapbox-gl-test-suite-**` exists in your local system?

**Comment by uptonking** [comment]
@xrmx please close the issue, I solve the problem myself.
I mannually exec `git clone`,and changed `git://` to `https://`, it works

**Comment by xrmx** [comment]
😒

**Comment by nikhil271995** [comment]
Facing a similar issue 

 LRN package.json osm-coverage@1.0.0 No repository field.
npm ERR! git rev-list -n1 bbox: fatal: ambiguous argument 'bbox': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 bbox: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 bbox: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 bbox: 
npm WARN deprecated turf-line-distance@1.0.2: Turf packages are now namespaced: please use @turf/line-distance instead
npm ERR! git rev-list -n1 bbox: fatal: ambiguous argument 'bbox': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 bbox: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 bbox: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 bbox: 
npm WARN deprecated tilebelt@1.0.1: This module is now under the @mapbox namespace: install @mapbox/tilebelt instead
npm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: Cloning into bare repository '/home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264'...
npm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: Permission denied (publickey).
npm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: 
npm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: and the repository exists.
npm WARN deprecated tile-reduce@3.1.1: This module is now under the @mapbox namespace: install @mapbox/tile-reduce instead

**Comment by rhunwicks** [comment]
I am having the same error installing Superset in a Docker container, and I am working around it with the following in the `Dockerfile`:

```
RUN git config --global url."https://github.com/".insteadOf git@github.com && \
    git config --global url."https://".insteadOf git:// && \
    npm install && \
    npm run build
```

See https://github.com/npm/npm/issues/5257#issuecomment-60441477 for the inspiration.
