### ISSUE TITLE
No data error is not propagated to the UI

### ISSUE THREAD

**Issue by bkyryliuk** [airbnb/superset#2109]
Query returns no data, js error is displayed instead of `no data` message

Link:
https://superset.d.musta.ch/superset/explore/table/2419/?goto_dash=false&slice_name=SLA+by+Locale&y_axis_zero=false&y_axis_label=&resample_fillmethod=&save_to_dashboard_id=771&line_interpolation=linear&add_to_dash=existing&show_legend=true&granularity_sqla=ds&x_axis_label=&rolling_type=None&datasource_type=table&viz_type=line&show_markers=false&since=1+year+ago&V2=true&time_compare=&json=false&until=now&collapsed_fieldsets=&resample_rule=&datasource_id=2419&period_ratio_type=growth&show_brush=false&y_axis_format=.3%25&x_axis_showminmax=true&metrics=avg__sla_perc_tier2&y_log_scale=false&timeseries_limit_metric=&slice_id=5698&where=sla_perc_tier2%21%3D0&resample_how=&groupby=locale&rich_tooltip=true&limit=50&x_axis_format=smart_date

**Comment by bkyryliuk** [comment]
@vera-liu @ascott  - could u please take a look?

**Comment by vera-liu** [comment]
I saw this one before, this was because we allow renderingFailed alert to override the previous one, will be solved on deprecate_v1
