### ISSUE TITLE
How to daemonize superset process

### ISSUE THREAD

**Issue by zhangjiajie023** [airbnb/superset#2123]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.0

### Expected results
Detaches the server from the controlling terminal and enters the background

### Actual results
can't realize running superset at backend

### Steps to reproduce
gunicorn is superset's server, I add the parameter `-D --daemon` in bin.superset.run_server(), but don't work.
Is there any other way s to  detaches the server from the controlling terminal and enters the background?

**Comment by zhangjiajie023** [comment]
I found that I can close the controlling terminal and the gunicorn still run as a daemon.
But there is no order to stop/restart superset, have to `kill` the superset process, right? Or exist other ways?

**Comment by xrmx** [comment]
What about letting your init system take care of superset?

**Comment by petroswork** [comment]
I've written a simple systemd service:
```
[Unit]
Description=Visualization platform by Airbnb

[Service]
Type=simple
ExecStart=/usr/local/bin/superset runserver -p 8088 -t 300
```

**Comment by xrmx** [comment]
@petroswork 👍

**Comment by zhangjiajie023** [comment]
@petroswork nice

**Comment by josebrwn** [comment]
Thanks for this. I had to make the following change on Azure:
`[Service]
Type=simple
User=username
ExecStart=/usr/local/bin/superset runserver -p 8088 -t 300`

**Comment by josebrwn** [comment]
Thanks for this. I had to make the following change on Azure:
`
[Service]
Type=simple
User=username
ExecStart=/usr/local/bin/superset runserver -p 8088 -t 300
`

**Comment by petroswork** [comment]
@josebrwn Mine was meant as a user service, i.e. appears in `systemctl --user`.

**Comment by fuzaro** [comment]
With few improvements works well for me.

#superset.service
###########
[Unit]
Description=Visualization platform by Airbnb
After=multi-user.target

[Service]
Type=simple
User=USER
ExecStart=/opt/superset/venv/bin/superset runserver 

[Install]
WantedBy=default.target

**Comment by mistercrunch** [comment]
For the record we use chef/runit at Airbnb. Hopefully we get to ship with some Linux distros that will take care of that eventualy :)

**Comment by pastarace** [comment]
Hi running the script from @fuzaro I'm getting `/bin/sh: 1: gunicorn: not found` message, that's due to the virtualenv is not active, I guess.. Any clue on how to solve?
Thanks

**Comment by liptanbiswas** [comment]
@pastarace change `/var/superset/superset/` with path to your Virtualenv. It's working I checked.

```
[Unit]
Description=Superset service 
After=network.target

[Service]
Type=simple
User=superset 
Group=superset 
Environment=PATH=/var/superset/superset/bin:$PATH
Environment=PYTHONPATH=/var/superset/superset:$PYTHONPATH
ExecStart=/var/superset/superset/bin/superset runserver

[Install]
WantedBy=multi-user.target
```

**Comment by mistercrunch** [comment]
Would recommend using a straight `gunicorn` in place of `superset runserver` to allow for more control and avoid an extra level of shelling

**Comment by nagaraju02** [comment]
@liptanbiswas can I use my own configuration file as well? Does this work?? please assist
like this:
[unit]
Description=SUPERSET systemd service script
After=network.target

[Service]
Type=simple
User=root
Environment=PATH=/opt/venv/bin:$PATH
Environment=PYTHONPATH=/opt/superset/superset_config.py:$PYTHONPATH
ExecStart=/opt/venv/bin/superset runserver
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by nagaraju02** [comment]
@liptanbiswas thanks a lot!
I will give a try.

**Comment by dominijk** [comment]
I've been trying to use [forever](https://www.npmjs.com/package/forever) to achieve something similar. Without success has anyone else got that working?

**Comment by jonathangueedes** [comment]
> Make sure these boxes are checked before submitting your issue - thank you!
> 
> * [x]  I have checked the superset logs for python stacktraces and included it here as text if any
> * [x]  I have reproduced the issue with at least the latest released version of superset
> * [x]  I have checked the issue tracker for the same issue and I haven't found one similar
> 
> ### Superset version
> 0.15.0
> 
> ### Expected results
> Detaches the server from the controlling terminal and enters the background
> 
> ### Actual results
> can't realize running superset at backend
> 
> ### Steps to reproduce
> gunicorn is superset's server, I add the parameter `-D --daemon` in bin.superset.run_server(), but don't work.
> Is there any other way s to detaches the server from the controlling terminal and enters the background?

Use the comando nohup before the command and put & in the final 

example:  nohup superset runserver -p 8088 &

**Comment by Aabhusan** [comment]
> I've written a simple systemd service:
> 
> ```
> [Unit]
> Description=Visualization platform by Airbnb
> 
> [Service]
> Type=simple
> ExecStart=/usr/local/bin/superset runserver -p 8088 -t 300
> ```

where to add this file and what is the case of the virtual environment??
any help is appreciated asap

**Comment by GOPIPACHA** [comment]
Can any one help me out what what in case supercet Is running on python virtual environment?

how we can get into python virtual environment and how we can setup this process

**Comment by Neel-rishabhsoft** [comment]
@GOPIPACHA The python environment can be specified in the .service file as "Environment=PYTHONPATH=/home/rspl_test/venv_s/bin:$PYTHONPATH" similar to what is done in above examples. The service file will automatically activate this environment

**Comment by jcalhinho** [comment]
the .service file must be in /etc/systemd/system
