### ISSUE TITLE
Cannot add all_datasource_access permission

### ISSUE THREAD

**Issue by clizzin** [airbnb/superset#2151]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4 (latest as of 2017-02-10)

### Expected results
When I try to add an `all_datasource_access` permission to a role, it should show up in the autocomplete, and I should be able to click it to add that permission.

### Actual results
The autocomplete says, "No matches found."

### Steps to reproduce
1. Go to http://localhost:8088/roles/edit/1 (which is the `Admin` role).
2. Type either `all_datasource_access` or `datasource` into the Permissions input field.
3. The autocomplete says, "No matches found."

**Comment by mistercrunch** [comment]
@bkyryliuk any idea what this may be related to?

**Comment by bkyryliuk** [comment]
@clizzin - could u run superset init and check if it appears ?
I couldn't replicate the issue

**Comment by clizzin** [comment]
Aha, you are correct!  I checked my terminal history, and it appears I forgot to run `superset init` when first setting everything up.  I'll close this issue now.  Sorry about that.

One potential improvement could be to wrap all setup into a single command that runs all the commands currently listed at http://airbnb.io/superset/installation.html#superset-installation-and-initialization (with the exception of `superset load_examples`—or maybe the single command could prompt the user to ask if they want to load the examples).
