### ISSUE TITLE
Superset Timeouts

### ISSUE THREAD

**Issue by chebu** [airbnb/superset#2157]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

### Expected results

When setting timeout on a command line ("superset runserver -t 300") the SQLLAB_TIMEOUT is not set. Only SUPERSET_WEBSERVER_TIMEOUT is set. I am not sure if this is a bug, but it would seem logical to set both variables since to allow queries to run for specified time. Otherwise, even though, gunicorn timeout is set at 300 the query will still time out at 30 sec as defined in config.py

**Comment by xrmx** [comment]
You should use a custom config and not augmenting the gunicorn options with other meanings. They are really two different things and thus should have two different knobs.

**Comment by chebu** [comment]
Perhaps you should clarify this in the FAQ under "Why are my queries timing out?"
 (http://airbnb.io/superset/faq.html#why-are-my-queries-timing-out) where it states that the query timeout can be resolved by starting the server with -t option (superset runserver -t 300). As a new user of Superbox it took me a while to find that the -t option did not set all the timeouts. 

PS: Also, when SQLLAB_TIMEOUT is reached I get  "(_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now")" as the error which is very misleading.

**Comment by Manju106** [comment]
@chebu can you update the link ?
