### ISSUE TITLE
 SQLLAB_TIMEOUT error message

### ISSUE THREAD

**Issue by chebu** [airbnb/superset#2158]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

### Expected results

When SQLLAB_TIMEOUT is reached I get "(_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now")" as the error which is very misleading.

**Comment by xrmx** [comment]
The error is from mysql and looks related to #2156 rather than a timeout issue

**Comment by chebu** [comment]
@xrmx This is not correct. Please test with a  simple query. You get an error because of timeout issue and not because of anything else.
