### ISSUE TITLE
Is there any solutions for windows?

### ISSUE THREAD

**Issue by jiar2046** [airbnb/superset#2160]
In company,there's only environment of windows. So,how can I find a solution to replace the gunicorn?
What does it mean to use the development web server for windows?

**Comment by xrmx** [comment]
Try the bash for windows

**Comment by jiar2046** [comment]
@xrmx  Thank u very much! But my system is Win7.....

**Comment by xrmx** [comment]
Install superset on a virtual machine then?

**Comment by jiar2046** [comment]
LOL~~ It may  be the most driect and good solution.
But I'm thinking whether there is another solution which can replace *gunicorn* in windows.
I'm a newbie.I'll appreciate u if you have any advice.
Maybe I should take time in reading *SourceCode* .

**Comment by xrmx** [comment]
superset is a wsgi app so any wsgi server that runs on windows would be good enough. You lose the *superset runserver* wrapper but that's it.

**Comment by jiar2046** [comment]
Thank you very much!
