### ISSUE TITLE
database如何添加hive数据源

### ISSUE THREAD

**Issue by gabrywu** [airbnb/superset#2170]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset-0.15.4

### Expected results
SQLAlchemy URI 配置成hive://hive@localhost:10000/default?auth=NOSASL
后点击Test Connection，测试通过

### Actual results
后点击Test Connection页面无反应

### Steps to reproduce
sources->databases-Add Database
SQLAlchemy URI 填写hive://hive@localhost:10000/default?auth=NOSASL
click Test Connection button

**Comment by asdf2014** [comment]
Can u show some logs in comment？And please speaking in English.

**Comment by gabrywu** [comment]
Haha, this is python version of the problem, I have solved

**Comment by asdf2014** [comment]
@gabrywu  Congratulations! Then u can close the issues now. BTW, which is the version of python in your environment now?

**Comment by gabrywu** [comment]
@asdf2014 python3

**Comment by yixinyiyide** [comment]
@gabrywu , 你好，我基于python3.5.3安装了superset，按照你提供的连接方式配置hive数据源，但“测试连接”弹出如下异常，这是什么原因啊？谢谢，我的微信13671721247。
ERROR:{"error":"Connection failed!\n\nThe error massage returned was:\nTSocket read 0 bytes"}

**Comment by gabrywu** [comment]
@yixinyiyide 额，python3好像是有问题的，你可以试试python2.7的。欢迎加微信 HelloGrape

**Comment by mistercrunch** [comment]
Can y'all write in english on this repo please?

**Comment by hungrytortoise** [comment]
i meet the same problem,my SQLAlchemy URI is: hive://hive@localhost:10000/database?auth=NOSASL
when i click test connect btn, it does not work.
python version is 2.7.5

**Comment by yixinyiyide** [comment]
@hungrytortoise , you can try hive://hive@localhost:10000/database , and yum -y install cyrus-sasl-plain.

**Comment by iclouding** [comment]
@yixinyiyide 我也遇到了你的问题，python版本是2.7.9，填写的url是`hive://hive@172.31.3.123:10000/default?auth=NOSASL`，但是报错：`ERROR:{"error":"Connection failed!\n\nThe error massage returned was:\nTSocket read 0 bytes"}`，求助是什么原因？

**Comment by asdf2014** [comment]
检查下，是不是hive配置的有问题哇。另外，社区里面最好用英文吧 (笑哭)

**Comment by iclouding** [comment]
@asdf2014 没啥问题啊，可否加个QQ(605612253)，向您请教一番。

**Comment by asdf2014** [comment]
Sure.

**Comment by danix9009** [comment]
Has this problem solved ?I faced the same problem when to build sparksql connector in superset.
I read comments in this page ,but there found no answer for me.
