### ISSUE TITLE
Hive connection 

### ISSUE THREAD

**Issue by superibra** [airbnb/superset#2174]
I'm new at superset
When i want to connect to hive database that shows me this error
TTransportException(message="Could not start SASL: b'Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found'", type=1"
i'm blocked for 6days in this error
did you know how to solve this error ?
![capture](https://cloud.githubusercontent.com/assets/11506804/22935574/4276f368-f2d3-11e6-84df-2720d50870b8.JPG)

**Comment by xrmx** [comment]
Googling for the error in this 6 days may have helped:
https://github.com/cloudera/impyla/issues/149#issuecomment-227519194

That's an issue with the connector, not a superset issue.

**Comment by superibra** [comment]
Before i wrote this post. I followed the answer in the 149 post with attention but it remains the same error. that's why i will see if i can find a solution to this issue at pyhive forum
Thank you for answering

**Comment by hungrytortoise** [comment]
Has the problem been solved?

**Comment by hungrytortoise** [comment]
@superibra

**Comment by mistercrunch** [comment]
You may want to try `auth=plain` or `auth=PLAIN`

**Comment by hungrytortoise** [comment]
i have done what you say,but meet a new error.
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nOnly NONE & NOSASL authentication are supported, got PLAIN"}
my SQLAlchemy URI is "hive://hive@xxxxxx:10000/xxx_idmapping?auth=PLAIN"
how to fix it ?
tks

**Comment by mistercrunch** [comment]
Did you try NONE?

**Comment by hungrytortoise** [comment]
i have tried it,but meet the following issue.
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCould not start SASL: Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found"}

**Comment by mistercrunch** [comment]
Here's the related pyhive logic:
https://github.com/dropbox/PyHive/blob/59746c31f1b16c96e90a5dd2cb00e23b30d3caea/pyhive/hive.py#L91

**Comment by yixinyiyide** [comment]
@superibra @hungrytortoise @mistercrunch , I guess the pyhive package only support python2.7, not support python 3.

**https://pypi.python.org/pypi/PyHive/0.2.1**
Requirements

Install using

pip install pyhive[hive] for the Hive interface and
pip install pyhive[presto] for the Presto interface.
PyHive works with

Python 2.7
For Presto: Presto install
For Hive: HiveServer2 daemon
There’s also a third party Conda package.

**Comment by sungjuly** [comment]
That's true, let's wait a couple of days, PyHive is trying to support Python3 since data scientist guy from Airbnb contributes for that, I expect new version will be rolled out soon!
* https://github.com/dropbox/PyHive/commit/e3ecad1e41ebe1f5484886649228a483390d5969

**Comment by maygupta** [comment]
@superibra @hungrytortoise Were you able to solve this issue ?

**Comment by SpyderRivera** [comment]
Any update on this? Did you get it working? Did you try python 2.7?

**Comment by sunriseLe** [comment]
> @superibra @hungrytortoise @mistercrunch , I guess the pyhive package only support python2.7, not support python 3.
> 
> **https://pypi.python.org/pypi/PyHive/0.2.1**
> Requirements
> 
> Install using
> 
> pip install pyhive[hive] for the Hive interface and
> pip install pyhive[presto] for the Presto interface.
> PyHive works with
> 
> Python 2.7
> For Presto: Presto install
> For Hive: HiveServer2 daemon
> There’s also a third party Conda package.

after insatll pyhive[presto], I can access presto, no error like that: 
Invalid driver: presto
