### ISSUE TITLE
"superset db upgrade" hang up when I setup the superset

### ISSUE THREAD

**Issue by wenma** [airbnb/superset#2178]
I first use the superset, and don't know what happened when I run the command "superset db upgrade".  the command hang up!

the console log show:  
```
......
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 4e6a06bad7a8, Init
-->       # hangs here ~

```

And,  I found the database table behave something incorrect.  when I run this sql, also hang up
```
select * from ab_user;     # also hang up
```

how can I solve this situation ?

**Comment by xrmx** [comment]
Dup of #1260
