### ISSUE TITLE
Authorization on data sources / tables

### ISSUE THREAD

**Issue by markrey** [airbnb/superset#2192]
Hi Everyone,

Is it possible to create authorization on Datasources? (For compliance reasons )

I ( as an devops! ) want to manage only one instance of Superset and create 3 data sources ( one for web app sessions, second for finance and third for server management ).

I want to create authorization on each type of source so that only LDAP/other users can see specific ones. Is it possible to do it?

Essentially creating multiuser authorized system.

Thanks

**Comment by xrmx** [comment]
If you are new to superset you may start by reading the manual:
http://airbnb.io/superset/security.html#managing-gamma-per-data-source-access

**Comment by markrey** [comment]
Thank you @xrmx !
