### ISSUE TITLE
How long we can install superset 0.16.0 using pip?

### ISSUE THREAD

**Issue by asdf2014** [airbnb/superset#2216]
How long we can install superset 0.16.0 using pip?

The network without VPN in China is so terrible, we cannot build `supereset` on local...
![image](https://cloud.githubusercontent.com/assets/8108788/23195372/fb5f873a-f8ed-11e6-939b-d08354cfd19c.png)

**Comment by xiaoidea** [comment]
you can choose a pypi mirror in China， like Tsinghua, Douban, etc.
Tsinghua: https://pypi.tuna.tsinghua.edu.cn/simple/

**Comment by asdf2014** [comment]
@xiaoidea Thank u! Actually, i am already changed the `pip` mirror.

pip install -i https://pypi.tuna.tsinghua.edu.cn/simple superset==0.16.0
```
Collecting superset==0.16.0
  Could not find a version that satisfies the requirement superset==0.16.0 (from versions: 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.3, 0.15.4)
No matching distribution found for superset==0.16.0
```

**Comment by xiaoidea** [comment]
seems that the pypi doesn't contain version 0.16.0.
I download the source code of 0.16.0 and setup it manually, but it's also a little time cosuming when doing the npm install. I use alibaba's npm mirror and it costs me about 30 minutes to download the dependencies.

**Comment by asdf2014** [comment]
Great! What is alibaba's npm mirror, can you share that? I installed `superset 0.16.0` with it's resource code :)
![image](https://cloud.githubusercontent.com/assets/8108788/23244543/ffcb96aa-f9c0-11e6-843c-2e2bbc6bb085.png)

**Comment by xiaoidea** [comment]
```
npm install -g cnpm --registry=https://registry.npm.taobao.org
cnpm install
npm run prod
```

**Comment by asdf2014** [comment]
@xiaoidea It works! Thx a lot :D

**Comment by fangyeqing** [comment]
@xiaoidea it doesn't work for me，and I don't know why

`
root@ubuntu:~/PycharmProjects/superset_2017/superset/assets# npm run prod

> superset@0.17.0 prod /root/PycharmProjects/superset_2017/superset/assets
> NODE_ENV=production node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js -p --colors --progress

 78% additional chunk assetsKilled

npm ERR! Linux 4.4.0-63-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prod"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! superset@0.17.0 prod: `NODE_ENV=production node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js -p --colors --progress`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the superset@0.17.0 prod script 'NODE_ENV=production node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js -p --colors --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the superset package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js -p --colors --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs superset
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls superset
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PycharmProjects/superset_2017/superset/assets/npm-debug.log

`

**Comment by tangshan-risk** [comment]
I have a similar trouble with Exit status 2:
ERROR in ./~/_css-loader@0.28.3@css-loader!./~/_less-loader@4.0.3@less-loader/dist!./stylesheets/react-select/select.less
Module build failed: 

        &:hover {
                box-shadow: @select-input-hover-box-shadow;
            ^
Variable @select-input-hover-box-shadow is undefined
      in /Users/Alex/Desktop/superset/superset/assets/node_modules/_react-select@1.0.0-rc.5@react-select/less/control.less (line 64, column 14)
 @ ./stylesheets/react-select/select.less 4:14-162
 @ ./javascripts/css-theme.js

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! superset@0.17.6 build: `NODE_ENV=production webpack --colors --progress`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the superset@0.17.6 build script 'NODE_ENV=production webpack --colors --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the superset package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack --colors --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs superset
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls superset
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Alex/Desktop/superset/superset/assets/npm-debug.log
