### ISSUE TITLE
seems that table timestamp format does not work

### ISSUE THREAD

**Issue by xiaoidea** [airbnb/superset#2219]
### Superset version
0.16.0

### Detail
table view should shows the corresponding  date format in the '__timestamp' column, but no matter which format has been chosen, the '__timestamp' column always shows something like '2017-02-15T15:00:00'
![pic](https://cloud.githubusercontent.com/assets/5398523/23202434/e400d406-f918-11e6-8bba-5617f14230c3.PNG)

**Comment by xiaoidea** [comment]
besides:
I have set 'is_timeseries = False' to'is_timeseries = True' in viz.py/Class TableViz to show the timestamp column in table view.
because I found that the Superset will not show the timestamp column in the table view, but the old Caravel not.
So, is it means that the "Table Timestamp Format" Option in Table View is useless cause the timestamp would never appear in the table?

**Comment by jroblak** [comment]
I'm seeing a similar issue with Postgres. I can't seem to use any Date-based charts, as they all return the same `{"error": "__timestamp"}` error.

**Comment by aleh-arol** [comment]
Issue was not resolved by the changes were made. In particular issue is about "Table Timestamp Format " which is on Customize tab of the Table viz control panel (and not about Time Grain). Expected that format selected in the Table Timestamp Format dropdown will be applied to the main dttm column values. Currently it is not.
Superset version is ebb7fbc5f024379361f301a86b770e0cc1a932cd

**Comment by Jclevinson** [comment]
Still experiencing this issue, has there been a fix yet?
