### ISSUE TITLE
Maintain changelog file

### ISSUE THREAD

**Issue by dataforger** [airbnb/superset#2220]
Make sure these boxes are checked before submitting your issue - thank you!

- [.] I have checked the superset logs for python stacktraces and included it here as text if any
- [.] I have reproduced the issue with at least the latest released version of superset
- [.] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
CHANGELOG.md should be updated as part of release

### Actual results
CHANGELOG.md is not being maintained

### Steps to reproduce
Open the CHANGELOG.md, the last release listed is 0.15.1, current release is 0.16.0

**Comment by mistercrunch** [comment]
I usually do it but skipped it on a few releases. Its up to date now

**Comment by bryceschober** [comment]
It has fallen behind again...
