### ISSUE TITLE
[sql-lab] results table ui bug

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#2231]
make results action buttons and search input field fixed even if results table needs to scroll left/right.

- move the `overflow:auto` rule from the parent div to the table container div.

fixed:
![sql-table-scrolling-fixed](https://cloud.githubusercontent.com/assets/130878/23250181/cceeb4e2-f95c-11e6-8eee-362fa4474762.gif)

currently:
![sql-table-scrolling](https://cloud.githubusercontent.com/assets/130878/23250180/cced7708-f95c-11e6-919b-60a227a82682.gif)

**Comment by jfeng15** [comment]
thanks for the quick turnaround @ascott !
