### ISSUE TITLE
 How can I set the language to Chinese?

### ISSUE THREAD

**Issue by sundaytok** [airbnb/superset#2242]
I have tried to modify here and restarted the server, but still in English。
![image](https://cloud.githubusercontent.com/assets/3404594/23294832/5837bfca-faa8-11e6-95d3-ef49a8fa91c5.png)

**Comment by xrmx** [comment]
Does zh_CN work?

**Comment by sundaytok** [comment]
@xrmx I know why I can set Chinese,change the conf.py like that and restart the server.
![image](https://cloud.githubusercontent.com/assets/3404594/23444329/5b166910-fe6f-11e6-90e1-3483348b5189.png)
you can close the issuse,thank you!

**Comment by 1c7** [comment]
https://github.com/apache/superset/discussions/18806#discussioncomment-2202576
