### ISSUE TITLE
Support and Configuration for Druid 0.9.x

### ISSUE THREAD

**Issue by denisvlah** [airbnb/superset#2249]
I have Druid 0.9.2 installed and I want to configure superset to query existing druid installation.

I have configured everything successfully according to docs  from 
http://airbnb.io/superset/druid.html

I can see all Druid datasources in superset but when I do any query it says that no data is returned when there are a lot of data matching the filter.

I have seen that the superset is tested against Druid 0.8.x from docs:
http://airbnb.io/superset/druid.html

Does anyone know how all caveats/fixes of using latest Druid version with the superset?

**Comment by mistercrunch** [comment]
Can you copy/paste the json Druid query and run it against your cluster and confirm that it does return data?

**Comment by denisvlah** [comment]
Yes Druid does return date on queries.

I have tried to query data with Metabase and Impy Pivot tools and they were working correctly.

**Comment by nishantmonu51** [comment]
@denisvlah: which version of superset are you using ? 
fwiw, we have been using superset 0.15.2 with druid 0.9.2 without any issues.

**Comment by denisvlah** [comment]
I have installed the latest version of superset from PyPi
and it was 0.15.4
I have installed superset 0.15.1 and it can see data from current Druid installation.

I am ok to work with suerset 0.15.1 for no. 

Closing this issue

**Comment by mistercrunch** [comment]
So the same query between 0.15.1 and 0.15.4 returns different results (no data on 0.15.4) for you? Can you diff the two queries so we can get to the bottom of this?

**Comment by denisvlah** [comment]
On the superset 0.15.4 there was some internal error and it didn't returned any data for the query.
On the UI I have seen message **No data** available.
I can't say what was the issue internally because I am not a python dev and I don't have skills to debug python code.
Regarding superset version 0.15.3 - I didn't tried this version.
And regarding superset version 0.15.2 - it is not available in the PyPI repository.

**Comment by mistercrunch** [comment]
Ok, this should be fixed in 1.16.x

**Comment by deyani27** [comment]
I am trying to connect Druid 0.9.2 with superset 0.15.1 and I can see the datasources, but when I click on the datasources, I am getting the below error:

2017-03-08 00:37:50,210:ERROR:root:Query component: merge is not valid for query type: segmentMetadata.The list of valid components is: 
 ['datasource', 'intervals', 'context']
