### ISSUE TITLE
datasource/schema permission issues

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#2253]
- GET /superset/datasources/ is throwing 401 for users who are not admins
- 401/eternally spinning schemas drop down in sqllab 

![image](https://cloud.githubusercontent.com/assets/130878/23320064/1739839c-fa8e-11e6-82b0-c3202bdcbf05.png)

**Comment by DaimonPl** [comment]
Was it fixed? I'm having same problem on superset 0.18.4

**Comment by DaimonPl** [comment]
@graceguo-supercat any info?

**Comment by DaimonPl** [comment]
@mistercrunch maybe you know something? :)
