### ISSUE TITLE
[explore] druid slice errors

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#2271]
https://airbnb.quip.com/sacgAluVmKAQ

**Comment by nishantmonu51** [comment]
@ascott can you add some more description or SNAPSHOTS for the issue. 
The link points to airbnb dashboard which everyone might not have access to.

**Comment by vera-liu** [comment]
this was caused by filters missing operator 'not in', solved by adding back filter operators

**Comment by vera-liu** [comment]
Fixed with https://github.com/airbnb/superset/pull/2288
