### ISSUE TITLE
Bar chart can't render correctly when two(or more) series are selected

### ISSUE THREAD

**Issue by HugoPu** [airbnb/superset#2281]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.15.2
### Expected results

Bar chart can show correctly
### Actual results

error
### Steps to reproduce
select two or more series in the DistributionBarViz, in these two series' values, they contain Chinese, since the following code(in get_data method) will encode Chinese to utf8 strings, which contains two '\' in each word, NVD.js can only recognize one '\', the bar chart can't render correctly.
d = {
                "key": series_title,
                "values": [
                    {'x': str(i), 'y': v}
                    for i, v in ys.iteritems()]
            }

after I replace the above code with the blow's, the chart works well.

d = {
                    "key": series_title,
                    "values": [
                        {'x': ", ".join(i), 'y': v} if isinstance(i, tuple) else {'x': str(i), 'y': v}
                        for i,v in ys.iteritems()
                    ]
                }

**Comment by mistercrunch** [comment]
oh I just fixed that, the fix will make the next release
