### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

### ISSUE THREAD

**Issue by asdf2014** [airbnb/superset#2282]
superset==0.15.4

UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

![image](https://cloud.githubusercontent.com/assets/8108788/23357070/2f3de394-fd17-11e6-8e41-3f9f01b6f4f9.png)

**Comment by mistercrunch** [comment]
it would help to have info about your backend and python version

**Comment by zhangjiajie023** [comment]
@mistercrunch If use mysql as backend, should `create database db character set utf8` and add `charset=utf8` in sqlalchemy_url. 

But use the sqlalchemy_url not containing `charset=utf8` to connect mysql once (of  course failed), then use the right sqlalchemy_url with `charset=utf8`, occurs the same error, need to re-create the database and re-generate superset's metadata.

 Does the  sqlalchemy_url without `charset=utf8` modify some properties of db? But the info of db showed by `status` don't have changed.

**Comment by asdf2014** [comment]
@zhangjiajie023 @mistercrunch I meet the same situation again when i upgrade `superset` from `v0.15.4` into `v0.17.0` using mysql as a metadata store.
```
superset db upgrade
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 1296d28ec131 -> f18570e03440, Add index on the result key to the query table.
INFO  [alembic.runtime.migration] Running upgrade f18570e03440 -> bcf3126872fc, Add keyvalue table
INFO  [alembic.runtime.migration] Running upgrade f18570e03440 -> db0c65b146bd, update_slice_model_json
最近一小时 Write OPS error: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
// ...
```

**Comment by asdf2014** [comment]
I think this could be the reason...

![image](https://cloud.githubusercontent.com/assets/8108788/23645065/3a813d62-0345-11e7-865e-c79fdb24edf8.png)

**Comment by zhangjiajie023** [comment]
@asdf2014 I changed to python3. If python2, try to add `# -*- coding: utf-8 -*- `  in the first line of x.py

**Comment by asdf2014** [comment]
@zhangjiajie023 You mean like this?

![image](https://cloud.githubusercontent.com/assets/8108788/23885555/e17a86f0-08ae-11e7-8586-76586c78933d.png)

**Comment by asdf2014** [comment]
You are so great! Thx a lot.
![image](https://cloud.githubusercontent.com/assets/8108788/23885607/4619b7de-08af-11e7-8a46-8759e42e0c1c.png)
