### ISSUE TITLE
[sql-lab] if there is no schema for a db, table search does not work

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#2304]
if there is no schema for a database, table search does not work

![screenshot 2017-03-01 00 03 02](https://cloud.githubusercontent.com/assets/130878/23450944/87af206e-fe12-11e6-9a67-84d252598a85.png)

if there is no schema for a db, we should show all tables.

**Comment by mistercrunch** [comment]
I thought @bkyryliuk recently fixed that

**Comment by ascott** [comment]
i think it may be that it is just really slow if no schema is selected.
