### ISSUE TITLE
Character encoding does not support chinese character in Email function

### ISSUE THREAD

**Issue by asdf2014** [airbnb/superset#2308]
superset==0.15.4

Character encoding does not support chinese character in Email function...

![image](https://cloud.githubusercontent.com/assets/8108788/23454776/50b0dd14-fea8-11e6-8472-6aa3ec5406fa.png)

**Comment by SalehHindi** [comment]
@asdf2014 I am not sure what is wrong. What do you expect to see in that screenshot?
