### ISSUE TITLE
There is no SQL in the query window of the slices menu

### ISSUE THREAD

**Issue by johnfanyong** [airbnb/superset#2309]
Make sure these boxes are checked before submitting your issue - thank you!

### Superset version
version: "0.15.4"

### Steps to reproduce
<img width="1164" alt="error" src="https://cloud.githubusercontent.com/assets/9602639/23454929/dba4f662-fea8-11e6-88d8-f3ddb896a8f0.png">

**Comment by ascott** [comment]
this is fixed in the latest release.
