### ISSUE TITLE
Allow user to decide when to apply "Filter slice" to a dashboard

### ISSUE THREAD

**Issue by Csnigs** [airbnb/superset#2310]
Hi all,

We've been using the filter slice for a while (and liking it!).
My main issue is that anytime I change a field of the filter, each slice of the dashboard instantly refresh itself.
The problem is that, when you have many field to select for your desired results, it will trigger a ton of unnecessary requests (which could be massive and entirely freeze Druid for a few minutes).
We are working around this by filtering on the last minute to make all of those requests tiny, but a simple APPLY FILTER button would make the whole thing a lot more natural.

**Comment by mistercrunch** [comment]
Sounds reasonable, the FilterBox widget could make that optional with a checkbox control "Instataneous". If checked (default) same as current behavior, if unchecked, a new "Apply" button is exposed and needs to be clicked.

**Comment by mistercrunch** [comment]
![img](http://g.recordit.co/iF9TQBMrIe.gif)
https://github.com/airbnb/superset/pull/2338
