### ISSUE TITLE
No new versions have been pushed to PyPI since 0.15.4

### ISSUE THREAD

**Issue by unixninja92** [airbnb/superset#2311]
No new versions of superset are in PyPI since 0.15.4 even though there have been releases on github for 0.16.0, 0.16.1, and 0.17.0. I would like to be able to continue to use pip to install superset. 
https://pypi.python.org/pypi/superset

**Comment by mistercrunch** [comment]
I'm pushing 0.17.0 today to pypi today.

**Comment by mistercrunch** [comment]
Make sure to read the CHANGELOG before upgrading.

**Comment by mistercrunch** [comment]
0.17 is out
