### ISSUE TITLE
Table filter not filtering

### ISSUE THREAD

**Issue by jr-minnaar** [airbnb/superset#2327]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset
Version 0.17.0

### Expected results
Clicking on table row filters the graphs in the dashboard

### Actual results
The filter is applied but includes HTML formatting tags, so graphs show "No data"

### Steps to reproduce
Add table with "Table Filter" checkbox selected and any graph to a dashboard. 
Select a row and click on "Active dashboard filters"

![image](https://cloud.githubusercontent.com/assets/8666131/23544569/2f8e4082-0000-11e7-8b1a-1303a23646b4.png)

**Comment by sipra24** [comment]
Can we add filter to time series bars . Upon clicking the bars it would show the table view / slice.
