### ISSUE TITLE
How to use github oauth?

### ISSUE THREAD

**Issue by rluisr** [airbnb/superset#2340]
Hi guys.

I want to enable GitHub Auth.
Duplicated issue #755 but I don't know how to enable.

I installed superset using this playbook.
https://github.com/rluisr/playbook-for-superset/blob/master/main.yml

**Comment by xrmx** [comment]
@rluisr auth is handled by flask app builder, you should refer to its documentation.

BTW if you know this has been already discussed why open a new bug?

**Comment by Aung-Myint-Thein** [comment]
Hi I managed to set it up and wrote a post here.

https://medium.com/@aungmt/superset-with-google-oauth-3ba7a1c1f459

**Comment by xrmx** [comment]
@Aung-Myint-Thein what about adding an example to superset documentation?

**Comment by Aung-Myint-Thein** [comment]
@xrmx Happy to contribute if you all think this is good :D ..
