### ISSUE TITLE
Metric D3Format doesn't work in the dashboard

### ISSUE THREAD

**Issue by Georgepentaho** [airbnb/superset#2358]
- [ N] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y] I have reproduced the issue with at least the latest released version of superset
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.0
### Expected results
On the dashboard, if I set the D3Format for one metric, this metric should display follow the setting

### Actual results
The metric display default

### Steps to reproduce
1. I set the D3Format.
![image](https://cloud.githubusercontent.com/assets/19921144/23644255/66698ffa-0341-11e7-9f53-1ca493e897af.png)
2.It's display OK in explore model:
![image](https://cloud.githubusercontent.com/assets/19921144/23644307/a7704386-0341-11e7-9744-68c9468a3872.png)
3.In the dashboard,the metric display not ok.
![image](https://cloud.githubusercontent.com/assets/19921144/23644336/dba33898-0341-11e7-8c58-04e7ccef996c.png)

**Comment by mistercrunch** [comment]
https://github.com/airbnb/superset/pull/2598
