### ISSUE TITLE
Failed to add datasource: Postgresql

### ISSUE THREAD

**Issue by huhuhong** [airbnb/superset#2363]
Sample postgresql connection url:
```
postgresql://postgres:iconnect360@10.32.8.109:5433/testdb
```

Error Message
```
{"error": "Connection failed!\n\nThe error message returned was:\n'NoneType' object has no attribute 'get'"}
```

### Superset version
0.17.0

Step
1. Login > Sources > Database > Test Connection

### Python Version
2.7

**Comment by evinhas** [comment]
I have a similar issue, also using python 2.7 in a red hat 7.2 VM.

I did the same steps (sources > database > test connection) after writing a postgres+psycopg2 URL ("`postgresql+psycopg2://`").

But in my case, the error is different:

`libpq-cf361c55.so.5.8: cannot open shared object file: no such file or directory`

I was trying to identify the library "`libpq-cf361c55.so.5.8`", but it seems that it doesn't exist (according to Google).

So I was not able to use a Postgresql source in Superset.

Please, any idea about what could be happening?

Thanks in advance.

**Comment by Germanaz0** [comment]
I have this error too, any suggestion of what can be ?
