### ISSUE TITLE
Windows installation issue

### ISSUE THREAD

**Issue by Mohan-Vel** [airbnb/superset#2365]
I m trying to install Superset in Windows 7 and i have completed up to creating admin successfully. I am failing in running the "superset db upgrade", "superset load_examples" and "superset runserver" . Any help

**Comment by lostwing** [comment]
Hi,I,m meet the same problem,when I run the superset db upgrade,it said it is not internal command，how do you solve it ?

**Comment by hengaini2055** [comment]
you can use the following command:
python .\venv\Scripts\superset load_examples
