### ISSUE TITLE
[filter_box] time filters don't seem to apply in some cases

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/superset#2372]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by shunjili** [comment]
do we have any updates on this issue?
