### ISSUE TITLE
d3.format error

### ISSUE THREAD

**Issue by AndyPau** [airbnb/superset#2374]
I create a slice, following is the format .
￼
<img width="598" alt="wx20170309-143429 2x" src="https://cloud.githubusercontent.com/assets/13029872/23738812/1a612ea6-04d6-11e7-8664-cfb9ab280645.png">

when i add it to a dashboard, The format does not take effect. 
<img width="1080" alt="wx20170309-143713-1 2x" src="https://cloud.githubusercontent.com/assets/13029872/23738775/ed0a2b4c-04d5-11e7-9498-5f323c2df56f.png">

**Comment by ascott** [comment]
dupe of https://github.com/airbnb/superset/issues/2358
