### ISSUE TITLE
Superset service start stuck at "CssTemplateAsyncModelView on menu"

### ISSUE THREAD

**Issue by csankaraiah** [airbnb/superset#2390]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by jnawras** [comment]
You're not providing enough information on what your expected results are. 

If I understand correctly, you ran the superset server and now you want to proceed? if so, go ahead and setup your admin login using "superset superset-init" command. Please follow the instructions on the README file if this doesn't resolve.
