### ISSUE TITLE
index.html: <img src="{{ url_for("static", filename="img/dash.png") }}">

### ISSUE THREAD

**Issue by zhangjiajie023** [airbnb/superset#2400]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Steps to reproduce

in superset/index.html there are multiple statements like  this:
`<img src="{{ url_for("static", filename="img/dash.png") }}">`
I am not familiar with` html`, but I think the nested quotes is wrong, right?

**Comment by xrmx** [comment]
That's a template, is the rendered html broken? If not, not an issue.
