### ISSUE TITLE
[vis]x bound causes problem when there are only two x datapoints

### ISSUE THREAD

**Issue by yileic** [airbnb/superset#2413]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
latest master branch

### Expected results
normal look in line chart 

### Actual results
everything squeezed together in line chart

### Steps to reproduce
Choose a time interval that contains two or one x data points. If 'X bound' is not selected, line chart looks normal. If "X bound" is selected, everything squeezed together. Please see attached images.
<img width="1381" alt="x bound not checked" src="https://cloud.githubusercontent.com/assets/10532596/23928790/1c2041fc-08df-11e7-9ab1-5cd2e2208bab.png">
<img width="1379" alt="x bound checked" src="https://cloud.githubusercontent.com/assets/10532596/23928794/238d2d56-08df-11e7-9de2-866863cae9a8.png">

**Comment by xrmx** [comment]
Please reproduce with 0.17.0 or even better latest master

**Comment by yileic** [comment]
reproduced with the latest master branch. thank you so much for your attention.

**Comment by yileic** [comment]
btw, is 'airbnb_prod.0.15.5.0' the latest or '0.17.0' the latest. Is it safe to use those without 'prod' in the tag? Thank you!

**Comment by yileic** [comment]
#2427
