### ISSUE TITLE
Cannot draw graph with nvd3. Uncaught TypeError: ue.watchTransition is not a function

### ISSUE THREAD

**Issue by ErosZZH** [airbnb/superset#2421]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y] I have checked the superset logs for python stacktraces and included it here as text if any
- [Y] I have reproduced the issue with at least the latest released version of superset
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Any version on my machine includes airbnb_prod.0.15.5.0

### Expected results
After loading examples, in Slices tab, superset should display any example slice like birth_names normally.

### Actual results
Cannot display any graph drawn by nvd3

### Steps to reproduce
superset load_examples
superset runserver
login, click slices tab, click birth_names

Below is my stack trace on browser:
`Uncaught TypeError: ue.watchTransition is not a function
    at SVGGElement.<anonymous> (explorev2.0.17.1rc2.entry.js:90)
    at explorev2.0.17.1rc2.entry.js:102
    at $ (explorev2.0.17.1rc2.entry.js:100)
    at Array.La.each (explorev2.0.17.1rc2.entry.js:102)
    at Array.o (explorev2.0.17.1rc2.entry.js:90)
    at Array.La.call (explorev2.0.17.1rc2.entry.js:102)
    at SVGGElement.<anonymous> (explorev2.0.17.1rc2.entry.js:87)
    at explorev2.0.17.1rc2.entry.js:102
    at $ (explorev2.0.17.1rc2.entry.js:100)
    at Array.La.each (explorev2.0.17.1rc2.entry.js:102)`

I found the exception was thrown by line 381 of nvd3_vis.js airbnb_prod.0.15.5.0. But I can't fix it.

Below is info of my machine:
macos 10.12.1
chrome 56.0.2924.87 (64-bit) The bug happens on any browser of my machine.
d3 3.5.17
nvd3 1.8.5

It also happened on other graph, I created using nvd3 like pie chart etc.

**Comment by xrmx** [comment]
Possibly this has been fixed in a later version?

**Comment by ErosZZH** [comment]
Using pip install -r requirements.txt instead of python setup.py install, The error never happened.
