### ISSUE TITLE
[vis] make line charts render properly at small sizes

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#2427]
chart and axis are distorted/broken if the slice container is too small.

![screenshot 2017-03-16 13 45 09](https://cloud.githubusercontent.com/assets/130878/24017838/d94a43c0-0a4e-11e7-800d-e0f1df081650.png)

**Comment by hawkett** [comment]
Additional note: the broken state is dependent on the screen resolution - e.g. on my laptop, they are broken as in OP, but if I connect a larger screen, they work fine - without needing refresh. In general screen resolution should not affect correctly rendering, as I could build a dashboard that looks great to me, and then send it someone else who will be unable to view it.

**Comment by yileic** [comment]
#2413
