### ISSUE TITLE
'dict' object does not support indexing when adding redshift database

### ISSUE THREAD

**Issue by nicokras** [airbnb/superset#2428]
Trying to add a redshift database, I get the **'dict' object does not support indexing** error. What could be happening?

Superset version 0.17.1
Python version: 2.7
Ubuntu server. 

Thanks

**Comment by xrmx** [comment]
Please use the template issue and report all the needed informations like a stack trace.

**Comment by ndeslandes** [comment]
@mistercrunch 

I have the same issue. No stacktrace in the log.

`'dict' object does not support indexing` when clicking Save  in the /databaseview/add page with a redshift config

Database : db_name
SQLAlchemy URI : redshift+psycopg2://user:password@redhsit_host:5439/db_name
Cache Timeout : <empty>
Extra : {
    "metadata_params": {},
    "engine_params": {
          "connect_args":{
              "sslmode": "prefer"
        }
     }
}

**Comment by alexdebrie** [comment]
I had the same issue. To fix, change your SQL Alchemy URI from `redshift+psycopg2://...` to `postgresql+psycopg2://...`

Solution found [here](https://github.com/airbnb/superset/issues/2364).

**Comment by nicokras** [comment]
@alexdebrie That worked for me. Thanks for your help!

**Comment by xrmx** [comment]
So documentation is wrong? If so anyone care to do a patch please? http://airbnb.io/superset/installation.html#database-dependencies

**Comment by alexdebrie** [comment]
See [2447](https://github.com/airbnb/superset/pull/2447).

**Comment by mistercrunch** [comment]
Merged, closing
