### ISSUE TITLE
No file superset/static/assets/package.json'

### ISSUE THREAD

**Issue by zjj796** [airbnb/superset#2444]
python2.7.5
centos

$sudo fabmanager create-admin --app superset
username..
user first name..
user last name..
email..
password..
password..

/usr/lib/python2.7/site-packages/flask_migrate/__init__.py:4: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  from flask.ext.script import Manager
Was unable to import superset Error: [Errno 2] No such file or directory: u'/usr/lib/python2.7/site-packages/superset-0.17.1-py2.7.egg/superset/static/assets/package.json'

i dont have the dir static
and download https://github.com/airbnb/superset/blob/master/superset/static/assets is also null file
please help me,thy

**Comment by xrmx** [comment]
It looks like you didn't build the static files as written in the docs.

**Comment by BenchongYan** [comment]
I have the same problem，please help me thanks

$ fabmanager create-admin --app superset
Username [admin]: l
User first name [admin]: 
User last name [user]: 
Email [admin@fab.org]: 
Password: 
Repeat for confirmation: 
Was unable to import superset Error: [Errno 2] No such file or directory: u'/usr/lib/python2.7/site-packages/superset/static/assets/package.json'
