### ISSUE TITLE
there are no grain  dashboard-level controls avaliable

### ISSUE THREAD

**Issue by anddyhuaa** [airbnb/superset#2445]
### Superset version
{"GIT_SHA": "", "version": "0.15.4"}

although there are already some grain control on menus and views, no dashboard-level control and management avaliable for several users.others should not see the dashboard and also its name i built unless i grant it to or share with it? e.g when i entered the welcome page，if i built different dashboards for the same datasource，other users could see it .

**Comment by xrmx** [comment]
Dup of #1806

**Comment by cherrylynn** [comment]
**### "Dashboard level access control" is really really needed !**

Add permissions at the dashboard level.

- Create permissions for each dashboard with the format "dashboard access on [dashboard_title](dash_id:x)"
- The name of the permission is updated if the dashboard title is changed.
- Add a dashboard permission to a role via the Edit Role form, or, for convenience, add a role to a dashboard via the Edit Dashboard form.
- Optionally, add a default role to be added to each new dashboard created from a slice.
- The permission "all_dashboard_access" is added to Admin, Alpha, and Gamma roles.
- To allow private dashboards, remove "all_dashboard_access" from a role. This role will then only have access to the dashboards specified. Add a dashboard's permission to a role to "publish" it.
- Note that these permissions do not apply to slices. To make the data in a dashboard truly private, use dashboard permissions with a read only role that has no slice/explore access.

Reference: https://github.com/apache/incubator-superset/pull/5099
