### ISSUE TITLE
Some problems on the nav bar

### ISSUE THREAD

**Issue by anddyhuaa** [airbnb/superset#2446]
i used 0.15.4 it's OK but 0.16 version and lastest version,there are Some displaying problems on the nav bar
![error_nav](https://cloud.githubusercontent.com/assets/26573576/24159948/7b9c5136-0e9b-11e7-9ee2-7fa80d2227b0.png)

### Superset version
0.16 and later

**Comment by xrmx** [comment]
How are you installing superset? If building from source have you built the static files as documentation states?

**Comment by anddyhuaa** [comment]
yeah,i have installed superset on 0.15.4 verison according to the documentation  early and it works,  i wanna to upgrade to the lastest version, at first i thought some version mismatches  on python packages  or maybe some files cached , then i reinstall but it  doesn't work

**Comment by mistercrunch** [comment]
did you restart the server after upgrading?

**Comment by anddyhuaa** [comment]
i have restarted the server for several times but it shows as before not in correct format

**Comment by anddyhuaa** [comment]
i download the source code and initially it is a nomal file /root/superset-master/superset/assets, when install,an error occurs : can't found /root/superset-master/superset/static/assets/backendSync.json NO such file
so i remove this file and make a soft link 
[root@test2 build]# cd /root/superset-master/superset/static/
[root@test2 build]# touch /root/superset-master/superset/static/assets
../assets
[root@test2 build]# rm -f assets
[root@test2 build]# ln -s ../assets/ assets
[root@test2 static]# ls -la
total 8
lrwxrwxrwx.  1 root root   10 Mar 22 00:14 assets -> ../assets/
i am not sure there is any influence on that?

**Comment by ErosZZH** [comment]
Superset build frontend code on superset/assets. But when you start superset, it will download assets of frontend from superset/static/assets. So superset's author made this soft link. If you've moved superset's code, the soft link will be broken. Even though you've execute npm install and npm run build. There are no dist and node_modules directory under superset/static/assets, which will cause your problem.

**Comment by anddyhuaa** [comment]
thank you for your reply, i reinstall again and upgrade to 0.17.1,it works
