### ISSUE TITLE
Filter box with embedded widgets 

### ISSUE THREAD

**Issue by carpediemy** [airbnb/superset#2454]
Hi,

I'm embedding widgets to my web application and couldn't find a way to use filter box with embedded widgets. Is this supported? If yes, any pointers?

Thanks!

**Comment by mistercrunch** [comment]
What do yo mean by embedded widgets? are you using iframes?

**Comment by mistercrunch** [comment]
You could embed a dashboard instead of embedding individual charts. You can suffix the dashboard url with `?standalone=true` to not render the menu bar.

**Comment by carpediemy** [comment]
@mistercrunch Thanks! that solves my problem.

**Comment by carpediemy** [comment]
@mistercrunch When I embed dashboard with custom CSS and suffix ?standalone=true, the css changes are not getting reflected in the embedded dashboard. any pointers please to get this working?

**Comment by mistercrunch** [comment]
https://github.com/airbnb/superset/blob/ea72c6b0188e9c5a662358e89c95801b319296f8/superset/assets/javascripts/dashboard/components/CssEditor.jsx#L49

**Comment by carpediemy** [comment]
Thanks!. @mistercrunch Is there a way to embed dashboard without requiring authentication for viewers?.

**Comment by mistercrunch** [comment]
Granting more rights to the Public role should allow for that, though we don't use it at Airbnb so I can't guarantee it would work out of the box.

**Comment by carpediemy** [comment]
@mistercrunch I tried to give  all dashboard and datasource rights to public role but I still get 'access denied' error. Also I see this in the config 
"Grant  role the same set of permissions as for the GAMMA role.
This is useful if one wants to enable anonymous users to view dashboards. 
Explicit grant on specific datasets is still required.
PUBLIC_ROLE_LIKE_GAMMA = False" 
this dint work either. can you please let me know your thoughts on this?

**Comment by falgunifb** [comment]
@mistercrunch Can you please tell , how to enable filter box in my web application or any configuration that i need to add in config.py file to enable it .
