### ISSUE TITLE
Change the setting of superset from sqlite to MySQL - a problem!

### ISSUE THREAD

**Issue by bbs2009** [airbnb/superset#2467]
Make sure these boxes are checked before submitting your issue - thank you!

- [+ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [+ ] I have reproduced the issue with at least the latest released version of superset
- [+ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
version: 0.17.1

Hey.
I want to change the standard database configuration from sqlite to mysql.

1. Added its configuration file superset_config.py and put it in PYTHONPATH

```
# Superset specific config
#---------------------------------------------------------
ROW_LIMIT = 200000
SUPERSET_WORKERS = 4

SUPERSET_WEBSERVER_PORT = 8088
#---------------------------------------------------------

#---------------------------------------------------------
# Flask App Builder configuration
#---------------------------------------------------------
# Your App secret key
SECRET_KEY = '\2\1t567fgj7dtghjdhfui64@#$&77cvw424tkey\1\2\e\y\y\h'

# The SQLAlchemy connection string to your database backend
# This connection defines the path to the database that stores your
# superset metadata (slices, connections, tables, dashboards, ...).
# Note that the connection information to connect to the datasources
# you want to explore are managed directly in the web UI
#SQLALCHEMY_DATABASE_URI = 'sqlite:////path/to/superset.db'
SQLALCHEMY_DATABASE_URI = 'mysql://superset:32rasdf356ytsdfDD@localhost/superset'

# Flask-WTF flag for CSRF
CSRF_ENABLED = True

# Set this API key to enable Mapbox visualizations
MAPBOX_API_KEY = ''

```

2. I'm executing the code
`Fabmanager create-admin --app superset`

In my database mysql, tables have been added, as well as 1 user admin.

![default](https://cloud.githubusercontent.com/assets/11568424/24290368/64856dd6-108d-11e7-9dd7-78f110dc421c.png)

3. Then I execute the code:
`Superset db upgrade`

At this point, the sqlite database is created! Why?
![default](https://cloud.githubusercontent.com/assets/11568424/24290290/20a14b44-108d-11e7-9782-a69a0c962fb9.png)

![default](https://cloud.githubusercontent.com/assets/11568424/24290313/3376122c-108d-11e7-8022-ae1fceccb3a1.png)

3. Then I execute the code:
`Superset init`

And the changes are again happening in the database sqlite ! Why?
![default](https://cloud.githubusercontent.com/assets/11568424/24290471/c7067716-108d-11e7-9f95-7d206a3e9298.png)

Thank you.

**Comment by xrmx** [comment]
```
export PYTHONPATH=$WHEREYOURCONFIGIS:$PYTHONPATH
```
should do the trick, where of course WHEREYOURCONFIGIS is the path of the superset_config with the mysql database.

**Comment by jasondscott** [comment]
I think there is something wrong with the latest version of superset. 
I had it working with psql and after a recent deploy that installed the latest superset it stopped working.
I had to rollback to version 0.15.4 and it works again.

**Comment by xrmx** [comment]
@jasondscott: you had superset installed on postgresql?

**Comment by xrmx** [comment]
Anyway superset_config.py work fine here with latest master to override the db, fails badly with the options read by the cli though.

**Comment by jasondscott** [comment]
@xrmx Yes superset is installed on postgresql. Is that a problem?

**Comment by mistercrunch** [comment]
To debug you can fire up `ipython`, run `import superset_config` and type `superset_config?` and it will print the location of your superset_config module

**Comment by LYmahang123** [comment]
I have met the same question, can you tell me how you fixed it?

**Comment by mistercrunch** [comment]
Whatever the problem was I think its been addressed. Closing

**Comment by Lamabu** [comment]
Hi, I don't understand how integration with mysql should work. By default, superset.db has a lot of tables and indexes. Should I import  all of them in my new mysql database? I want to use superset to analyze data hosted on two tables from a mysql database.

**Comment by Aung-Myint-Thein** [comment]
@jasondscott is this solved?

I am running superset 0.19.0 and installed it from pip with Python 3.4.5. However, I faced the same issue as this while I am using postgresql. 

If it is solved, how did you solve it?

**Comment by Aung-Myint-Thein** [comment]
Oh solved the problem by `export PYTHONPATH="/home/user/superset/:$PYTHONPATH"`.

Initially, I was using `export PYTHONPATH="/home/user/superset:$PYTHONPATH"`. .. one simple `/` solved the problem :)

**Comment by JazzChen** [comment]
after removing ~/.superset/superset.db, it works

**Comment by ricardoorozco** [comment]
so that it works for me, change the variable also in the config.py file (/usr/local/lib/pythonX.X/site-packages/config.py)

**Comment by bllli** [comment]
export SUPERSET_CONFIG_PATH=superset/superset_config.py

**Comment by tooptoop4** [comment]
bump

**Comment by ccggeo** [comment]
> export SUPERSET_CONFIG_PATH=superset/superset_config.py
worked for me thanks!

**Comment by pundalikvk** [comment]
> export SUPERSET_CONFIG_PATH=superset/superset_config.py work for me

This worked for me today (Oct 2023), more than 6 years after the issue was reported. 

I did not find this anywhere in the documentation either. Took me WEEKS to figure this tiny thing out!
