### ISSUE TITLE
Creating users, role based data restrictions through API

### ISSUE THREAD

**Issue by arangates** [airbnb/superset#2476]
is there API documentation for creating new users ..etc. I want to create users from angular 2 application.i integrated superset in my application. but have no API access .is there REST api for all actions of superset?!

**Comment by mistercrunch** [comment]
Check out the `/users/api` endpoint. All models in Flask App Builder get a REST api, that means `/slicemodelview/api` also exist, and so on. It's somewhat documented in the FAB docs.

<img width="353" alt="screen shot 2017-03-25 at 6 10 29 pm" src="https://cloud.githubusercontent.com/assets/487433/24327456/60b4d530-1186-11e7-9cad-f19ce00a5986.png">

**Comment by mistercrunch** [comment]
On the Python side you can simply import the models and the ORM itself act as a CRUD API

**Comment by arangates** [comment]
tats great ... where can i find this ?!
