### ISSUE TITLE
No Longer Able to Set Column as Groupable

### ISSUE THREAD

**Issue by stephendj** [airbnb/superset#2484]
Make sure these boxes are checked before submitting your issue - thank you!

- [Yes] I have checked the superset logs for python stacktraces and included it here as text if any
- [Yes] I have reproduced the issue with at least the latest released version of superset
- [Yes] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.1

### Expected results
I should be able to check on the groupable checkbox and the setting is saved immediately

### Actual results
The setting is not saved and I'm unable to group by a specific column in the slices

### Steps to reproduce
1. Pick any table and click edit (data source)
2. In the table column list, check any column to set it as groupable
3. Exit the edit UI, and enter again
4. The checkbox will become unchecked

**Comment by mistercrunch** [comment]
That's fixed in `master`, I'll push a version as soon as we merge a few other fixes.

**Comment by stephendj** [comment]
@mistercrunch awesome, thanks!
