### ISSUE TITLE
How to authenticate with REST API

### ISSUE THREAD

**Issue by amancevice** [airbnb/superset#2488]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.17.1

### Expected results

N/A

### Actual results

N/A

### Steps to reproduce

Sorry if this has been answered somewhere else, but is there any documentation on how to authenticate through the REST API?

Specifically, I'd like to be able to return JSON from the `/superset/explore_json/` endpoint (copied from the UI slice view) using cURL (or something similar) but I get the following response when I do:

```json
{
  "message": "Access is Denied", 
  "severity": "danger"
}
```

Thanks

**Comment by mistercrunch** [comment]
This is how we do it in the unit tests:
https://github.com/airbnb/superset/blob/master/tests/base_tests.py#L127

But that may vary depending on the type of authentication you use.

**Comment by slarrain** [comment]
Hey @amancevice did you figure this out? I have this exact use case and was wondering if you solve it.
Thanks!

**Comment by amancevice** [comment]
@slarrain I did not -- gave up & moved on to other things. Sorry!

**Comment by andrewsali** [comment]
For those still looking for some kind of solution - the following example seems to work:

```
import requests
from bs4 import BeautifulSoup

# set up session for auth
s = requests.Session()
login_form = s.post("http://my_server/login")

# get Cross-Site Request Forgery protection token
soup = BeautifulSoup(login_form.text, 'html.parser')
csrf_token = soup.find('input',{'id':'csrf_token'})['value']

# login the given session
s.post('http://my_server/login/',data=dict(username='admin', password='my_passwd',csrf_token=csrf_token))

# run API call
print(s.get('http://my_server/users/api').text)
```

**Comment by alexjacquot** [comment]
Is there a documentation of the rest api ?

**Comment by mistercrunch** [comment]
The part we get for free on modelviews through FAB is documented here:
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/docs/quickhowto.rst#exposed-methods

**Comment by kalimuthu123** [comment]
i need authentication by using json web tokens

**Comment by DungLai** [comment]
> For those still looking for some kind of solution - the following example seems to work:
> 
> ```
> import requests
> from bs4 import BeautifulSoup
> 
> # set up session for auth
> s = requests.Session()
> login_form = s.post("http://my_server/login")
> 
> # get Cross-Site Request Forgery protection token
> soup = BeautifulSoup(login_form.text, 'html.parser')
> csrf_token = soup.find('input',{'id':'csrf_token'})['value']
> 
> # login the given session
> s.post('http://my_server/login/',data=dict(username='admin', password='my_passwd',csrf_token=csrf_token))
> 
> # run API call
> print(s.get('http://my_server/users/api').text)
> ```

`csrf_token = soup.find('input',{'id':'csrf_token'})['value']` gave me this error:

`TypeError: 'NoneType' object is not subscriptable`

**Comment by prgx-mrodri01** [comment]
> For those still looking for some kind of solution - the following example seems to work:
> 
> ```
> import requests
> from bs4 import BeautifulSoup
> 
> # set up session for auth
> s = requests.Session()
> login_form = s.post("http://my_server/login")
> 
> # get Cross-Site Request Forgery protection token
> soup = BeautifulSoup(login_form.text, 'html.parser')
> csrf_token = soup.find('input',{'id':'csrf_token'})['value']
> 
> # login the given session
> s.post('http://my_server/login/',data=dict(username='admin', password='my_passwd',csrf_token=csrf_token))
> 
> # run API call
> print(s.get('http://my_server/users/api').text)
> ```

I had to change login_form = s.post("http://my_server/login") to login_form = s.get("http://my_server/login")
for this to work. thanks!

**Comment by imanju** [comment]
Hi pritypriya25 its working for me.it generated jwt token. how can i need to fetch dashboard in superset through /dashboard/ endpoint can you please help me.
Thank you

**Comment by pritypriya25** [comment]
@imanju you can check superset api . It provides APIs for all kind of operations.
https://superset.apache.org/docs/rest-api
It also has a swagger ui where you can check for all APIs.

**Comment by nytai** [comment]
I haven't really found a good way to authenticate non password based accounts against the rest api. So far only db and ldap work. What I have resorted to is creating a db based "service account" and using that for api actions

**Comment by xneg** [comment]
Faced this problem trying to access `explore_json` with JWT token. This doesn't work cause this endpoint is missing `@protected` decorator. Want to make a PR to fix it (or receive feedback why I shouldn't do so).

**Comment by SAVE-POlNT** [comment]
hello , i want to integrate superset with an external existing service , but the problem is that users have to login twice (one for the service and one for supsetset ) can i bypass it with the jwt token ? 

did anyone face this before ?

**Comment by xneg** [comment]
@SAVE-POlNT we are doing exact this thing now. But, of course, there are some pitfalls and also it depends on existing service.  I don't think this topic matches this issue but you can contact me directly so we could discuss your problem.

**Comment by SAVE-POlNT** [comment]
@xneg i would like to , can yu please leave your discord or your e-mail so i can contact you ?

**Comment by vedangparasnis** [comment]
@xneg in Superset all the Api are build on top of Flask App builder BaseApi with all the security decorators borrowed from FAB.  We tried to replicate some of the methods with our own FAB security views and security manager, since we are using OAUTH, either we use the global rs256 session token signed from IDP, or integrate vault by adding a custom Decorator to bypass the default FAB security decorators and use this token to authenticate.

**Comment by xneg** [comment]
@SAVE-POlNT you can find my email in my profile.

**Comment by xneg** [comment]
@vedangparasnis yes, I know about FAB but what I mean is that not all enpdoints in Superset have decorator `@protected` (from FAB) and this is a restriction to complete JWT integration.

**Comment by vedangparasnis** [comment]
@xneg , do you think it is a limitation of AUTH_DB type in Superset Security manager, correct me if I wrong, in other type excluding Remote_user the IDP session cookie bypasses these api security using the same global session token.

**Comment by xneg** [comment]
@vedangparasnis I think we misunderstand each other and sorry for misunderstanding. I was talking about OAuth authentication and using it to access endpoints.

**Comment by cdmikechen** [comment]
We use flask-oidc to support oauth/oidc token, maybe we can extend superset api to better support non flask security authentication?

**Comment by lmingzhi** [comment]
Thank to [andrewsali](https://github.com/andrewsali) commented [on 18 Jan 2018](https://github.com/apache/superset/issues/2488#issuecomment-358429474), I finally figure out how to access the superset REST API by python code.

```
import requests
from bs4 import BeautifulSoup

# https://192.168.100.120:8088/swagger/v1
superset_host = '192.168.100.120:8088'
username = 'YOUR_username'
password = 'YOUR_password'

# set up session for auth
s = requests.Session()
login_form = s.post(f"http://{superset_host}/login")
# get Cross-Site Request Forgery protection token
soup = BeautifulSoup(login_form.text, 'html.parser')
csrf_token = soup.find('input',{'id':'csrf_token'})['value']
data = {
    'username': username,
    'password': password,
    'csrf_token':csrf_token
}
# login the given session
s.post(f'http://{superset_host}/login/', data=data)
print(dict(s.cookies))

url = f'http://{superset_host}/api/v1/chart/'
r = s.get(url)
print(r.json())
```

**Comment by Jp555-jai** [comment]
I have a requirement where I need to integrate a superset dashboard with my client application, so whenever the user login the client web app using token superset automatically by pass the login page and redirects to the dashboard based on role.  I am new to web development can someone help me with step by step process to integrate it would be grateful.
Thanks in advance.
