### ISSUE TITLE
sqllab timeout is not working

### ISSUE THREAD

**Issue by yileic** [airbnb/superset#2504]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
latest master branch and also 0.16.1

### Expected results
Sql Lab would time out after the time limit specified in config

### Actual results
The timeout message flashes but the query continues running.
In the console, it shows:
2017-03-28 16:32:32,128:WARNING:root:timeout can't be used in the current context
2017-03-28 16:32:32,128:ERROR:root:signal only works in main thread

Maybe something in the method 'get_sql_results' in 'sql_lab.py' is causing that.

**Comment by yileic** [comment]
encountering #2532 too

**Comment by mistercrunch** [comment]
Are you using the debug web server?

**Comment by yileic** [comment]
Sorry this message is from debug, but when not debugging, the sql lab continues running after the timeout (eg. 30 seconds). The time out warning message just flashes and the sql lab will continue running, instead of stop.

**Comment by shivaganapuram** [comment]
I have same issue. Does anyone have a solution for this ?. I tried to set 
SQLLAB_TIMEOUT = 30*60*60.

No luck yet ..

**Comment by shalmalijain** [comment]
Where is SQLLAB_TIMEOUT? Which config file?
