### ISSUE TITLE
[vis] y axis needs some margin even without labels

### ISSUE THREAD

**Issue by yileic** [airbnb/superset#2508]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
latest master branch

### Expected results
The y axis numbers should be fully shown no matter in what number formatting.

### Actual results
If the number is too long, it will not be fully shown, as the following picture.
<img width="777" alt="yaxis" src="https://cloud.githubusercontent.com/assets/10532596/24438141/249ad696-13fa-11e7-9150-6a0a9c4b70bf.png">

**Comment by xrmx** [comment]
While a perfect layout that fits everything you throw at it would be nice, the formatting of your y axis label is totally gratuitous.

**Comment by yileic** [comment]
In many situations, people need to see the raw number, which are usually quite long. It would be nice when formatting the y axis as '.3s', there is still some way to see the raw number. For example, when hovering over, it shows the raw number instead of the y-axis formatted number.
