### ISSUE TITLE
Date Format is not applied on TableView

### ISSUE THREAD

**Issue by kkalyan** [airbnb/superset#2515]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

![image](https://cloud.githubusercontent.com/assets/391567/24453971/c211ba90-143e-11e7-8cd0-71fda3e51186.png)
![image](https://cloud.githubusercontent.com/assets/391567/24453977/c821c330-143e-11e7-893e-c21e840a93e9.png)

### Superset version
0.17.6

### Expected results
In the table view, selecting table timestamp like (%m/%d/%Y) should display the time field in results in the format. 

### Actual results
changing date format has no impact. it's always displayed like 2017-03-24T00:00:00 

### Steps to reproduce
Go to any data source
Pick any granularity other than 'all'
Select 'Include Time'
Change the date format to any format

**Comment by higaxman** [comment]
Any hint how to fix it ?

**Comment by kelchm** [comment]
I'm also seeing this issue. Haven't had a chance to dig into it yet.

**Comment by kkalyan** [comment]
fixed in 0.18.5

**Comment by napjon** [comment]
Reopen. Issue still exists in latest version (0.22.1)
