### ISSUE TITLE
[performance] serve roboto from our server rather than fetching from fonts.googleapis.com

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#2518]
https://github.com/ascott/superset/blob/master/superset/assets/stylesheets/less/cosmo/bootswatch.less#L5

- this is especially problematic when multiple iframes are rendered on a page.

**Comment by mistercrunch** [comment]
it also hits me with flimsy web connection (development on train and during demos)

**Comment by ascott** [comment]
https://github.com/airbnb/superset/pull/2519

**Comment by ascott** [comment]
fixed with https://github.com/airbnb/superset/pull/2519
