### ISSUE TITLE
what are these columns used for?

### ISSUE THREAD

**Issue by zhangjiajie023** [airbnb/superset#2535]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

TableColumn.is_active, filterable
SqlMetric.is_restricted, 
SqlaTable.filter_select_enabled, default_endpoint

I don't find these columns are been used, for what?

**Comment by xrmx** [comment]
On latest master, git grep founds users for all but TableColumn.is_active.

**Comment by mistercrunch** [comment]
https://github.com/airbnb/superset/pull/2536 should clarify things somewhat.
