### ISSUE TITLE
Decimal formatting in Table View (M, k, m etc.)

### ISSUE THREAD

**Issue by magnusso** [airbnb/superset#2546]
Is there some way to change the decimal formatting in Table View?

Currently 0.532 is formatted as 532m. I would very much welcome a formatting option that would not use M (for 10^6), k (for 10^3) and m (for 10^-3).

![capture](https://cloud.githubusercontent.com/assets/26468823/24652201/98f80358-1939-11e7-947c-515181ae6caf.JPG)

Superset version: 0.17.0

**Comment by kkalyan** [comment]
You can use D3 Format like .1% in the metric configuration. 
More information about format: https://github.com/d3/d3-format

**Comment by mistercrunch** [comment]
You can set that up in the metric definition form
