### ISSUE TITLE
Question: How do bullet charts work in superset?

### ISSUE THREAD

**Issue by jnawras** [airbnb/superset#2555]
1- Where does the maximum value come from (shown in the label once hovering over the gray background rectangle)? Seems always to be some 110% the "current value". 

2- How can I set that value?

3- How can I set the marker values dynamically (not hard-coded) based on an SQL calculation?

### Superset version
0.17.2

**Comment by kmagida110** [comment]
For 1 and 2 you can use the ranges and labels to set the values and the name you want to associate with them. 

I'd be interested in the answer to 3 as well.

**Comment by mistercrunch** [comment]
In its current state only the blue line can be associated with a real, not-hard-coded value

**Comment by jnawras** [comment]
Thanks! I figured so after looking into the scripts.
Do you think this could easily be implemented? It seems to me if so, this would require changes across multiple scripts to be well generalized.

Not sure where this issue fits under current labels. I got the answers I need for now, feel free to close it, or I'll do in awhile.

**Comment by swattamw** [comment]
> For 1 and 2 you can use the ranges and labels to set the values and the name you want to associate with them.
> 
> I'd be interested in the answer to 3 as well.

Did we get answer for 3?
I am trying to figure it out as well

**Comment by phamthoidinhthien** [comment]
Looking for solution as well
