### ISSUE TITLE
Dashboards- Non Admin User's

### ISSUE THREAD

**Issue by FareehaNaaz** [airbnb/superset#2577]
Make sure these boxes are checked before submitting your issue - thank you!

- [yes] I have checked the superset logs for python stacktraces and included it here as text if any
- [yes] I have reproduced the issue with at least the latest released version of superset
- [yes] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.1

### Expected results
Hi! i am new to superset and i have created a few dashboards and gave ownership to few users(non-admin) with vrious roles, the idea is to check how dashboards are visible for users with different roles, but when i login through these users they dont have access to the dashbaords.

### Actual results
N/A

### Steps to reproduce
N/A

**Comment by xrmx** [comment]
Have you read the documentation? http://airbnb.io/superset/security.html

**Comment by FareehaNaaz** [comment]
yes, 
here i gave permission for non-admin users over database
![capture](https://cloud.githubusercontent.com/assets/25292376/24853615/4d2c020c-1df9-11e7-9aae-0abbe8d9c528.PNG)

user given ownership for the dashbaord
![capture1](https://cloud.githubusercontent.com/assets/25292376/24853617/4d3c4be4-1df9-11e7-8d14-3bf95e98dd7d.PNG)

view through user to the dashboard after login with the same user
![capture2](https://cloud.githubusercontent.com/assets/25292376/24853616/4d2d2c68-1df9-11e7-9046-79b25c1b18f9.PNG)

**Comment by xrmx** [comment]
Does the user have permissions for the datasource?

**Comment by FareehaNaaz** [comment]
thanks! changing permissions for user role( gave datasource,database,dashboard view options) worked.
