### ISSUE TITLE
Question: I want to setup some sort of auto login?

### ISSUE THREAD

**Issue by govardhank** [airbnb/superset#2591]
Hi ,

Actually what i want is I am developing web application using nodejs.After login into my web app , when i click a link in my application, it should redirect to superset auto login and open dashboard page bypassing the login page in a separate window? can you please briefly explain or give me step wise instructions on how to do this.Didn't find documentation in Flask App Builder (FAB)  for REMOTE_USER

Thanks & Regards,
Govardhan

**Comment by mistercrunch** [comment]
http://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-methods
