### ISSUE TITLE
D3Format works in Slices but not in Dashboards 

### ISSUE THREAD

**Issue by magnusso** [airbnb/superset#2592]
Formatting a SQL Metric with _D3Format_ has the desired effect on a slice of type _Table View_ when the slice is viewed through _Slices_, However, when the same slice is is viewed through _Dashboards_ the formatting is lost.

Related to: #2546

Superset version: 0.17.0

**Comment by mistercrunch** [comment]
https://github.com/airbnb/superset/pull/2598 should address this
