### ISSUE TITLE
Bug when editing any table

### ISSUE THREAD

**Issue by bbs2009** [airbnb/superset#2613]
Make sure these boxes are checked before submitting your issue - thank you!

- [+] I have checked the superset logs for python stacktraces and included it here as text if any
- [+] I have reproduced the issue with at least the latest released version of superset
- [+] I have checked the issue tracker for the same issue and I haven't found one similar

Greetings to all. A new bug has appeared.

### Superset version
{"GIT_SHA": "", "version": "0.17.4"}

### Expected results
Successful editing of table fields.

### Actual results

![default](https://cloud.githubusercontent.com/assets/11568424/24999854/ced3ee50-2047-11e7-99d6-014c4de05e76.png)

### Steps to reproduce
1. Open the list of tables

![default](https://cloud.githubusercontent.com/assets/11568424/24999798/a2dc30b4-2047-11e7-97bb-0f794d7e507a.png)

2. Select any of the tables and click edit

![default](https://cloud.githubusercontent.com/assets/11568424/24999890/f3766eea-2047-11e7-9d1b-b6facd58dcbb.png)

3. 3. I see the error
![default](https://cloud.githubusercontent.com/assets/11568424/24999854/ced3ee50-2047-11e7-99d6-014c4de05e76.png)

4. 4. Nothing in the terminal logs
```
Loaded your LOCAL configuration at [/data/work/virtualenvs/superset3/bin/superset_config.py]
2017-04-13 12:53:26,431:INFO:werkzeug: * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)
2017-04-13 12:53:26,432:INFO:werkzeug: * Restarting with stat
Loaded your LOCAL configuration at [/data/work/virtualenvs/superset3/bin/superset_config.py]
2017-04-13 12:53:29,046:WARNING:werkzeug: * Debugger is active!
2017-04-13 12:53:29,046:INFO:werkzeug: * Debugger PIN: 833-503-817
/data/work/virtualenvs/superset3/lib/python3.6/site-packages/flask_appbuilder/forms.py:245: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = self(obj=obj)
2017-04-13 12:53:42,443:INFO:werkzeug:192.168.2.58 - - [13/Apr/2017 12:53:42] "GET /tablemodelview/edit/31 HTTP/1.1" 404 -
 
```

Slices and dashboards from this table work fine, I can not just open the tables for editing. Any idea why this is so?Thank you

**Comment by kkalyan** [comment]
I saw similar issue, clearing cookie fixed the problem.

**Comment by bbs2009** [comment]
Thank you so much. My problem is solved.
