### ISSUE TITLE
Serie limit in bubble chart is not working

### ISSUE THREAD

**Issue by 360d-io-labs** [airbnb/superset#2617]
### Superset version
0.17.4

### Expected results
When creating a bubble chart if you  set the maximum number of series to display it should only display this number of bubble at max. 

### Actual results
Currently all the series are displayed whatever the value in the field series limit.

### Steps to reproduce
Create a bubble chart with X series of point and set a series limit Y smaller. 

On another point, it would be great to be able to not display the plot legend but to be able to keep the tool tip. Currently if you disable the legend the tool tip is also disabled.

**Comment by jeffcarey** [comment]
@360d-io-labs From examining this it looks like this field is only used when dealing with time series charts, though the "Series limit" field appears on non-time series charts also.

@mistercrunch Any reason this shouldn't be supported on a non-time series chart? I can attempt a pull request if you agree it's worth doing.

**Comment by mistercrunch** [comment]
Here's the fix:
https://github.com/airbnb/superset/pull/2815
