### ISSUE TITLE
Pass UNIX socket parameters to runserver, and hence to gunicorn

### ISSUE THREAD

**Issue by scaba** [airbnb/superset#2621]
I'd prefer to have Gunicorn serve requests from a UNIX socket instead of via HTTP. Is this something that can be added to a near future version of Superset?

**Comment by xrmx** [comment]
You can add your own thin wrapper for gunicorn, runserver is not much more than that https://github.com/airbnb/superset/blob/master/superset/cli.py#L61

**Comment by mistercrunch** [comment]
Right. You can issue your own gunicorn command or hook up whatever else wsgi server and configure is however you prefer

**Comment by scaba** [comment]
Thanks for your replies. While it's not very challenging to create a Gunicorn startup script to allow Superset to be served from a socket, I think it's a common enough set up to warrant having runserver (or the Superset config file) accept a path to a UNIX socket for the sake of consistency and simplicity. So I've added a pull request: https://github.com/airbnb/superset/pull/2627
