### ISSUE TITLE
no scrolling in the explore view

### ISSUE THREAD

**Issue by xrmx** [airbnb/superset#2626]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

f5216f60479a2580b5a5532ec8c1b0882905d7a0

### Expected results

I can scroll down to see all the visualization options

### Actual results

There's no scrollbar

### Steps to reproduce

Open a slice and select distribution chart as visualization type.

**Comment by mistercrunch** [comment]
I think this is fixed in master. Please confirm and close the issue

**Comment by xrmx** [comment]
Fixed, thanks!
