### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by HugoPu** [airbnb/superset#2629]
Hi superset team,

I think the following code miss calling gettext or lazy_gettext method,

superset/views  dashboardmodelviewasync
` label_columns = { 
        'dashboard_link': _('Dashboard'),  
        'creator': _("Creator"),  
        'modified': _("Modified"),  
    }`

superset/views DeleteMixin
`@action("muldelete", _("Delete", _("Delete all Really?"), "fa-trash", single=False)`

**Comment by xrmx** [comment]
If you want to contribute code, please open a PR. Also you missed a closing paren.
