### ISSUE TITLE
SQLAlchemy URI  for hive problem

### ISSUE THREAD

**Issue by hungrytortoise** [airbnb/superset#2632]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

the lastest version
### Expected results
my SQLAlchemy URI is:  hive://jiaoyang@10.5.x.x:10000/xxx_dmp_idmapping?auth=NOSASL

### Actual results
when i click test connect btn,
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCould not start SASL: Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found"}

**Comment by xrmx** [comment]
Does not looks a superset issue, more like a config or sqlalchemy dialect issue.

**Comment by hungrytortoise** [comment]
i use sqlalchemy URI prefix like "jdbc+hive://..." ,but it does not work too and  error msg is 
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:jdbc.hive"}
how can i fix this.
tks

**Comment by xrmx** [comment]
Still the new error is not superset related

**Comment by hungrytortoise** [comment]
solution:yum -y install cyrus-sasl-plain

**Comment by fadhlounanis** [comment]
@hungrytortoise  could you please tell me which version of superset have you benn using ?

**Comment by matiji66** [comment]
Hello, I mtet this problem either.And I have install cyrus-sasl-plain,but error still occur.
`ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:jdbc.hive"}`.

**Comment by danny-zhu** [comment]
In debian or unbuntu would be worked by:apt install -y libsasl2-dev libsasl2-2 libsasl2-modules-gssapi-mit
