### ISSUE TITLE
Date filter in filter box doesn't work

### ISSUE THREAD

**Issue by ErosZZH** [airbnb/superset#2650]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y] I have checked the superset logs for python stacktraces and included it here as text if any
- [Y] I have reproduced the issue with at least the latest released version of superset
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
airbnb_prod.0.15.5.0

### Expected results
'World's population' slice in 'World's Bank Data' sample dashboard will change after I added date filter of datasource wb_health_population

### Actual results
The number on 'World's population' slice didn't change, after I add some date filter of the datasource.

### Steps to reproduce
1. Save 'World's population' slice as a new slice in a test dashboard.
2. Edit 'Region filter' slice, check 'date filter', then save it as a new slice in the same test dashboard.
3. Open the test dashboard, add some region filter, world population will change accordingly, but when I add some date filter. For example: from: 1980, to: 1990, the population didn't change.

I checked the request:

http://host:port/superset/explore_json/table/2/?form_data=%7B%22datasource%22%3A%222__table%22%2C%22viz_type%22%3A%22filter_box%22%2C%22slice_id%22%3A46%2C%22granularity_sqla%22%3A%22year%22%2C%22time_grain_sqla%22%3A%22Time%20Column%22%2C%22since%22%3A%222014-01-01%22%2C%22until%22%3A%222014-01-01%22%2C%22date_filter%22%3Atrue%2C%22groupby%22%3A%5B%22region%22%2C%22country_name%22%5D%2C%22metric%22%3A%22sum__SP_POP_TOTL%22%2C%22where%22%3A%22%22%2C%22having%22%3A%22%22%2C%22filters%22%3A%5B%5D%7D&extra_filters=%5B%7B%22col%22%3A%22__from%22%2C%22op%22%3A%22in%22%2C%22val%22%3A%221980%22%7D%2C%7B%22col%22%3A%22__to%22%2C%22op%22%3A%22in%22%2C%22val%22%3A%221990%22%7D%5D&json=true&force=false

form data is:
form_data:{"datasource":"2__table","viz_type":"filter_box","slice_id":46,"granularity_sqla":"year","time_grain_sqla":"Time Column","since":"2014-01-01","until":"2014-01-01","date_filter":true,"groupby":["region","country_name"],"metric":"sum__SP_POP_TOTL","where":"","having":"","filters":[]}
extra_filters:
[{"col":"__from","op":"in","val":"1980"},{"col":"__to","op":"in","val":"1990"}]

But I got the response like this:
{"error": null, "query": "SELECT year AS __timestamp,\n               SUM(\"SP_POP_TOTL\") AS \"sum__SP_POP_TOTL\"\nFROM wb_health_population\nWHERE year >= '1917-04-20 13:29:11.000000'\n  AND year <= '2017-04-20 13:29:11.000000'\n  AND region IN ('East Asia & Pacific')\nGROUP BY year LIMIT 50000\nOFFSET 0", "is_cached": false, "cache_timeout": 86400, "data": {"data": [[-315619200000.0, 1031863394.0], [-283996800000.0, 1034767718.0], [-252460800000.00003, 1048537618.0], [-220924800000.0, 1073600747.0], [-189388800000.0, 1098305025.0], [-157766400000.0, 1124077872.0], [-126230400000.00002, 1153296196.0], [-94694400000.0, 1181582226.0], [-63158400000.00001, 1210302481.0], [-31536000000.000004, 1242569208.0], [0.0, 1274888198.0], [31536000000.000004, 1308215425.0], [63072000000.00001, 1339781984.0], [94694400000.0, 1369814002.0], [126230400000.00002, 1399636343.0], [157766400000.0, 1426562368.0], [189302400000.0, 1450503110.0], [220924800000.0, 1473091499.0], [252460800000.00003, 1495573053.0], [283996800000.0, 1518439245.0], [315532800000.0, 1540823440.0], [347155200000.0, 1563926423.0], [378691200000.0, 1589245249.0], [410227200000.0, 1614538807.0], [441763200000.0, 1638618355.0], [473385600000.0, 1663385538.0], [504921600000.00006, 1689894237.0], [536457600000.00006, 1717904169.0], [567993600000.0, 1746140324.0], [599616000000.0, 1773743982.0], [631152000000.0, 1800365903.0], [662688000000.0, 1825955698.0], [694224000000.0, 1849800435.0], [725846400000.0, 1872809684.0], [757382400000.0, 1895892806.0], [788918400000.0, 1918680993.0], [820454400000.0, 1941199188.0], [852076800000.0, 1963227851.0], [883612800000.0, 1984508261.0], [915148800000.0, 2004495631.0], [946684800000.0, 2023534787.0], [978307200000.0001, 2041915058.0], [1009843200000.0001, 2059375225.0], [1041379200000.0001, 2076029083.0], [1072915200000.0001, 2092086887.0], [1104537600000.0, 2107802765.0], [1136073600000.0, 2123180222.0], [1167609600000.0, 2137834848.0], [1199145600000.0, 2152663168.0], [1230768000000.0, 2167098541.0], [1262304000000.0, 2181465325.0], [1293840000000.0, 2195899073.0], [1325376000000.0, 2210627396.0], [1356998400000.0, 2225523116.0], [1388534400000.0, 2240687901.0]], "compare_lag": "10", "compare_suffix": "over 10Y"}, "form_data": {"y_axis_format": ".3s", "granularity_sqla": "year", "slice_id": 45, "until": "now", "viz_type": "big_number", "where": "", "time_grain_sqla": "Time Column", "metric": "sum__SP_POP_TOTL", "compare_lag": "10", "filters": [{"val": "1980", "col": "__from", "op": "in"}, {"val": "1990", "col": "__to", "op": "in"}, {"val": ["East Asia & Pacific"], "col": "region", "op": "in"}], "having": "", "datasource": "2__table", "compare_suffix": "over 10Y", "since": "100 year ago"}, "filter_endpoint": "/superset/filter/table/2/?y_axis_format=.3s&granularity_sqla=year&slice_id=45&until=now&viz_type=big_number&where=&time_grain_sqla=Time+Column&metric=sum__SP_POP_TOTL&compare_lag=10&filters=%7B%27val%27%3A+%271980%27%2C+%27col%27%3A+%27__from%27%2C+%27op%27%3A+%27in%27%7D&filters=%7B%27val%27%3A+%271990%27%2C+%27col%27%3A+%27__to%27%2C+%27op%27%3A+%27in%27%7D&filters=%7B%27val%27%3A+%5B%27East+Asia+%26+Pacific%27%5D%2C+%27col%27%3A+%27region%27%2C+%27op%27%3A+%27in%27%7D&having=&datasource=2__table&compare_suffix=over+10Y&since=100+year+ago", "cached_dttm": "2017-04-20T13:29:11", "stacktrace": null, "status": "success", "cache_key": "97d478ca46e70299f8debf176ad3b4f2"}

From the 'query' node, I found the sql still use the default date filter configured in World's population slice.

**Comment by ErosZZH** [comment]
<img width="362" alt="1" src="https://cloud.githubusercontent.com/assets/9304243/25216087/766c52a2-25d3-11e7-8e45-a99442cd0543.png">
<img width="463" alt="2" src="https://cloud.githubusercontent.com/assets/9304243/25216086/766c4762-25d3-11e7-97dd-9acf7b36a10e.png">
<img width="439" alt="3" src="https://cloud.githubusercontent.com/assets/9304243/25216088/766cddee-25d3-11e7-88aa-d257251432f5.png">

**Comment by Xiaowang0206** [comment]
hi  ~
I have the same problem，Has it been settled yet?

这个是和字段本身的格式有关吗
