### ISSUE TITLE
The messages.mo file doesn't work in properties panel

### ISSUE THREAD

**Issue by yhc1990518** [airbnb/superset#2683]
Hi,

I made a messages.mo in version 0.15.4, this message.mo works fine like this:
![1](https://cloud.githubusercontent.com/assets/24221476/25473891/c95ff47e-2b63-11e7-8ee2-241e55105c88.png)

When I upgraded superset to 0.17.5, this same meesage.mo doesn't working like this:
![2](https://cloud.githubusercontent.com/assets/24221476/25474176/cafea8ce-2b64-11e7-900e-e05cb2d5a82f.png)

I don't know how to solve this problem? PLEASE HELP ME!!!!!!

THANK YOU~

**Comment by xrmx** [comment]
Strings changed you have to update your translation

**Comment by xrmx** [comment]
Please update your translation using latest master since it has the needed translatable strings for chinese.

**Comment by yhc1990518** [comment]
I want to know Is the properties panel cannot be translated?
Thank you~
