### ISSUE TITLE
Document best approach to using py3

### ISSUE THREAD

**Issue by robert-digit** [airbnb/superset#2684]
Make sure these boxes are checked before submitting your issue - thank you!

- [N/A] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.5

### Expected results
Using python3 instead of python2 is documented

### Actual results
Python3 usage is referred to only vaguely

### Steps to reproduce
Install superset, try to use python3

We switched to using python3 for Superset after some painful issues with unicode and db migrations. However, how best to do so isn't clearly documented - we did so by changing the shebangs in bin/superset, cli.py, and extract_table_names.py to refer to python3. (i.e. `#!/usr/bin/env python3`)

However, to get this to work we ended up adding psycopg2 to install_reqs in setup.py, and updating thrift to 0.10.0. This might be due to quirks in our deployment (using Superset inside a Docker container running Ubuntu 16.04, and connecting to Redshift).

Are people able to use superset with python3 with no changes to the basic repo? If you're not building from source, what's the best approach? Using a virtualenv and setting the `python` to python3 is one approach, but I'm curious what others who aren't building from source do.

**Comment by xrmx** [comment]
As the documentation already suggests please use a virtualenv

**Comment by robert-digit** [comment]
OK. I was hoping to avoid using a virtualenv inside a docker container - will try just changing /usr/bin/python to python3 and seeing what happens.

**Comment by xrmx** [comment]
You can create a python3 only container and symlink usr/bin/python to usr/bin/python3

**Comment by robert-digit** [comment]
That's what I ended up doing - works ok except that for some reason I get segmentation faults install thriftpy, which I didn't before...

**Comment by mistercrunch** [comment]
thriftpy isn't py3 compatible yet I think

**Comment by xrmx** [comment]
@mistercrunch it does, https://travis-ci.org/eleme/thriftpy
