### ISSUE TITLE
Cannot read property 'slice_name' of null

### ISSUE THREAD

**Issue by X-Mars** [airbnb/superset#2712]
`Uncaught TypeError: Cannot read property 'slice_name' of null`
i got this "ERROR"  when i "Save as"

**Comment by X-Mars** [comment]
Ubuntu 14.04 x64

**Comment by X-Mars** [comment]
Python 3.4.3

**Comment by xrmx** [comment]
Please fill all the missing information per the issue template

**Comment by X-Mars** [comment]
`explorev2.0.16.1.entry.js:229 Uncaught TypeError: Cannot read property 'slice_name' of null
    at t.e (explorev2.0.16.1.entry.js:229)
    at d._renderValidatedComponentWithoutOwnerOrContext (explorev2.0.16.1.entry.js:55)
    at d._renderValidatedComponent (explorev2.0.16.1.entry.js:55)
    at d.performInitialMount (explorev2.0.16.1.entry.js:55)
    at d.mountComponent (explorev2.0.16.1.entry.js:55)
    at Object.mountComponent (explorev2.0.16.1.entry.js:40)
    at d.performInitialMount (explorev2.0.16.1.entry.js:55)
    at d.mountComponent (explorev2.0.16.1.entry.js:55)
    at Object.mountComponent (explorev2.0.16.1.entry.js:40)
    at Object.updateChildren (explorev2.0.16.1.entry.js:55)
e @ explorev2.0.16.1.entry.js:229
_renderValidatedComponentWithoutOwnerOrContext @ explorev2.0.16.1.entry.js:55
_renderValidatedComponent @ explorev2.0.16.1.entry.js:55
performInitialMount @ explorev2.0.16.1.entry.js:55
mountComponent @ explorev2.0.16.1.entry.js:55
mountComponent @ explorev2.0.16.1.entry.js:40
performInitialMount @ explorev2.0.16.1.entry.js:55
mountComponent @ explorev2.0.16.1.entry.js:55
mountComponent @ explorev2.0.16.1.entry.js:40
updateChildren @ explorev2.0.16.1.entry.js:55
_reconcilerUpdateChildren @ explorev2.0.16.1.entry.js:55
_updateChildren @ explorev2.0.16.1.entry.js:55
updateChildren @ explorev2.0.16.1.entry.js:55
_updateDOMChildren @ explorev2.0.16.1.entry.js:54
updateComponent @ explorev2.0.16.1.entry.js:54
receiveComponent @ explorev2.0.16.1.entry.js:54
receiveComponent @ explorev2.0.16.1.entry.js:40
_updateRenderedComponent @ explorev2.0.16.1.entry.js:55
_performComponentUpdate @ explorev2.0.16.1.entry.js:55
updateComponent @ explorev2.0.16.1.entry.js:55
performUpdateIfNecessary @ explorev2.0.16.1.entry.js:55
performUpdateIfNecessary @ explorev2.0.16.1.entry.js:40
s @ explorev2.0.16.1.entry.js:40
perform @ explorev2.0.16.1.entry.js:40
perform @ explorev2.0.16.1.entry.js:40
perform @ explorev2.0.16.1.entry.js:40
E @ explorev2.0.16.1.entry.js:40
closeAll @ explorev2.0.16.1.entry.js:40
perform @ explorev2.0.16.1.entry.js:40
batchedUpdates @ explorev2.0.16.1.entry.js:56
i @ explorev2.0.16.1.entry.js:40
dispatchEvent @ explorev2.0.16.1.entry.js:56
explorev2.0.16.1.entry.js:229 Uncaught TypeError: Cannot read property 'slice_name' of null
    at t.e (explorev2.0.16.1.entry.js:229)
    at d._renderValidatedComponentWithoutOwnerOrContext (explorev2.0.16.1.entry.js:55)
    at d._renderValidatedComponent (explorev2.0.16.1.entry.js:55)
    at d.performInitialMount (explorev2.0.16.1.entry.js:55)
    at d.mountComponent (explorev2.0.16.1.entry.js:55)
    at Object.mountComponent (explorev2.0.16.1.entry.js:40)
    at d.performInitialMount (explorev2.0.16.1.entry.js:55)
    at d.mountComponent (explorev2.0.16.1.entry.js:55)
    at Object.mountComponent (explorev2.0.16.1.entry.js:40)
    at Object.updateChildren (explorev2.0.16.1.entry.js:55)
e @ explorev2.0.16.1.entry.js:229
_renderValidatedComponentWithoutOwnerOrContext @ explorev2.0.16.1.entry.js:55
_renderValidatedComponent @ explorev2.0.16.1.entry.js:55
performInitialMount @ explorev2.0.16.1.entry.js:55
mountComponent @ explorev2.0.16.1.entry.js:55
mountComponent @ explorev2.0.16.1.entry.js:40
performInitialMount @ explorev2.0.16.1.entry.js:55
mountComponent @ explorev2.0.16.1.entry.js:55
mountComponent @ explorev2.0.16.1.entry.js:40
updateChildren @ explorev2.0.16.1.entry.js:55
_reconcilerUpdateChildren @ explorev2.0.16.1.entry.js:55
_updateChildren @ explorev2.0.16.1.entry.js:55
updateChildren @ explorev2.0.16.1.entry.js:55
_updateDOMChildren @ explorev2.0.16.1.entry.js:54
updateComponent @ explorev2.0.16.1.entry.js:54
receiveComponent @ explorev2.0.16.1.entry.js:54
receiveComponent @ explorev2.0.16.1.entry.js:40
_updateRenderedComponent @ explorev2.0.16.1.entry.js:55
_performComponentUpdate @ explorev2.0.16.1.entry.js:55
updateComponent @ explorev2.0.16.1.entry.js:55
performUpdateIfNecessary @ explorev2.0.16.1.entry.js:55
performUpdateIfNecessary @ explorev2.0.16.1.entry.js:40
s @ explorev2.0.16.1.entry.js:40
perform @ explorev2.0.16.1.entry.js:40
perform @ explorev2.0.16.1.entry.js:40
perform @ explorev2.0.16.1.entry.js:40
E @ explorev2.0.16.1.entry.js:40
closeAll @ explorev2.0.16.1.entry.js:40
perform @ explorev2.0.16.1.entry.js:40
batchedUpdates @ explorev2.0.16.1.entry.js:56
l @ explorev2.0.16.1.entry.js:40
r @ explorev2.0.16.1.entry.js:55
enqueueSetState @ explorev2.0.16.1.entry.js:55
r.setState @ explorev2.0.16.1.entry.js:39
(anonymous) @ explorev2.0.16.1.entry.js:193
`

**Comment by X-Mars** [comment]
From 0.16.1 upgrade to 0.17.6
it's ok now.
thinks
