### ISSUE TITLE
SQL Lab DO not support other languages

### ISSUE THREAD

**Issue by anddyhuaa** [airbnb/superset#2730]
do againt a query using some column alias not in english, for example:
select word as 'おはようございます' from test;
select word as '你好' from test;
select word as 'أهلا و سهلا'from test;
error msg:
'ascii' codec can't encode characters in position 21-24: ordinal not in range(128)

**Comment by xrmx** [comment]
This has already been reported (just search for ascii), unfortunately nobody with the issue provided a patch fixing the issue.
