### ISSUE TITLE
dist_bar in the dashbord can't show show_bar_value

### ISSUE THREAD

**Issue by anddyhuaa** [airbnb/superset#2732]
see the following config params,show_bar_value is set 'y' but when severcal slices  added to the dashbord,they can't show the values utterly, and it's ok in the slice edit view
{
    "add_to_dash": "false", 
    "bar_stacked": "y", 
    "bottom_margin": "auto", 
    "collapsed_fieldsets": "", 
    "contribution": "false", 
    "datasource_id": "105", 
    "datasource_name": "report_pay_t0_m", 
    "datasource_type": "table", 
    "flt_col_0": "", 
    "flt_eq_0": "", 
    "flt_op_0": "in", 
    "goto_dash": "false", 
    "groupby": [
        "month"
    ], 
    "having": "", 
    "metrics": [
        "sum__pay_amt"
    ], 
    "new_dashboard_name": "", 
    "new_slice_name": "", 
    "order_bars": "y", 
    "rdo_save": "overwrite", 
    "reduce_x_ticks": "false", 
    "row_limit": "50000", 
    "save_to_dashboard_id": "", 
    **"show_bar_value": "y",** 
    "show_controls": "false", 
    "show_legend": "false", 
    "since": "100 years ago", 
    "slice_id": "57", 
    "slice_name": "t0\u4ed8\u6b3e\u6309\u6708\u7edf\u8ba1", 
    "until": "now", 
    "userid": "1", 
    **"viz_type": "dist_bar",** 
    "where": "", 
    "x_axis_label": "", 
    "y_axis_format": ".3s", 
    "y_axis_label": ""
}

**Comment by xrmx** [comment]
Please fill the required information in the issue template.

**Comment by mistercrunch** [comment]
It looks like an old version, values should be `true` or `false`, not `'true'` or `'y'`

**Comment by anddyhuaa** [comment]
there are any additional info?
Superset version
"GIT_SHA": "", "version": "0.15.4"}
Actual results
![20170510165730](https://cloud.githubusercontent.com/assets/26573576/25891129/7c2870b6-35a2-11e7-8977-4b4fbac0a527.png)

**Comment by xrmx** [comment]
@anddyhuaa you should file issues only after checking that latest release have still the same problem.

**Comment by ramugr8** [comment]
Hi All,

We are getting Data Labels on the above Bar, but we are unable to get labels on stacked bar.
![issue](https://cloud.githubusercontent.com/assets/20371395/25938217/2383f278-364c-11e7-816e-1cb419de0ffc.JPG)

**Comment by anddyhuaa** [comment]
it seems has been fiexed in the newest version 0.17.6.
as to uprade to this version, i  had to export the old version dashboard 0.15.4 to this version and got errors, but i forgot to take down the errors,so i reconfigured all of the slices and dashbords manually one by for the whole day one /sadly

**Comment by ramugr8** [comment]
Hi anddyhuaa,

Can you please help me, how can i fix colors for legends/charts ?

**Comment by mistercrunch** [comment]
@ramugr8 your question seems unrelated, I confirm that this issue is fixed in `master`
