### ISSUE TITLE
Advise against following the "visualize flow" on long queries

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/superset#2733]
The explore view typically times out at 45-60 seconds depending on setup. When users click "Visualize" in SQL Lab, we know how long the query took, so we should show an alert advising against following that flow.

"This query took ${duration} to run, and the explore view times out at ${timeout}, following this flow will most likely lead to your query timing out. We recommend your summarize your data further before following that flow. If activated you can use the `CREATE TABLE AS` feature to store a summarized data set that you can then explore."

**Comment by DuffautM** [comment]
Is there a way to increase manually the allowed duration of execution for visualization queries ?
