### ISSUE TITLE
"Timeout" error message should be clear and actionable

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/superset#2734]
Currently timeouts show as "Network Error" in many cases and that is confusing to users. A timeout should say something like "Query timeout - visualization query are set to time out at ${timeoutDuration}. Perhaps your data has grown, your database is under unusual load, or you are simply querying a data source that is to large to be processed within the timeout range. If that is the case, we recommend that you summarize your data further."

**Comment by graceguo-supercat** [comment]
verified in superset-staging:
https://superset-staging.d.musta.ch/superset/explore/table/4487/?form_data=%7B%22y_axis_zero%22%3A%20false%2C%20%22y_axis_label%22%3A%20%22%22%2C%20%22resample_fillmethod%22%3A%20null%2C%20%22show_brush%22%3A%20false%2C%20%22line_interpolation%22%3A%20%22linear%22%2C%20%22show_legend%22%3A%20true%2C%20%22groupby%22%3A%20%5B%22dim_mt_product%22%5D%2C%20%22filters%22%3A%20%5B%7B%22col%22%3A%20%22dim_mt_product%22%2C%20%22val%22%3A%20%5B%22experiences%22%5D%2C%20%22op%22%3A%20%22not%20in%22%7D%5D%2C%20%22granularity_sqla%22%3A%20%22ds%22%2C%20%22x_axis_label%22%3A%20%22%22%2C%20%22rolling_type%22%3A%20%22None%22%2C%20%22viz_type%22%3A%20%22line%22%2C%20%22show_markers%22%3A%20false%2C%20%22since%22%3A%20%2228%20days%20ago%22%2C%20%22y_log_scale%22%3A%20false%2C%20%22time_compare%22%3A%20null%2C%20%22until%22%3A%20%22now%22%2C%20%22resample_rule%22%3A%20null%2C%20%22period_ratio_type%22%3A%20%22growth%22%2C%20%22y_axis_format%22%3A%20%22.3s%22%2C%20%22x_axis_format%22%3A%20%22smart_date%22%2C%20%22metrics%22%3A%20%5B%22sum__m_pdps_viewed_last7d%22%5D%2C%20%22timeseries_limit_metric%22%3A%20null%2C%20%22slice_id%22%3A%209186%2C%20%22time_grain_sqla%22%3A%20%22Time%20Column%22%2C%20%22resample_how%22%3A%20null%2C%20%22having%22%3A%20%22%22%2C%20%22rich_tooltip%22%3A%20true%2C%20%22limit%22%3A%2050%2C%20%22datasource%22%3A%20%224487__table%22%2C%20%22x_axis_showminmax%22%3A%20true%2C%20%22contribution%22%3A%20false%2C%20%22where%22%3A%20%22%22%2C%20%22num_period_compare%22%3A%20%22%22%7D
