### ISSUE TITLE
Flipping or changing axis

### ISSUE THREAD

**Issue by jerryhall** [airbnb/superset#2739]
Could anyone explain how I would change axis in my bar chart? I have over 100 columns and about 5 rows and the table is unusable because of width limitations. 

Here's my existing parameters for the chart:
`{"bottom_margin": "auto", "y_axis_label": "", "row_limit": null, "reduce_x_ticks": false, "filters": [{"col": null, "val": "", "op": null}], "show_controls": false, "granularity_sqla": null, "viz_type": "dist_bar", "since": "100 year ago", "x_axis_label": "", "order_bars": true, "until": "now", "columns": [], "show_bar_value": false, "y_axis_format": ".3s", "metrics": ["count"], "slice_id": 41, "where": "lic_app = 'APP'", "show_legend": true, "having": "", "datasource": "9__table", "contribution": false, "time_grain_sqla": null, "groupby": ["prem_city", "lic_app"], "bar_stacked": false}`

Also, is there any resource outside of the official documentation that could help answer questions like this? Thanks much!

**Comment by jerryhall** [comment]
Took to Gitter.

**Comment by KarlaCarvajal** [comment]
I have been the same problem, do you have the answer yet?
