### ISSUE TITLE
/bin/sh: gunicorn: command not found 

### ISSUE THREAD

**Issue by X-Mars** [airbnb/superset#2748]
centos 7.2
system-python：2.7
new-python：3.4.6
1. My system-python is 2.7，and i make a new-python is 3.4.6，new-python dir is /usr/local/python3.4.
2. install superset whit `/usr/local/python3.4/bin/pip3.4 install superset`,it's ok.
3. `/usr/local/python3.4/bin/superset runserver ` ，
i got error 
`Loaded your LOCAL configuration at [/app/superset/superset_config.py]
Starting server with command: gunicorn -w 2 --timeout 60 -b  0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 superset:app
/bin/sh: gunicorn: command not found `
4. i edit `./lib/python3.4/site-packages/superset/cli.py` at line 67
Modified `gunicorn ` to `/usr/local/python3.4/bin/gunicorn `.  
i can run `/usr/local/python3.4/bin/superset runserver ` now.

**Comment by xrmx** [comment]
Create a python virtualenv, activate it and then install superset inside it. See http://airbnb.io/superset/installation.html#python-virtualenv

**Comment by OGx09** [comment]
Hi @xrmx , the link you shared is down.
