### ISSUE TITLE
SSO(Single Sign-on)

### ISSUE THREAD

**Issue by xyhc** [airbnb/superset#2767]
I want to integrate the Superset with my web project, but I am a new hand of python, How can I implement SSO with Superset ?  Please HELP ME !!!

**Comment by timfeirg** [comment]
this is probably not the best place to ask such a question.
superset uses flask-appbuilder which supports oauth2 out of the box, you should check out [their documentation](http://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth)
