### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

### ISSUE THREAD

**Issue by elkan1788** [airbnb/superset#2771]
Make sure these boxes are checked before submitting your issue - thank you!

[-] I have checked the superset logs for python stacktraces and included it here as text if any
[-] I have reproduced the issue with at least the latest released version of superset
[-] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.2

### Expected results
Graphic a column diagram product sales group by date.

### Actual results
Throws an exception: `UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)`
Detail Stack Info:
```
2017-05-17 17:27:56,137:INFO:root:SELECT `TIMESTAMP` AS `TIMESTAMP`, product AS product, COUNT(*) AS count 
FROM ja_act_lotterylog 
WHERE `TIMESTAMP` >= STR_TO_DATE('2016-11-20 17:27:56', '%%Y-%%m-%%d %%H:%%i:%%s') AND `TIMESTAMP` <= STR_TO_DATE('2016-11-30 17:27:56', '%%Y-%%m-%%d %%H:%%i:%%s') GROUP BY `TIMESTAMP`, product ORDER BY count DESC 
 LIMIT 50000
2017-05-17 17:28:05,548:ERROR:root:'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/superset/viz.py", line 237, in get_payload
    data = self.get_data(df)
  File "/usr/lib/python2.7/site-packages/superset/viz.py", line 1113, in get_data
    x = str(x)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
2017-05-17 17:28:05,551:INFO:root:Caching for the next 600000 seconds
```

### Steps to reproduce
Add a MySQL datasource and table, then click Sources --> Tables --> Query, after that show result like below:
![snapshot2017-05-17-5.33.17.png](http://7xi700.com1.z0.glb.clouddn.com/snapshot2017-05-17-5.33.17.png-alias "snapshot2017-05-17-5.33.17.png")

MySQL table data:
![snapshot2017-05-17-5.33.38.png](http://7xi700.com1.z0.glb.clouddn.com/snapshot2017-05-17-5.33.38.png-alias "snapshot2017-05-17-5.33.38.png")

> Remember that some meta data use in Chinese.

**Comment by mistercrunch** [comment]
You can try to set the charset in the database url.
```
SQLALCHEMY_DATABASE_URI = 'mysql://user:pass@localhost/db?charset=utf8'
```

**Comment by mistercrunch** [comment]
Also if you're not using py3 it may help

**Comment by elkan1788** [comment]
Yeah, there I had try add charset at DB url, but not any effect. And next time add reset default encoding in `superset.py` then get result success.

```
import sys 
reload(sys) 
sys.setdefaultencoding('utf-8') 
```

**Comment by RichardKyire** [comment]
@elkan1788 
both of your suggection i had try.but it do not work again.if i use superset runserver -d,run the server in debug mode ,it can work .do you know what 's the matter about that?

**Comment by elkan1788** [comment]
@RichardKyire  I don't known the deep reason. May you can check the DB environment suggest to use the "UTF-8" charset.
