### ISSUE TITLE
How to install superset without creating an admin user ?

### ISSUE THREAD

**Issue by gamebusterz** [airbnb/superset#2786]
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version 0.18.2

How can I install/user superset without creating an admin user. I followed [this](http://airbnb.io/superset/installation.html#superset-installation-and-initialization) guide but skipped the creating admin user part (`fabmanager create-admin --app superset`). Now when I run `superset runserver` and go to the web-ui, how do I login ?
 
I tried using my default username and password for my Linux account which I installed superset in, but it didn't work. 

So, is there no way to use Superset without creating an admin account ?

**Comment by xrmx** [comment]
What's wrong in creating an admin user *inside* superset?

**Comment by gamebusterz** [comment]
Oops

**Comment by mbadrADS** [comment]
When I  tried to create an admin user I had this error:
" Was unable to import superset Error: cannot import name 'quoted_name' "
Anyone have an idea about this issue?

Thanks

**Comment by akuckartz** [comment]
@mbadrADS Maybe you should create a new issue instead of asking in this closed issue?
