### ISSUE TITLE
Edit Dashboard title and Slice title in place

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/superset#2796]
Currently the only way to edit the title of a dashboard or a slice is to use the CRUD view provided by FAB. 

Instead of that, it'd be nice to have a way to edit the name in-place, the same way that it's done in Google docs for instance.

**Comment by ascott** [comment]
google docs example:
![edit-name-inline](https://cloud.githubusercontent.com/assets/130878/26324897/91092c00-3ee9-11e7-8c82-d88b074b3928.gif)

- clicking outside the editable field or hitting enter should save the new name
- use the `notify` module to give user feedback
https://github.com/airbnb/superset/blob/master/superset/assets/javascripts/SqlLab/components/VisualizeModal.jsx#L153

**Comment by jeffcarey** [comment]
Does this supersede #2726 then? I had something started on that.

**Comment by mistercrunch** [comment]
Oh I forgot I had opened it. Closing #2726
