### ISSUE TITLE
Default Decimal Place - all results showing as .0 

### ISSUE THREAD

**Issue by jerryhall** [airbnb/superset#2799]
After creating slices, my pivot tables and some bar chart tables are returning whole count numbers with a .0 after each. This is extraneous as I typically don't work with any fractions. 

Is there a way to change the default and where would I do that? Thanks much!

**Comment by mistercrunch** [comment]
You should be able to change the `Y Axis formating` on bar chart and the `number format` on the pivot (only in recent versions I think)

**Comment by jerryhall** [comment]
Thanks @mistercrunch  I don't see how to find the current available version number. I have .17 installed. For the pivot tables is there a way not in the interface where I could update the number format? I believe I should use ,.2r to get the 4,000 format.

**Comment by mistercrunch** [comment]
I'm positive these issues have been fixed since 0.17.
