### ISSUE TITLE
[Database] inspector can't get sqlalchemy dialect's function

### ISSUE THREAD

**Issue by zhangjiajie023** [airbnb/superset#2803]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

### Expected results
the Database.inspector can get dialect's function in sqlalchemy.

### Actual results
I can test this function in `sqlalchemy` project, but can't call it in `superset`
```
  File "/home/jojo/project/superset/superset/superset/models.py", line 869, in all_schema_table_names
    st_list = self.inspector.get_schema_and_table_names()
AttributeError: 'Inspector' object has no attribute 'get_schema_and_table_names'
```

### Steps to reproduce
1. Months ago, I added my dialect and many functions in `sqlalchemy`, such as: `get_schema_names(self, connection, **kw)` ...
2. Now add a new function `get_schema_and_table_names(self, connection, **kw)`;
3. I can test this function in `sqlalchemy` project, but can't call it in `superset`

this is the issue related to sqlalchemy, if can get help here, should be grateful

**Comment by xrmx** [comment]
If `get_schema_and_table_names`is code outside superset and you have an old modified of superset so use it i can't see how we can help here.

**Comment by zhangjiajie023** [comment]
@xrmx ok, tks all the same

**Comment by xrmx** [comment]
Any chance you can rebase your work and make it public?

**Comment by zhangjiajie023** [comment]
@xrmx here is my test code:
```
engine = create_engine(xxx)
conn = engine.connect()
dialect = MyDialect()
rs = dialect.get_schema_and_table_names(conn)   # works

insepector = sqla.inspect(engine)
rs = inspector.get_schema_names()   # works
rs = inspector.get_schema_and_table_names()   # AttributeError
```

```
def get_schema_names(self, connection, **kw)
def get_schema_and_table_names(self, connection, **kw)
```
The two functions have the same definitions and in the same class. Could it caused by `sqla.inspect`?

**Comment by xrmx** [comment]
The error clearly shows there's no get_schema_and_table_names in what `sqla.inspect(engine)` returns. Also it's completely unrelated to superset since you are calling sqlalchemy straight.

**Comment by zhangjiajie023** [comment]
#xrmx yes, it's slqalchemy's issue
