### ISSUE TITLE
SQL expression of column not respected in metric

### ISSUE THREAD

**Issue by rumbin** [airbnb/superset#2806]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

I do not expect this issue to be fixed in the latest release, as the changelog does not suggest so.

### Superset version
0.17.4

### Expected results
A metric based on a column which is calculated via an SQL expression should actually use the defined SQL expression instead of the bare column name alias.

### Actual results
The metric (aggregatiuon function) is only applied on the column name alias, resulting in an SQL error, as the column name does not exist.

### Steps to reproduce

* Create a new column for an existing table, e.g. the difference between column_a d column_b. We assume that this new column is names diff_a_b.
* Create a metric using this new column, e.g. max(dif_a_b) as max__diff_a_b.
* Create a slice using this new metric.

The query of this slice will fail with a message that the column diff_a_b does not exist.

## Remarks

I do understand that the metric is just an aggregation function of the SQL query. I also understand that I could as well just define the metric as max(column_a - column_b) instead of max(diff_a_b).

However, from a user's point of view it is not transparent which of the table columns (as defined in superset) can directly be used in metrics and which columns can not, as they are only calculated ones.

**Comment by mistercrunch** [comment]
There's something nice and simple around the current behavior where the SQL expression for the metric is just what it is, there's no magic trying to parse the expression and resolve it. Potentially that would be complex, brittle and perhaps confusing.`SQL expression` is executed as is.

Note that we support jinja templating in those expression, but there's no easy way to share variables across the different expressions. Maybe as we introduce a DSL for the semantic layer, it would be possible to define and share expressions in the templating layer.
