### ISSUE TITLE
big num with trend line: strange results. 

### ISSUE THREAD

**Issue by afsmith** [airbnb/superset#2807]
Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if any
- [X ] I have reproduced the issue with at least the latest released version of superset
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"GIT_SHA": "", "version": "0.18.2"}

### Expected results

When using 'big number with trend line, the number shown is consistent with big num, and table view.

### Actual results
Big num shows the correct value, as does table big num with trend line shoes something else.

### Steps to reproduce
Using this data:
__timestamp	sum__price
5/24/17 14:27	160
5/24/17 14:30	170
5/24/17 14:35	230
5/24/17 14:41	161
5/24/17 14:45	90
5/24/17 14:48	170
5/24/17 14:54	133.3300018
5/24/17 14:56	170
5/24/17 15:09	0

This data came processed via superset csv export. It matches the source data

Ok:
![big_num](https://cloud.githubusercontent.com/assets/496726/26403621/90b14850-4097-11e7-96b4-cb8bd38fcfe5.png)

Change type to big num with trend line:
![big_num_with_timeline](https://cloud.githubusercontent.com/assets/496726/26403655/a6eb553e-4097-11e7-900a-807a9648727b.png)

**Comment by mistercrunch** [comment]
`Big Number with Trendline` shows the last data point value in the time series. `Big number` shows the sum that applies over the period selected. If you want `Big Number` to show the latest data point, you can add some subquery in the WHERE clause as in `dt IN (SELECT max(dt) FROM foo WHERE dt > [reasonable time range])`. The WHERE [reasonable time range] in the subquery can be useful depending if that field is partitioned or indexed, avoiding an full extra table to find the max date.

**Comment by afsmith** [comment]
Ok.. My expectation was that big num with trendline would show the same value as big number: the metric over the time period.  Now I know.. thanks!
