### ISSUE TITLE
Question: Can I retrieve data from superset as JSON or XML via webservice?

### ISSUE THREAD

**Issue by steffenbrand** [airbnb/superset#2808]
Let's say I make a report that answers the question: "What's the average turnaround time for smartphones in our different repair centers?"

Now I don't only want to use the report to visualize the data in a meeting, but also to use this data in various applications. Preferably the data should be requested from a webservice that superset provides.

Is this possible? I didn't find anything like this in the documentation.

**Comment by mistercrunch** [comment]
See the json button on the upper right.
<img width="824" alt="screen shot 2017-05-24 at 8 37 21 am" src="https://cloud.githubusercontent.com/assets/487433/26412009/4ee0533e-405c-11e7-857c-0bb0500e5c02.png">

There's also a JSON endpoint you can hit behind `SQL Lab`.

In both cases you have to be authenticated and data access rules apply.

What's "XML"? </kidding>

**Comment by bivav** [comment]
> See the json button on the upper right.
> <img alt="screen shot 2017-05-24 at 8 37 21 am" width="824" src="https://cloud.githubusercontent.com/assets/487433/26412009/4ee0533e-405c-11e7-857c-0bb0500e5c02.png">
> 
> There's also a JSON endpoint you can hit behind `SQL Lab`.
> 
> In both cases you have to be authenticated and data access rules apply.
> 
> What's "XML"?

Hi,
I can export to json but I am curious as - how can I use this json chart as? Where can I use? 

Also, if you can help me with <iframe>. It tells me, 
  localhost is blocked 
  ERR_BLOCKED_BY_RESPONSE  
when I try to open in browser.

Thank you in advance!
