### ISSUE TITLE
Use metrics and columns "Verbose Name" in Table and Pivot Table headers

### ISSUE THREAD

**Issue by jerryhall** [airbnb/superset#2813]
Is there a way to change the labels for various column headings in pivot tables? 
Along those lines are there docs or writing or examples of styling options? 
I'm using Superset v.0.17 and am pulling data from my postgres tables. 
Thanks!

**Comment by mistercrunch** [comment]
We should be using the columns and metrics "Verbose Name" in that context but aren't at the moment.

**Comment by kelchm** [comment]
Similarly, the verbose name could be used in the Filter Box.

Where is the verbose name used currently? I haven't seen it show up anywhere.

**Comment by fabianmenges** [comment]
I was looking for this as well, Thanks Arijana.

**Comment by jerryhall** [comment]
I'm not getting any changes appearing in my tables after editing the data table verbose element for individual rows. Could anyone help me with this? My tables are all appearing with the column names. I'm assuming I'm able to add a Verbose name in Superset which would be the label that actually displays. Thanks!

**Comment by mistercrunch** [comment]
I pushed a PR that should help with that, though it's only fixing the Table component for now, though it sets the path forward. We'll have to address other visualizations.

**Comment by desavera** [comment]
+1 !!

**Comment by raelmiu** [comment]
Doesn't this solve the issue? https://github.com/airbnb/superset/pull/2824
