### ISSUE TITLE
alpha.1.entry.js  404 not find

### ISSUE THREAD

**Issue by wangbokun** [airbnb/superset#2817]
dashboard页面总是找不到js文件。
welcome:19 GET http://172.19.40.198:8088/static/assets/dist/css-theme.0.18.3-alpha.1.entry.js 
welcome:26 GET http://172.19.40.198:8088/static/assets/dist/welcome.0.18.3-alpha.1.entry.js

**Comment by xrmx** [comment]
Did you update the python code but didn't rebuild the frontend?

**Comment by wangbokun** [comment]
Need bash running  script    js_build.sh ?

**Comment by wangbokun** [comment]
12.7
npm ERR! npm  v2.11.3
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall read



static path,running npm install err msg is:
npm ERR! network read ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
-

**Comment by xrmx** [comment]
Just follow the documentation http://airbnb.io/superset/installation.html

**Comment by fufjvnvnf** [comment]
What do you mean by rebuilding the frontend? Do you mean to run the js_build.sh script?
