### ISSUE TITLE
[js-testing] write tests for javascripts/SqlLab/components/DataPreviewModal.jsx

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#2825]

**Comment by xrmx** [comment]
What about filling tasks in the kanban instead of opening dozens of small / short lived issues? 👍 for the testing effort.

**Comment by ascott** [comment]
closing this issue. turns out we are not using this component anymore https://github.com/airbnb/superset/pull/2882

@xrmx i don't know what the kanban is but adding the issues here make them visible to the whole community, to see the progress, and/or jump in and assign the task to themselves. since they are small tasks they are great for new contributors.

**Comment by xrmx** [comment]
@ascott the kanban is the `projects` label near the `pull requests` one :) My suggestion was to add a "improve frontend test coverage" and then track each file in a card in the kanban.
