### ISSUE TITLE
How to create a customized dashboard-based permission?

### ISSUE THREAD

**Issue by fufjvnvnf** [airbnb/superset#2914]
I essentially want to achieve what is done at https://github.com/airbnb/superset/issues/1799 . I would like to be allowed to add dashboard-based permission to user, which is similar to a database-based permission: I just iterate over each slice in the dash board and add each datasource permission to the user. However after modeling over the changes made in that thread, I'm not able to see "dashboard access on XXX" as an option when configuring permissions for each role, which is reasonable since the issue then is at version 0.14, and we are now at 0.18. How, are those permissions (datasource permissions, database permissions, etc) created in the first place? Howe should I go about modeling over the implementation of database permission to add a customized dashboard permission? Thank you!

**Comment by fufjvnvnf** [comment]
My bad I forgot to run superset init : ) Then changes at #1799 still work for current version!

**Comment by yamyamyuo** [comment]
> I would like to have all datasources in the dashboard be automatically granted permission to role once the dashboard permission has been granted, just like when granting permission to the entire database. How should I go about to change that?

So what's going on with this feature? I have the same desire...

**Comment by Ritesh205** [comment]
Could you please point out(refer me) to the changes you did in the code for the dashboard permissions ?

**Comment by starsunny** [comment]
@fufjvnvnf Can you please tell me the changes and the file path where it needs to be done?
