### ISSUE TITLE
support number right-aligning in table view

### ISSUE THREAD

**Issue by SimpleExpress** [airbnb/superset#2933]
This is an improvement suggestion.

### Superset version
15.2

### Expected results
numbers should be either right-aligned or decimal places aligned, it's better that user can control this behavior.

### Actual results
numbers in table view are left-aligned like normal text, which is not so convenient for comparison.

### Steps to reproduce
create a table view with any metrics, number values are now left-aligned and I could not found any adjustment for it. I also tried d3-format with padding but this doesn't work.

**Comment by xrmx** [comment]
Does it happen on latest release?
