### ISSUE TITLE
Pie/TimeSeries chart legends are not clickable

### ISSUE THREAD

**Issue by kkalyan** [airbnb/superset#2944]
In the earlier versions (caravel), pie/time series chart legends are clickable, giving a nice ability to include and exclude certain values. With explore-v2 this functionality is no longer there. 

Caravel - 0.10.0
![image](https://user-images.githubusercontent.com/391567/27014264-3a0baca4-4eaa-11e7-9927-cf0457270917.png)

superset - 0.18.2
![image](https://user-images.githubusercontent.com/391567/27014265-4492aa4c-4eaa-11e7-952b-4c239f8149f1.png)

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.2

**Comment by mistercrunch** [comment]
Works for me on `master`.

**Comment by kkalyan** [comment]
got it. In the previous versions labels were clickable, now only the dot before the label. Closing this.
