### ISSUE TITLE
MapboxGL: Access token issue

### ISSUE THREAD

**Issue by chandupydev** [airbnb/superset#2949]
How to resolve this this issue?
I have created one access token? and changed mapgl.jsx put my access key inplace of {this.props.mapboxApiKey} .. But still it's not working.

PS: My skill level in react is still very beginner :-) 

![misc_chart](https://user-images.githubusercontent.com/17685818/27034617-fbd911a4-4f9b-11e7-938f-68cb9c07809b.png)

**Comment by xrmx** [comment]
You have to configure it in settings without changing the code:
http://airbnb.io/superset/installation.html#configuration
