### ISSUE TITLE
How to add new visualization type??

### ISSUE THREAD

**Issue by Subhash9325** [airbnb/superset#2962]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
You can take a look at this PR https://github.com/airbnb/superset/pull/2708 especially:

- superset/assets/backendSync.json
- superset/assets/javascripts/explorev2/stores/controls.jsx
- superset/assets/visualizations/main.js
- superset/viz.py

Plus of course your specific js.

**Comment by Subhash9325** [comment]
Thanks xrmx

**Comment by mistercrunch** [comment]
For the record `superset/assets/backendSync.json` is generated with the `npm run backend-sync` command

**Comment by Subhash9325** [comment]
@mistercrunch  how move chart - function works...?? i know its using react, react-redux... can u explain??

**Comment by Subhash9325** [comment]
@mistercrunch or @xrmx  how charts are moving inside dashboards??

**Comment by mgulaydin** [comment]
@mistercrunch > For the record `superset/assets/backendSync.json` is generated with the `npm run backend-sync` command

(senv) [root@blade02 assets]# pwd
/root/incubator-superset/superset/assets
(senv) [root@blade02 assets]# npm run backend-sync
npm ERR! missing script: backend-sync

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-05T11_49_42_150Z-debug.log

I run the command but this error show up. Where should i run this command? Thanks
