### ISSUE TITLE
overriding config with SUPERSET_CONFIG_PATH env variable not working

### ISSUE THREAD

**Issue by tclass** [airbnb/superset#2982]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.4

### Expected results
creating tables in postgres

### Actual results
created sqllite db

### Steps to reproduce
SQLALCHEMY_DATABASE_URI = 'postgresql://supersetdb:xxx@somehost/supersetdb'
The database is outside of the docker container, user and password are correct, it loads the config.py, at least it says so.

```Loaded your LOCAL configuration at [/home/superset/.superset/config.py]
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.```

**Comment by andrewmchen** [comment]
I have the same issue. It looks like superset doesn't initialize the config correctly from the CONFIG_MODULE.

If you run 
```
import superset
superset.app.config.get('SQLALCHEMY_DATABASE_URI')
```
You'll get the sqlite path.

**Comment by xrmx** [comment]
How are you starting superset?

**Comment by andrewmchen** [comment]
Easy workaround is to just use the `PYTHONPATH` method of loading the config.

**Comment by tclass** [comment]
@xrmx I set the environment variable: SUPERSET_CONFIG_PATH: /home/superset/.superset/superset_config.py

**Comment by aquinovo** [comment]
> Easy workaround is to just use the `PYTHONPATH` method of loading the config.

How do I add my configuration file to PYTHONPATH?

**Comment by andrewmchen** [comment]
It's been a while since I've done this but if I recall correctly it's like this: https://superset.incubator.apache.org/faq.html#why-does-flask-fab-or-superset-freezed-hung-not-responding-when-started-my-home-directory-is-nfs-mounted

**Comment by aquinovo** [comment]
> It's been a while since I've done this but if I recall correctly it's like this: https://superset.incubator.apache.org/faq.html#why-does-flask-fab-or-superset-freezed-hung-not-responding-when-started-my-home-directory-is-nfs-mounted

Thanks.
