### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by gzponline** [airbnb/superset#2997]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
17.1

### Expected results
![image](https://user-images.githubusercontent.com/12186221/27320133-5908370c-55c7-11e7-948b-411822264b39.png)

### Actual results
npm install succeed

### Steps to reproduce

- change the npm as cnpm ==> [淘宝镜像](https://npm.taobao.org/) to download quickly (npm install will long long long time )
- cnpm install 
- stop at request module

**Comment by mistercrunch** [comment]
"*optional* install error"

**Comment by Subhash9325** [comment]
@mistercrunch can u please explain me how move chart works using react at least tell m files??

**Comment by gzponline** [comment]
@mistercrunch  can I skip this module if can how to do

**Comment by timfeirg** [comment]
I think you can safely ignore that error, it'll work just fine @gzponline

**Comment by Subhash9325** [comment]
@gzponline u can escae it.. don't worry it will work fine

**Comment by gzponline** [comment]
@Subhash9325  but npm must install this then go on how to ignore this

**Comment by mistercrunch** [comment]
It's an optional dependency that is only necessary when on osx
