### ISSUE TITLE
Where is Move Chart Function definition?? 

### ISSUE THREAD

**Issue by Subhash9325** [airbnb/superset#2999]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by xrmx** [comment]
Please don't open bugs if you have already asked question in other bugs. Especially if you got answers. Ref #2962

**Comment by Subhash9325** [comment]
@xrmx  please tell m how charts are moving inside dashboards>>???

**Comment by Subhash9325** [comment]
But how charts r moving inside dashboards??? Please explain dude

On 20 Jun 2017 3:30 p.m., "Riccardo Magliocchetti" <notifications@github.com>
wrote:

Please don't open bugs if you have already asked question in other bugs.
Especially if you got answers. Ref #2962
<https://github.com/airbnb/superset/issues/2962>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/airbnb/superset/issues/2999#issuecomment-309705925>,
or mute
the thread

**Comment by Subhash9325** [comment]
Will u reply I'm in hurry

On 20 Jun 2017 3:42 p.m., wrote:

But how charts r moving inside dashboards??? Please explain dude

On 20 Jun 2017 3:30 p.m., "Riccardo Magliocchetti" <notifications@github.com>
wrote:

Please don't open bugs if you have already asked question in other bugs.
Especially if you got answers. Ref #2962
<https://github.com/airbnb/superset/issues/2962>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/airbnb/superset/issues/2999#issuecomment-309705925>,
or mute
the thread
