### ISSUE TITLE
Can't find superset_config.py !

### ISSUE THREAD

**Issue by DylanCa** [airbnb/superset#3024]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version 

0.18.4

### Expected results

Finding superset_config.py wherever it is supposed to be, but just finding an empty folder instead

### Actual results

Nothing in the folder where superset_config.py is supposed to be

![superset config](https://user-images.githubusercontent.com/2054131/27439856-4dcb0484-5769-11e7-9738-1da85b5fc1df.png)

**Comment by xrmx** [comment]
Why should anyone here know where did you put your files?

**Comment by DylanCa** [comment]
Well, because during the install process, the superset_config.py file never showed up, but the "locate" command just tells me that it is in the /superset folder, even if it's not.

I was wondering if anyone ever had the same issue. I'm not asking you 'Where did I put my file ?', just asking you if "invisible files" is a common issue or not.

**Comment by xrmx** [comment]
First locate works on a *cache* not on the file system. `ls` does though and is telling you that there's nothing other than superset_env. Second there's no superset_config.py that should show up.

**Comment by xrmx** [comment]
And the morale of this is please use find and forget about locate :)

**Comment by DylanCa** [comment]
I will, from now on ! 

Just a last thing I don't understand. Am I not supposed to have a superset_config.py file here ?

**Comment by xrmx** [comment]
You may have a file named superset_config.py but you should create it http://airbnb.io/superset/installation.html#configuration

**Comment by DylanCa** [comment]
Okay, I'm pretty sure the file was automatically created with the previous version, must have been drunk during the installation.

Thank you, and sorry for the disturbance ! :)

**Comment by Navya-Prakash** [comment]
I have'nt installed apache superset but i have cloned the whole repo, even i'm trying to find out where superset_config.py is , 
found one in docker folder but its not relevant. Do we have any other name or such for this file?
