### ISSUE TITLE
Fix the Gamma role user experience

### ISSUE THREAD

**Issue by alanmcruickshank** [airbnb/superset#359]
While logged in as a user without access rights to save new dashboard positioning and css, if they click the "Save the current positioning and CSS" button, they get a modal message "Success, This dashboard was saved successfully." although it hasn't been successful (and if you reload the dashboard the changes have not been saved - which is the correct behaviour for a user without sufficient rights).

Either the modal message should say "Unable to save dashboard due to insufficient access permissions", or the save button should be hidden for users without sufficient rights. I think one tidy solution might be to hide/disable the entire multi-button (refresh, filter, css, edit, save) for users without edit rights.

**Comment by mistercrunch** [comment]
Right. We need to iron out the gamma user experience and fix some other things around security. It's pretty rough right now.

**Comment by sid88in** [comment]
I have disabled these features in #298 based on access permissions. They cannot be clicked if the user does not have respective access permissions.

**Comment by alanmcruickshank** [comment]
#298 looks great for slices, any chance we could do something very very similar for dashboards too?

**Comment by sid88in** [comment]
I added features for dashboard as well in the same PR. Saving dashboard etc is disabled now.

**Comment by xrmx** [comment]
On current master the "Save the current positioning and CSS" does not give any feedback when the save fails. I think we just need to disable the button if the user don't have enough permissions to save it. Same goes for "Add a new slice to the dashboard"
