### ISSUE TITLE
Ability to create Label Replacement Tables

### ISSUE THREAD

**Issue by JohnOmernik** [airbnb/superset#520]
When creating slices, lets say we have a table that a field "gender" and the values are 1 and they are 2.  (1 being female, 2 being male)
I can do a nice pie chart showing the distribution of the genders grouped by field gender.  It shows 58% 1 and 42% 2.  

I know what that means, but without having to change my source table, or create new fields that do a SQL CASE statement, what if we could create a simple "replace" matrix in the slice creation. 
- 1 -> Female
- 2 -> Male

All this would do is update the labels on the vis, not the actual data itself.  It would be stored with the slice, and wouldn't effect the underlying queries or data sets.

**Comment by XiaodiKong** [comment]
@georgeke I also want to take sum__*** replace the real meaning, can I?

**Comment by JohnOmernik** [comment]
@XiaodiKong Are you thinking about the actual "metric" names? You can redefine what the Metric names are in the table editing screen. 

So you could take "sum" and name it via the Metric name you even have control over the expression that is grouped, so you could do "sum(somefield) and name it "sum_field" there. 

What I am looking to do with this issue is for fields that just don't "look" pretty (the 1 -> Female, 2 -> Male example) or Lets say you have a field that is an abbreviation for departments in your company:

HR -> Human Resources
Acct -> Accounting
Op -> Operations
IT -> Information Technology

For columns or for metrics, you could attach a "lookup" table that any time the values were displayed, Caravel would try a simple replacement if value to be displayed = "lookup value" than instead replace the value.  

This would have no impact on the SQL, and you wouldn't be able to change how the visualizations compute things, this would be on the labels only.  Additionally, we should probably limit the size of the tables to say "50" for performance reasons. If you have more that 50 values, it would be tedious to create the lookup tables, and you may be better off with a join, I am talking about presentation layer only for this request.  The idea being in the case of the Abbreviations, I could show the vis on a dashboard as is, but if I want it to look really good, then I can alter the final output and get that 100% I am looking for. 

(Also: If no lookup value if found, obviously default to the real value)

**Comment by deepish** [comment]
+1 for this feature

**Comment by shailesh2k9** [comment]
+1 for this feature

**Comment by mistercrunch** [comment]
For now the solution to this is to create a calculated column as a case when statement or handling it upstream in a pipeline or a view.

If Superset was to allow for a mapping construct in the UI, it should probably be reusable across Slices and Datasources. Assuming mapping often means grouping as in mapping goes many-to-one, it would have to be translated to a case-when expression so that the db itself performs the proper grouping. 

There would also be a need to add some UI component that applies mappings to columns on top of that.

Another approach would be in the direction of a comprehensive sql expression editor, perhaps more integrated as a popover in the explore view. My vote goes in that direction.

**Comment by gzbigegg** [comment]
@mistercrunch Can you give an example of a calculated column approach?

**Comment by mistercrunch** [comment]
<img width="608" alt="screen shot 2017-05-09 at 12 57 07 am" src="https://cloud.githubusercontent.com/assets/487433/25840876/81f094a2-3452-11e7-9c77-6d7aaba474c9.png">

**Comment by gzbigegg** [comment]
@mistercrunch Thanks a lot.

**Comment by suuuch** [comment]
@mistercrunch Thanks a lot .
 And I have a new problem, I need to filter data use this column ,but SQL just like this:
```
SELECT *
FROM dwmkt.fct_fin_invest_summary
WHERE  case sex
          when 1 then 'Female'
          when 2 then 'Male'
          else 'Unknow'
      end != case sex
          when 1 then 'Female'
          when 2 then 'Male'
          else 'Unknow'
      end
```
Can you tell me how to do it , Please?
Thanks.
