### ISSUE TITLE
default order on  the distribution bar chart

### ISSUE THREAD

**Issue by witwall** [airbnb/superset#525]
I notice the default is order by main_metric desc 
how about let us select the order by condition?

for example, the following query 

``` sql
SELECT date_part::text AS date_part,
       SUM(total_sales) AS sum__total_sales
FROM d1
GROUP BY date_part::text 
LIMIT 5000
```

I want to order by date_part asc, not order by sum__total_sales desc

**Comment by georgeke** [comment]
#519

**Comment by skyyk** [comment]
in the caravel, how to remove the default order by.Eg: the query sql end--ORDER BY count DESC-- LIMIT 5000
tks!

**Comment by Towhid1** [comment]
Is there any way for distribution bar chart y axis ascending sort? My use case is to show 10 worst performing products?
