### ISSUE TITLE
Caravel with HTTPS in gunicorn

### ISSUE THREAD

**Issue by EstebanMonge** [airbnb/superset#533]
Hello I am trying to add HTTPS to Caravel... I made a hack:
/usr/local/bin/caravel (VPS, Debian 8 64bits)

```
        cmd = (
            "gunicorn "
            "-w {workers} "
            "--timeout {timeout} "
            "--certfile=/etc/ssl/certs/7524b7242d4e83b4.crt "
            "--keyfile=/etc/ssl/private/server.key "
            "-b 0.0.0.0:{port} "
```

It works. But I want to pass with arguments the values... in future updates I don't want to repeat the task.

I modify the caravel binary, I add to options:

```
@manager.option(
    '-t', '--timeout', default=config.get("CARAVEL_WEBSERVER_TIMEOUT"),
    help="Specify the timeout (seconds) for the gunicorn web server")
@manager.option(
    '-c', '--certfile', default="",
    help="Specify certificate path of https for the gunicorn web server")
@manager.option(
    '-k', '--keyfile', default="",
    help="Specify key path of https for the gunicorn web server")
```

And:

``````
   else:
        cmd = (
            "gunicorn "
            "-w {workers} "
            "--timeout {timeout} "
            "--certfile={certfile} "
            "--keyfile={keyfile} "
#           "--certfile=/etc/ssl/certs/7524b7242d4e83b4.crt "
#           "--keyfile=/etc/ssl/private/server.key "
            "-b 0.0.0.0:{port} "
 #```

But didn't works.

The idea to post this issues is share the hack and if someone wants to able https in a better way help me to make a better hack and pass arguments from command line.
``````

**Comment by xrmx** [comment]
Better put an http proxy like nginx before gunicorn and do the ssl termination there. There's nothing caravel specific so you should find plenty of examples on the internet.

**Comment by EstebanMonge** [comment]
I like the idea to have a "pure python" solution without third party things...

**Comment by mistercrunch** [comment]
It's really easy to just run the gunicorn process yourself too.

**Comment by EstebanMonge** [comment]
Hello I upgrade to 0.15 and start server is different.

I installed Superset in virtualenv in /opt/superset.

So you can run manually gunicorn or superset with this command:
cd /opt/superset/lib/python3.4/site-packages
nohup gunicorn --certfile=/etc/ssl/certs/4ccf2cbf0009d8e9.crt --keyfile=/etc/ssl/private/server.key -b 0.0.0.0:8088 superset:app &

**Comment by Jie-Yang** [comment]
I am having a similar problem: HTTP works perfectly, but when I config ALB with HTTPS, always get error 502 Bad gateway. 

I have tried:
set ENABLE_PROXY_FIX = True in superset_config,
and set FORWARDED_ALLOW_IPS=* as Environment variable, 

but not luck.

FYI, my Gunicon version is 19.7.1, superset is 0.18.5.

I am wondering whether there is anything else I can try? I tried to replicate the error locally with haproxy, but it seems that haproxy does not have the problem, only ALB has this error. I have sent the whole days on it, but no progress at all. Any help and tips are appreciated !

Thanks
Jay

**Comment by sandipsinha** [comment]
we are having the same issue. This is a very common reuirement and I am surprised that I have to do so much digging and apparently there is no easy fix...

- Sandip

**Comment by pexpert9** [comment]
Hi,
1. How  can i set SSL certificate files setting in gunicorn ?
2. Is any specific command or file for SSL configuration, If yes please explain ...

**Comment by mistercrunch** [comment]
Please refer to the gunicorn docs for this.
