### ISSUE TITLE
Frequent Worker Timeout

### ISSUE THREAD

**Issue by tylerFowler** [airbnb/superset#546]
I'm using Caravel in front of a PostgreSQL database and I'm finding that I get a lot of messages like these in the logs:

``` bash
[23] [CRITICAL] WORKER TIMEOUT (pid:37)
[96] [INFO] Booting worker with pid: 96
```

Followed by a big red box that says '502 Bad Gateway' from Nginx where the query results usually are. On the Nginx side I'm seeing corresponding logs with messages like:

``` bash
upstream prematurely closed connection while reading response header from upstream
```

It's also worth noting that my Postgres servers are a master & and a replica in hot standby mode both behind a PGPool II server, so perhaps it's that different workers go to potentially different database servers? In any case I can't figure out what might be wrong on my end so I thought I'd check here to see if it's just me. It seems to be a fairly random occurrence but definitely frequent enough to be inconvenient.

**Comment by mistercrunch** [comment]
Isn't it just Gunicorn timing out when you run long queries?

**Comment by tylerFowler** [comment]
That's what is interesting because I'll get that 'worker timeout' typically between 30 - 60 seconds but I've definitely run queries for longer than that without getting a timeout. The other day I looked into it a little more and found that even after I get the error I can run `select * from pg_stat_activity` and see that the worker running my query is still running and usually will run to completion. So it's almost like the connection to the worker from the main app is being lost or something.

I have very little experience with Python web frameworks or gunicorn so it's hard for me to tell where even to look to see what's really going on.

**Comment by tylerFowler** [comment]
Quick update, I played around with some timeouts and am getting better results, still can't explain why it would fail at different time intervals instead of being consistent. However, now I have an issue where after a really long running query (~300s) it just gives me back the red box indicating error but it's just empty (i.e. no message from nginx). Though once again in Postgres I can still see that the worker is still running the query, if that's expected behavior then it's no problem.

**Comment by brutus333** [comment]
I see similar behavior with Superset running slow queries in an Oracle DB - the "Worker timeout" message in logs:

> 2/2/2017 8:55:32 AM[2017-02-02 08:55:32 +0200] [1] [CRITICAL] WORKER TIMEOUT (pid:119)
> 2/2/2017 8:55:33 AM[2017-02-02 08:55:33 +0200] [123] [INFO] Booting worker with pid: 123

 and 

> undefined 
> An unknown error occurred. (Status: 0) Maybe the request timed out?

 

message in the UI. Usually, the timeout occurs at ~30s but I saw rare cases when the timeouts occurs at ~50s. I tried everything I could, I changed to async workers with celery but I still get the timeouts. I also adjusted SUPERSET_WEBSERVER_TIMEOUT without any change in behavior.

I don't know where this timeout comes from, please advice.

Thank you,
Virgil

**Comment by tylerFowler** [comment]
I finally figured out how to fix this issue, I'm not sure what `SUPERSET_WEBSERVER_TIMEOUT` does but it doesn't seem to change the actual worker timeout. However the `runserver` command has a `-t` flag that does control the timeout.

So something like this should set the timeout to 90 seconds:
`superset runserver -t 90`

**Comment by desavera** [comment]
I am currently using the -t flag but still facing the same issue ... my queries are being interrupted around 50segs ... any tip on this please ?

**Comment by mistercrunch** [comment]
Web requests are supposed to time out. Your webserver or proxy (if you use one) is likely set to timeout somewhere between 30-60 seconds. The real solution to this is to setup an async backend for SQL Lab.

**Comment by desavera** [comment]
Hey, thanks for the answer ... the solution for this is to use SUPERSET_WEBSERVER_TIMEOUT ... it is tricky as the two approaches for starting Superset are conflicting ... you EITHER use a config file OR use command line params (ex : -t) ... it is now going over 50segs ... THANKS !

**Comment by lexmiln** [comment]
In case you land here after Googling this error message: I saw these worker timeouts after deploying the `amancevice/superset` docker image to a Kubernetes cluster for the first time, however, it was only a temporary issue that was resolved once I'd run `superset-init` to create the admin account and complete the setup process.
