### ISSUE TITLE
[Suggestion] Add a date picker (like one appeared on Airbnb's homepage) with similar functionality like filtre_box so that user can select date range

### ISSUE THREAD

**Issue by izzyleung** [airbnb/superset#767]
Although we can use "Range filter" functionality to select a specific time range for "Time Series - Line Chart", it would be better to have a date picker (or even time picker) that user can add to a dashboard, so that all the result in that time range will be filtered out.

**Comment by CaraWuu** [comment]
You can select time range from "Time Grain".

**Comment by kkalyan** [comment]
@CaraWuu Care to explain what is 'Time Grain' ? 

Related: https://github.com/airbnb/caravel/issues/665

**Comment by xrmx** [comment]
Closing as dup of #1318
