### ISSUE TITLE
caravel can not use greenplum4.3(Postgresql 8.3)  as datasource

### ISSUE THREAD

**Issue by qiutiaoming** [airbnb/superset#782]
```
System version: Centos 6.3
PostgreSQL 8.3devel (Greenplum Database 4.3.99.00 build dev)
```

I can use select statements in  /caravel/sql/\* , but could not create table from datasource in caravel.below are some exception information.

![image](https://cloud.githubusercontent.com/assets/5118099/16951252/c84275e4-4df6-11e6-936c-70159e6086eb.png)

**Comment by mistercrunch** [comment]
What postgres driver are you using? What's does your SqlAlchemy URI look like? I don't know much about Greenplum but I'd try something that starts with `postgresql+psycopg2://`

**Comment by qiutiaoming** [comment]
Thanks @mistercrunch , 
driver: ` psycopg2 v2.5 ` , a bit older version of psycopg2,because, when I  install the newest one, pip throw exception. 
 SqlAlchemy url: `postgresql+psycopg2://`

**Comment by phreatom** [comment]
Greenplum 4.3 does work with caravel. I use a url like `postgresql://` and `psycopg2 v2.6.2`

**Comment by xrmx** [comment]
Closing then, thanks @phreatom for the update!

**Comment by mistercrunch** [comment]
Added an entry in the docs for greenplum
https://github.com/airbnb/superset/commit/84b98c234f852550ecf536e4a6e7ce2d7ebc5df6

**Comment by qiutiaoming** [comment]
@phreatom ,Thansk for your test. 
@xrmx  I think docs should add one column about the very basic version of db supported.

**Comment by mistercrunch** [comment]
I'm not sure what you mean by that.
